import { createHash } from "node:crypto";

import type { ArtifactPromotionReceiptClaims, ArtifactWriteLeaseClaims } from "@opencrane/backend/artifacts/authorization";
import type { ArtifactServicePromotionPort, ArtifactUploadCryptoPort } from "@opencrane/backend/server/agents/artifacts";
import { WorkflowTaskTerminalError } from "@opencrane/backend/server/infra/workflows/contract";
import { GENERATED_CSV_MEDIA_TYPE } from "@opencrane/models/conversation-assets";
import { describe, expect, it, vi } from "vitest";

import { GeneratedFileArtifactPromotionPort } from "../generated-file-artifact-promotion-port";
import type { GeneratedFilePromotionAuthority, GeneratedFilePromotionAuthorityEvidence } from "../generated-file-promotion.types";
import type { PromoteGeneratedFileCommand } from "../../workflow/generated-file-workflow.types";

/** Stable generated bytes accepted by the promotion adapter. */
const _CONTENT = new TextEncoder().encode("name,value\r\nalpha,1\r\n");
/** Full immutable address of the generated bytes. */
const _CONTENT_ADDRESS = `sha256:${createHash("sha256").update(_CONTENT).digest("hex")}`;

/** Return one exact promotion command under a future original deadline. */
function _Command(overrides: Partial<PromoteGeneratedFileCommand> = {}): PromoteGeneratedFileCommand
{
	return { siloId: "silo-1", operationId: "operation-1", artifactId: "artifact-1", artifactRevisionId: "revision-1", uploadLeaseId: "lease-1", contentAddress: _CONTENT_ADDRESS, byteLength: _CONTENT.byteLength, mediaType: GENERATED_CSV_MEDIA_TYPE, notAfterEpochMs: Date.now() + 60_000, content: _CONTENT, ...overrides };
}

/** Build the original fixed write lease for one command. */
function _Lease(command: PromoteGeneratedFileCommand, overrides: Partial<ArtifactWriteLeaseClaims> = {}): ArtifactWriteLeaseClaims
{
	return { leaseId: command.uploadLeaseId, siloId: command.siloId, artifactId: command.artifactId, action: "artifact.write", expiresAtEpochSeconds: Math.floor((command.notAfterEpochMs - 1_000) / 1_000), expectedContentAddress: command.contentAddress, expectedByteLength: command.byteLength, mediaType: command.mediaType, ...overrides };
}

/** Return a verified receipt with fields matching one command. */
function _Receipt(command: PromoteGeneratedFileCommand, overrides: Partial<ArtifactPromotionReceiptClaims> = {}): ArtifactPromotionReceiptClaims
{
	return { leaseId: command.uploadLeaseId, contentAddress: command.contentAddress, byteLength: command.byteLength, mediaType: command.mediaType, issuedAtEpochSeconds: Math.floor(Date.now() / 1_000), ...overrides };
}

/** Mutable synthetic dependencies for one promotion adapter. */
interface _Harness
{
	/** Current-authority call observed by tests. */
	readonly admitCurrent: ReturnType<typeof vi.fn>;
	/** Signing and verification dependency. */
	readonly crypto: ArtifactUploadCryptoPort;
	/** Adapter under test. */
	readonly port: GeneratedFileArtifactPromotionPort;
	/** Existing Artifact service transport observed by tests. */
	readonly servicePromote: ReturnType<typeof vi.fn>;
}

/** Compose a promotion adapter without reading mounted keys or making network requests. */
function _HarnessFor(command: PromoteGeneratedFileCommand, evidence?: GeneratedFilePromotionAuthorityEvidence | null): _Harness
{
	const admitted = evidence === undefined ? { lease: _Lease(command), notAfterEpochMs: command.notAfterEpochMs } : evidence;
	const admitCurrent = vi.fn().mockResolvedValue(admitted);
	const authority = { admitCurrent } as unknown as GeneratedFilePromotionAuthority;
	const servicePromote = vi.fn().mockResolvedValue({ receipt: "compact-receipt" });
	const service = { promote: servicePromote } as unknown as ArtifactServicePromotionPort;
	const crypto: ArtifactUploadCryptoPort = {
		signLease: vi.fn().mockReturnValue("compact-lease"),
		verifyReceipt: vi.fn().mockReturnValue(_Receipt(command)),
		digestReceipt: vi.fn().mockReturnValue(`sha256:${"d".repeat(64)}`),
	};
	return { admitCurrent, crypto, port: new GeneratedFileArtifactPromotionPort(authority, service, crypto), servicePromote };
}

/** Collect the exact chunks passed to the existing streaming service port. */
async function _Collect(chunks: AsyncIterable<Uint8Array>): Promise<Uint8Array>
{
	const values: number[] = [];
	for await (const chunk of chunks)
		values.push(...chunk);
	return new Uint8Array(values);
}

describe("generated file Artifact promotion port", function _Suite()
{
	it("reloads the exact fixed lease immediately before one verified byte transfer", async function _Promotes()
	{
		const command = _Command();
		const harness = _HarnessFor(command);
		harness.servicePromote.mockImplementation(async function _Promote(_lease: string, bytes: AsyncIterable<Uint8Array>)
		{
			expect(await _Collect(bytes)).toEqual(_CONTENT);
			return { receipt: "compact-receipt" };
		});

		await expect(harness.port.promote(command)).resolves.toEqual({ leaseId: "lease-1", contentAddress: _CONTENT_ADDRESS, byteLength: _CONTENT.byteLength, mediaType: GENERATED_CSV_MEDIA_TYPE, receiptDigest: `sha256:${"d".repeat(64)}` });

		expect(harness.admitCurrent).toHaveBeenCalledExactlyOnceWith({ siloId: "silo-1", operationId: "operation-1", artifactId: "artifact-1", artifactRevisionId: "revision-1", uploadLeaseId: "lease-1", contentAddress: _CONTENT_ADDRESS, byteLength: _CONTENT.byteLength, mediaType: GENERATED_CSV_MEDIA_TYPE, notAfterEpochMs: command.notAfterEpochMs }, expect.any(Date));
		expect(harness.crypto.signLease).toHaveBeenCalledExactlyOnceWith(_Lease(command));
		expect(harness.servicePromote).toHaveBeenCalledOnce();
		expect(harness.admitCurrent.mock.invocationCallOrder[0]).toBeLessThan(harness.servicePromote.mock.invocationCallOrder[0]!);
	});

	it("does not sign or transfer after current authority records its terminal denial", async function _RejectsEndedAuthority()
	{
		const command = _Command();
		const harness = _HarnessFor(command, null);

		await expect(harness.port.promote(command)).rejects.toBeInstanceOf(WorkflowTaskTerminalError);

		expect(harness.crypto.signLease).not.toHaveBeenCalled();
		expect(harness.servicePromote).not.toHaveBeenCalled();
	});

	it.each([
		["lease id", { leaseId: "lease-other" }],
		["silo", { siloId: "silo-other" }],
		["artifact", { artifactId: "artifact-other" }],
		["content", { expectedContentAddress: `sha256:${"a".repeat(64)}` }],
		["length", { expectedByteLength: _CONTENT.byteLength + 1 }],
		["media type", { mediaType: "text/plain" }],
	])("rejects a fixed lease with a mismatching %s", async function _RejectsLease(_label, override)
	{
		const command = _Command();
		const evidence = { lease: _Lease(command, override), notAfterEpochMs: command.notAfterEpochMs };
		const harness = _HarnessFor(command, evidence);

		await expect(harness.port.promote(command)).rejects.toBeInstanceOf(WorkflowTaskTerminalError);

		expect(harness.servicePromote).not.toHaveBeenCalled();
	});

	it("rejects substituted plaintext before asking current authority for a lease", async function _RejectsSubstitutedContent()
	{
		const command = _Command({ content: new TextEncoder().encode("different") });
		const harness = _HarnessFor(command);

		await expect(harness.port.promote(command)).rejects.toBeInstanceOf(WorkflowTaskTerminalError);

		expect(harness.admitCurrent).not.toHaveBeenCalled();
		expect(harness.servicePromote).not.toHaveBeenCalled();
	});

	it("rejects a verified receipt for another lease without returning promotion metadata", async function _RejectsForeignReceipt()
	{
		const command = _Command();
		const harness = _HarnessFor(command);
		vi.mocked(harness.crypto.verifyReceipt).mockReturnValue(_Receipt(command, { leaseId: "lease-other" }));

		await expect(harness.port.promote(command)).rejects.toBeInstanceOf(WorkflowTaskTerminalError);

		expect(harness.crypto.digestReceipt).not.toHaveBeenCalled();
	});

	it("does not replace or extend a mismatching original authority deadline", async function _RejectsChangedDeadline()
	{
		const command = _Command();
		const evidence = { lease: _Lease(command), notAfterEpochMs: command.notAfterEpochMs + 1_000 };
		const harness = _HarnessFor(command, evidence);

		await expect(harness.port.promote(command)).rejects.toBeInstanceOf(WorkflowTaskTerminalError);

		expect(harness.servicePromote).not.toHaveBeenCalled();
	});
});
