import { Buffer } from "node:buffer";
import { createHash } from "node:crypto";

import type { ConversationPrivatePayloadCipher, ConversationPrivatePayloadCoordinates, EncryptedConversationPrivatePayload } from "@opencrane/backend/server/conversations/history";

import { GeneratedFileCustodyManifestVersions, type GeneratedFileCustodyIdentity, type GeneratedFileCustodyManifest, type GeneratedFileCustodyManifestChunk, type GeneratedFilePayloadReferenceCoordinates, type SealGeneratedFileCommand, type SealedGeneratedFile, type SealedGeneratedFileChunk } from "./file-custody.types";

/** Limits that keep generated bytes within existing encrypted text custody. */
export const GENERATED_FILE_CUSTODY_LIMITS = Object.freeze({
	fileBytes: 1_048_576,
	chunkBytes: 49_152,
	cipherPlaintextBytes: 65_536,
	identifierCharacters: 512,
});

/** Canonical padded base64 accepted from the private-payload cipher. */
const _CANONICAL_BASE64 = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/u;
/** Exact lowercase SHA-256 address used for plaintext and ciphertext evidence. */
const _SHA256 = /^sha256:[0-9a-f]{64}$/u;
/** Versioned domain separator for stable private-payload row references. */
const _PAYLOAD_REF_DOMAIN = "opencrane.generated-file-custody.chunk.v1";
/** Versioned domain separator for the complete ordered ciphertext manifest. */
const _MANIFEST_DOMAIN = "opencrane.generated-file-custody.manifest.v1";

/**
 * Seals one complete generated file into fresh encrypted chunks.
 * Callers persist the returned manifest and rows in one transaction. A retry must load those saved
 * rows rather than call this function again, because every first capture intentionally uses fresh
 * AES-GCM nonces even though its payload references are stable.
 */
export function __SealGeneratedFile(cipher: ConversationPrivatePayloadCipher, command: SealGeneratedFileCommand): SealedGeneratedFile
{
	_ValidateIdentity(command);
	if (!_ByteArray(command.bytes))
		throw new Error("Generated file custody requires exact bytes");
	const bytes = Buffer.from(command.bytes);
	if (bytes.byteLength < 1 || bytes.byteLength > GENERATED_FILE_CUSTODY_LIMITS.fileBytes)
		throw new Error("Generated file custody requires 1 to 1048576 bytes");
	const contentAddress = _Digest(bytes);
	const chunkCount = Math.ceil(bytes.byteLength / GENERATED_FILE_CUSTODY_LIMITS.chunkBytes);
	const chunks: SealedGeneratedFileChunk[] = [];
	const manifestChunks: GeneratedFileCustodyManifestChunk[] = [];
	for (let index = 0; index < chunkCount; index += 1)
	{
		const start = index * GENERATED_FILE_CUSTODY_LIMITS.chunkBytes;
		const chunkBytes = bytes.subarray(start, Math.min(start + GENERATED_FILE_CUSTODY_LIMITS.chunkBytes, bytes.byteLength));
		const reference = { ..._Identity(command), byteLength: bytes.byteLength, chunkIndex: index, chunkCount, contentAddress };
		const payloadRef = __ExpectedGeneratedFilePayloadRef(reference);
		const coordinates = _CipherCoordinates(command, payloadRef);
		const plaintext = chunkBytes.toString("base64");
		if (Buffer.byteLength(plaintext, "utf8") > GENERATED_FILE_CUSTODY_LIMITS.cipherPlaintextBytes)
			throw new Error("Generated file custody chunk exceeded private payload capacity");
		const payload = cipher.encrypt(plaintext, coordinates);
		chunks.push({ coordinates, idempotencyKey: payloadRef, index, payload, payloadRef });
		manifestChunks.push({ ciphertextDigest: payload.ciphertextDigest, decodedByteLength: chunkBytes.byteLength, index, payloadRef });
	}
	const evidence = { version: GeneratedFileCustodyManifestVersions.V1, ..._Identity(command), byteLength: bytes.byteLength, chunkCount, chunks: manifestChunks, contentAddress };
	const manifest: GeneratedFileCustodyManifest = { ...evidence, ciphertextManifestDigest: _ManifestDigest(evidence) };
	return { chunks, manifest };
}

/** Reconstructs bytes only after the complete manifest, ciphertext order, base64 and digest checks pass. */
export function __OpenGeneratedFile(cipher: ConversationPrivatePayloadCipher, manifestValue: unknown, chunkValues: unknown): Uint8Array
{
	const manifest = _ParseManifest(manifestValue);
	if (manifest === null)
		throw new Error("Generated file custody manifest is invalid");
	const chunks = _ParseChunks(chunkValues);
	if (chunks === null || chunks.length !== manifest.chunkCount)
		throw new Error("Generated file custody chunks do not match manifest");
	const plaintextChunks: Buffer[] = [];
	for (let index = 0; index < manifest.chunkCount; index += 1)
	{
		const evidence = manifest.chunks[index]!;
		const chunk = chunks[index]!;
		const reference = { ..._Identity(manifest), byteLength: manifest.byteLength, chunkIndex: index, chunkCount: manifest.chunkCount, contentAddress: manifest.contentAddress };
		const payloadRef = __ExpectedGeneratedFilePayloadRef(reference);
		const coordinates = _CipherCoordinates(manifest, payloadRef);
		if (evidence.index !== index || chunk.index !== index || evidence.payloadRef !== payloadRef || chunk.payloadRef !== payloadRef || chunk.idempotencyKey !== payloadRef
			|| evidence.ciphertextDigest !== chunk.payload.ciphertextDigest || !_SameCoordinates(chunk.coordinates, coordinates))
			throw new Error("Generated file custody chunks do not match manifest");
		const plaintext = cipher.decrypt(chunk.payload, coordinates);
		const decoded = _DecodeCanonicalBase64(plaintext);
		const expectedLength = _ExpectedChunkLength(manifest.byteLength, index, manifest.chunkCount);
		if (decoded === null || decoded.byteLength !== evidence.decodedByteLength || decoded.byteLength !== expectedLength)
			throw new Error("Generated file custody plaintext is invalid");
		plaintextChunks.push(decoded);
	}
	const bytes = Buffer.concat(plaintextChunks, manifest.byteLength);
	if (bytes.byteLength !== manifest.byteLength || _Digest(bytes) !== manifest.contentAddress)
		throw new Error("Generated file custody content digest does not match");
	return new Uint8Array(bytes);
}

/** Derives the stable opaque row reference from every immutable ownership and content coordinate. */
export function __ExpectedGeneratedFilePayloadRef(coordinates: GeneratedFilePayloadReferenceCoordinates): string
{
	_ValidateIdentity(coordinates);
	if (!_SHA256.test(coordinates.contentAddress) || !Number.isSafeInteger(coordinates.byteLength) || coordinates.byteLength < 1 || coordinates.byteLength > GENERATED_FILE_CUSTODY_LIMITS.fileBytes
		|| !Number.isSafeInteger(coordinates.chunkCount) || coordinates.chunkCount !== Math.ceil(coordinates.byteLength / GENERATED_FILE_CUSTODY_LIMITS.chunkBytes)
		|| !Number.isSafeInteger(coordinates.chunkIndex) || coordinates.chunkIndex < 0 || coordinates.chunkIndex >= coordinates.chunkCount)
		throw new Error("Generated file custody payload reference coordinates are invalid");
	const encoded = JSON.stringify([_PAYLOAD_REF_DOMAIN, coordinates.siloId, coordinates.conversationId, coordinates.agentIdentityId, coordinates.requesterPrincipalId, coordinates.requesterSubjectId, coordinates.operationId, coordinates.chunkIndex, coordinates.chunkCount, coordinates.contentAddress, coordinates.byteLength]);
	return `generated-file-chunk:${createHash("sha256").update(encoded, "utf8").digest("hex")}`;
}

/** Parses and verifies a complete content-free manifest from persistence. */
function _ParseManifest(value: unknown): GeneratedFileCustodyManifest | null
{
	if (!_Record(value) || !_ExactKeys(value, ["version", "siloId", "conversationId", "agentIdentityId", "requesterPrincipalId", "requesterSubjectId", "operationId", "byteLength", "chunkCount", "chunks", "ciphertextManifestDigest", "contentAddress"]))
		return null;
	const identity = _ParseIdentity(value);
	if (identity === null || value["version"] !== GeneratedFileCustodyManifestVersions.V1 || typeof value["contentAddress"] !== "string" || !_SHA256.test(value["contentAddress"])
		|| typeof value["ciphertextManifestDigest"] !== "string" || !_SHA256.test(value["ciphertextManifestDigest"]))
		return null;
	const byteLength = value["byteLength"];
	const chunkCount = value["chunkCount"];
	const chunksValue = value["chunks"];
	if (!Number.isSafeInteger(byteLength) || typeof byteLength !== "number" || byteLength < 1 || byteLength > GENERATED_FILE_CUSTODY_LIMITS.fileBytes
		|| !Number.isSafeInteger(chunkCount) || typeof chunkCount !== "number" || chunkCount !== Math.ceil(byteLength / GENERATED_FILE_CUSTODY_LIMITS.chunkBytes)
		|| !Array.isArray(chunksValue) || chunksValue.length !== chunkCount)
		return null;
	const chunks: GeneratedFileCustodyManifestChunk[] = [];
	const refs = new Set<string>();
	for (let index = 0; index < chunkCount; index += 1)
	{
		const chunk = _ParseManifestChunk(chunksValue[index]);
		const expectedLength = _ExpectedChunkLength(byteLength, index, chunkCount);
		if (chunk === null || chunk.index !== index || chunk.decodedByteLength !== expectedLength || refs.has(chunk.payloadRef))
			return null;
		refs.add(chunk.payloadRef);
		chunks.push(chunk);
	}
	const evidence = { version: GeneratedFileCustodyManifestVersions.V1, ...identity, byteLength, chunkCount, chunks, contentAddress: value["contentAddress"] };
	if (_ManifestDigest(evidence) !== value["ciphertextManifestDigest"])
		return null;
	return { ...evidence, ciphertextManifestDigest: value["ciphertextManifestDigest"] };
}

/** Parses one ordered manifest entry without accepting extra persistence fields. */
function _ParseManifestChunk(value: unknown): GeneratedFileCustodyManifestChunk | null
{
	if (!_Record(value) || !_ExactKeys(value, ["ciphertextDigest", "decodedByteLength", "index", "payloadRef"]))
		return null;
	const ciphertextDigest = value["ciphertextDigest"];
	const decodedByteLength = value["decodedByteLength"];
	const index = value["index"];
	const payloadRef = value["payloadRef"];
	if (typeof ciphertextDigest !== "string" || !_SHA256.test(ciphertextDigest) || typeof decodedByteLength !== "number" || !Number.isSafeInteger(decodedByteLength)
		|| decodedByteLength < 1 || decodedByteLength > GENERATED_FILE_CUSTODY_LIMITS.chunkBytes || typeof index !== "number" || !Number.isSafeInteger(index)
		|| typeof payloadRef !== "string" || !payloadRef.startsWith("generated-file-chunk:") || payloadRef.length !== 85)
		return null;
	return { ciphertextDigest, decodedByteLength, index, payloadRef };
}

/** Parses encrypted rows from a transaction result before any decryption is attempted. */
function _ParseChunks(value: unknown): readonly SealedGeneratedFileChunk[] | null
{
	if (!Array.isArray(value))
		return null;
	const chunks: SealedGeneratedFileChunk[] = [];
	for (const item of value)
	{
		if (!_Record(item) || !_ExactKeys(item, ["coordinates", "idempotencyKey", "index", "payload", "payloadRef"]))
			return null;
		const coordinates = _ParseCipherCoordinates(item["coordinates"]);
		const payload = _ParsePayload(item["payload"]);
		if (coordinates === null || payload === null || typeof item["idempotencyKey"] !== "string" || typeof item["payloadRef"] !== "string"
			|| typeof item["index"] !== "number" || !Number.isSafeInteger(item["index"]))
			return null;
		chunks.push({ coordinates, idempotencyKey: item["idempotencyKey"], index: item["index"], payload, payloadRef: item["payloadRef"] });
	}
	return chunks;
}

/** Parses the exact cipher representation stored in a ConversationPrivatePayload row. */
function _ParsePayload(value: unknown): EncryptedConversationPrivatePayload | null
{
	if (!_Record(value) || !_ExactKeys(value, ["authTag", "ciphertext", "ciphertextDigest", "keyId", "nonce"]))
		return null;
	const authTag = value["authTag"];
	const ciphertext = value["ciphertext"];
	const ciphertextDigest = value["ciphertextDigest"];
	const keyId = value["keyId"];
	const nonce = value["nonce"];
	if (!_ByteArray(authTag) || authTag.byteLength !== 16 || !_ByteArray(ciphertext) || ciphertext.byteLength > GENERATED_FILE_CUSTODY_LIMITS.cipherPlaintextBytes
		|| typeof ciphertextDigest !== "string" || !_SHA256.test(ciphertextDigest) || typeof keyId !== "string" || !_Identifier(keyId)
		|| !_ByteArray(nonce) || nonce.byteLength !== 12)
		return null;
	return { authTag: new Uint8Array(authTag), ciphertext: new Uint8Array(ciphertext), ciphertextDigest, keyId, nonce: new Uint8Array(nonce) };
}

/** Computes the digest over every ordered, content-free ciphertext manifest field. */
function _ManifestDigest(evidence: Omit<GeneratedFileCustodyManifest, "ciphertextManifestDigest">): string
{
	const encoded = JSON.stringify([_MANIFEST_DOMAIN, evidence.version, evidence.siloId, evidence.conversationId, evidence.agentIdentityId, evidence.requesterPrincipalId, evidence.requesterSubjectId, evidence.operationId, evidence.byteLength, evidence.chunkCount, evidence.contentAddress, evidence.chunks.map(function _Chunk(chunk) { return [chunk.index, chunk.decodedByteLength, chunk.payloadRef, chunk.ciphertextDigest]; })]);
	return _Digest(Buffer.from(encoded, "utf8"));
}

/** Returns immutable identity fields without retaining a command's byte buffer. */
function _Identity(value: GeneratedFileCustodyIdentity): GeneratedFileCustodyIdentity
{
	return { siloId: value.siloId, conversationId: value.conversationId, agentIdentityId: value.agentIdentityId, requesterPrincipalId: value.requesterPrincipalId, requesterSubjectId: value.requesterSubjectId, operationId: value.operationId };
}

/** Parses and validates persisted identity coordinates. */
function _ParseIdentity(value: Record<string, unknown>): GeneratedFileCustodyIdentity | null
{
	const identity = { siloId: value["siloId"], conversationId: value["conversationId"], agentIdentityId: value["agentIdentityId"], requesterPrincipalId: value["requesterPrincipalId"], requesterSubjectId: value["requesterSubjectId"], operationId: value["operationId"] };
	if (!Object.values(identity).every(function _Valid(item) { return typeof item === "string" && _Identifier(item); }))
		return null;
	return identity as GeneratedFileCustodyIdentity;
}

/** Rejects empty, normalized, control-bearing, or unbounded identity coordinates. */
function _ValidateIdentity(value: GeneratedFileCustodyIdentity): void
{
	if (![value.siloId, value.conversationId, value.agentIdentityId, value.requesterPrincipalId, value.requesterSubjectId, value.operationId].every(_Identifier))
		throw new Error("Generated file custody coordinates are invalid");
}

/** Checks one exact bounded identifier used only in cryptographic coordinate derivation. */
function _Identifier(value: unknown): value is string
{
	return typeof value === "string" && value.length > 0 && value.length <= GENERATED_FILE_CUSTODY_LIMITS.identifierCharacters && value === value.trim() && !/[\p{Cc}]/u.test(value);
}

/** Derives the existing cipher's authenticated coordinates from requester ownership. */
function _CipherCoordinates(identity: GeneratedFileCustodyIdentity, payloadRef: string): ConversationPrivatePayloadCoordinates
{
	return { siloId: identity.siloId, conversationId: identity.conversationId, authorSubject: identity.agentIdentityId, payloadRef };
}

/** Parses exact authenticated cipher coordinates from persistence. */
function _ParseCipherCoordinates(value: unknown): ConversationPrivatePayloadCoordinates | null
{
	if (!_Record(value) || !_ExactKeys(value, ["siloId", "conversationId", "authorSubject", "payloadRef"]))
		return null;
	if (!_Identifier(value["siloId"]) || !_Identifier(value["conversationId"]) || !_Identifier(value["authorSubject"]) || !_Identifier(value["payloadRef"]))
		return null;
	return { siloId: value["siloId"], conversationId: value["conversationId"], authorSubject: value["authorSubject"], payloadRef: value["payloadRef"] };
}

/** Compares all AES-GCM additional-data fields without normalization. */
function _SameCoordinates(left: ConversationPrivatePayloadCoordinates, right: ConversationPrivatePayloadCoordinates): boolean
{
	return left.siloId === right.siloId && left.conversationId === right.conversationId && left.authorSubject === right.authorSubject && left.payloadRef === right.payloadRef;
}

/** Returns the only valid decoded length for one deterministic chunk position. */
function _ExpectedChunkLength(byteLength: number, index: number, chunkCount: number): number
{
	if (index < chunkCount - 1)
		return GENERATED_FILE_CUSTODY_LIMITS.chunkBytes;
	return byteLength - (index * GENERATED_FILE_CUSTODY_LIMITS.chunkBytes);
}

/** Decodes only padded canonical base64 with no whitespace or alternate spellings. */
function _DecodeCanonicalBase64(value: string): Buffer | null
{
	if (value.length < 1 || value.length > GENERATED_FILE_CUSTODY_LIMITS.cipherPlaintextBytes || value.length % 4 !== 0 || !_CANONICAL_BASE64.test(value))
		return null;
	const decoded = Buffer.from(value, "base64");
	return decoded.toString("base64") === value ? decoded : null;
}

/** Computes the lowercase full SHA-256 address of exact bytes. */
function _Digest(value: Uint8Array): string
{
	return `sha256:${createHash("sha256").update(value).digest("hex")}`;
}

/** Accepts Buffer and Uint8Array values returned by Prisma without accepting arrays. */
function _ByteArray(value: unknown): value is Uint8Array
{
	return value instanceof Uint8Array;
}

/** Accepts one non-array object from typed code or parsed persistence JSON. */
function _Record(value: unknown): value is Record<string, unknown>
{
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Requires every named field and rejects extra mutable persistence data. */
function _ExactKeys(value: Record<string, unknown>, expected: readonly string[]): boolean
{
	const actual = Object.keys(value).sort();
	const sortedExpected = [...expected].sort();
	return actual.length === sortedExpected.length && actual.every(function _Matches(key, index) { return key === sortedExpected[index]; });
}
