import type { ConversationPrivatePayloadCoordinates, EncryptedConversationPrivatePayload } from "@opencrane/backend/server/conversations/history";

/** Immutable requester and operation coordinates bound into every generated-file chunk. */
export interface GeneratedFileCustodyIdentity
{
	/** Agent identity that authored the generated bytes and owns each encrypted payload row. */
	readonly agentIdentityId: string;
	/** Conversation that will own the generated file. */
	readonly conversationId: string;
	/** Stable operation that captured the generated bytes. */
	readonly operationId: string;
	/** Local Principal that will own the generated Artifact. */
	readonly requesterPrincipalId: string;
	/** Participant subject stored with the encrypted conversation payload row. */
	readonly requesterSubjectId: string;
	/** Silo that owns the conversation and generated file. */
	readonly siloId: string;
}

/** Command that seals one bounded generated file into encrypted persistence chunks. */
export interface SealGeneratedFileCommand extends GeneratedFileCustodyIdentity
{
	/** Exact non-empty generated bytes, copied before encryption. */
	readonly bytes: Uint8Array;
}

/** Complete inputs used to derive one stable opaque payload reference. */
export interface GeneratedFilePayloadReferenceCoordinates extends GeneratedFileCustodyIdentity
{
	/** Total byte length of the complete generated file. */
	readonly byteLength: number;
	/** Zero-based position of this chunk in the complete file. */
	readonly chunkIndex: number;
	/** Total number of chunks in the complete file. */
	readonly chunkCount: number;
	/** SHA-256 address of the complete generated file. */
	readonly contentAddress: string;
}

/** Persisted format version for a generated-file custody manifest. */
export enum GeneratedFileCustodyManifestVersions
{
	/** First format: ordered encrypted chunk evidence plus complete content identity. Renaming this member's value would make saved manifests unreadable. */
	V1 = "generated-file-custody.v1",
}

/** Ordered evidence for one ciphertext row referenced by a custody manifest. */
export interface GeneratedFileCustodyManifestChunk
{
	/** SHA-256 digest recorded by the private-payload cipher for this exact ciphertext. */
	readonly ciphertextDigest: string;
	/** Decoded byte length expected after canonical base64 decryption. */
	readonly decodedByteLength: number;
	/** Zero-based position of this chunk. */
	readonly index: number;
	/** Deterministic opaque reference used as the private-payload row identity. */
	readonly payloadRef: string;
}

/** Content-free manifest that binds a complete file to its ordered encrypted rows. */
export interface GeneratedFileCustodyManifest extends GeneratedFileCustodyIdentity
{
	/** Exact non-zero byte length of the complete generated file. */
	readonly byteLength: number;
	/** Number of encrypted rows required to reconstruct the file. */
	readonly chunkCount: number;
	/** Ordered references and ciphertext digests for every encrypted row. */
	readonly chunks: readonly GeneratedFileCustodyManifestChunk[];
	/** SHA-256 digest over every manifest field and ordered ciphertext entry. */
	readonly ciphertextManifestDigest: string;
	/** SHA-256 content address of the complete plaintext bytes. */
	readonly contentAddress: string;
	/** Persisted format that selects the exact validation rules. */
	readonly version: GeneratedFileCustodyManifestVersions;
}

/** One encrypted row ready for the caller's existing ConversationPrivatePayload transaction. */
export interface SealedGeneratedFileChunk
{
	/** Coordinates authenticated by AES-GCM and stored beside the ciphertext. */
	readonly coordinates: ConversationPrivatePayloadCoordinates;
	/** Deterministic retry key; the caller must reuse the saved row instead of sealing again. */
	readonly idempotencyKey: string;
	/** Zero-based position matching the manifest entry. */
	readonly index: number;
	/** Encrypted canonical-base64 chunk produced with a fresh nonce. */
	readonly payload: EncryptedConversationPrivatePayload;
	/** Deterministic private-payload row identity matching the manifest entry. */
	readonly payloadRef: string;
}

/** Fresh ciphertext rows and the exact manifest a retry must reuse. */
export interface SealedGeneratedFile
{
	/** Fresh ciphertext rows in reconstruction order. */
	readonly chunks: readonly SealedGeneratedFileChunk[];
	/** Content-free evidence required to validate and reconstruct the rows. */
	readonly manifest: GeneratedFileCustodyManifest;
}
