"""Keep OpenAI container-file coordinates private while admitting generated bytes.

Only this adapter understands OpenAI response annotations and the container-files API.  The model
loop gives it final Pydantic events and receives plain output dictionaries whose bytes have been
classified locally.  Provider identifiers, response bodies, headers, and authentication never
cross that boundary.
"""

from __future__ import annotations

import hashlib
import io
import re
import unicodedata
import zipfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Literal, TypedDict

from ..observability import trace


MAX_GENERATED_OUTPUT_FILES = 10
MAX_GENERATED_OUTPUT_BYTES = 200 * 1024 * 1024
_STREAM_CHUNK_BYTES = 64 * 1024
_MAX_DISPLAY_STEM_CHARACTERS = 72
_ADMITTED_CAPABILITIES = frozenset({"code_execution_files", "image_png"})


class NeutralGeneratedOutput(TypedDict):
    """The provider-neutral output shape consumed by the core model loop."""

    type: Literal["output_asset"]
    content: bytes
    displayName: str
    mediaType: str
    outputOrdinal: int


@dataclass(frozen=True)
class OpenAIGeneratedOutputConfiguration:
    """Exact Pydantic capabilities and model settings for admitted generated outputs."""

    capabilities: tuple[object, ...]
    model_settings: Mapping[str, object]


@dataclass(frozen=True)
class OpenAIContainerFileReference:
    """Attempt-private coordinates extracted from one final OpenAI text annotation."""

    container_id: str
    file_id: str
    filename: str


class OpenAIGeneratedOutputError(RuntimeError):
    """A safe visible failure that never includes provider data or credentials."""


@dataclass(frozen=True)
class _QueuedContainerFile:
    """One provider-private reference bound to its neutral output ordinal."""

    reference: OpenAIContainerFileReference
    output_ordinal: int


class OpenAIGeneratedOutputCollector:
    """Own provider event knowledge and one cumulative generated-file budget.

    The core loop observes framework events and receives at most a neutral in-memory output. OpenAI
    coordinates remain queued here until :meth:`finish` retrieves them through an attempt-scoped
    client. The collector is single-use because retrying a failed provider read is forbidden.
    """

    def __init__(self) -> None:
        """Create an empty collector for one model-loop attempt."""
        self._queued: list[_QueuedContainerFile] = []
        self._seen_references: set[tuple[str, str]] = set()
        self._direct_file_count = 0
        self._direct_byte_count = 0
        self._reserved_file_count = 0
        self._next_ordinal = 0
        self._finished = False

    def observe(self, event: object, ordinal: int) -> NeutralGeneratedOutput | None:
        """Observe one exact framework event without exposing provider coordinates."""
        if self._finished:
            raise OpenAIGeneratedOutputError("generated output collector is already finished")
        if not isinstance(ordinal, int) or ordinal < 0:
            raise OpenAIGeneratedOutputError("generated file ordinal is invalid")
        self._next_ordinal = max(self._next_ordinal, ordinal)

        direct_output = self._observe_completed_file_part(event)
        references = openai_container_file_references(event)
        for reference in references:
            identity = (reference.container_id, reference.file_id)
            if identity in self._seen_references:
                continue
            self._reserve_file()
            self._seen_references.add(identity)
            self._queued.append(_QueuedContainerFile(reference, self._take_ordinal()))
        return direct_output

    async def finish(
        self,
        *,
        base_url: str,
        attempt_key: str,
        http_client: object | None = None,
    ) -> list[NeutralGeneratedOutput]:
        """Retrieve all queued provider files once and return only neutral outputs."""
        if self._finished:
            raise OpenAIGeneratedOutputError("generated output collector is already finished")
        self._finished = True
        if not self._queued:
            return []
        return await retrieve_openai_generated_outputs(
            [queued.reference for queued in self._queued],
            base_url=base_url,
            attempt_key=attempt_key,
            starting_file_count=self._direct_file_count,
            starting_byte_count=self._direct_byte_count,
            output_ordinals=[queued.output_ordinal for queued in self._queued],
            http_client=http_client,
        )

    def _observe_completed_file_part(self, event: object) -> NeutralGeneratedOutput | None:
        """Map a final Pydantic FilePart by local bytes and the shared collector budget."""
        if getattr(event, "event_kind", None) != "part_start":
            return None
        part = getattr(event, "part", None)
        if getattr(part, "part_kind", None) != "file":
            return None
        binary_content = getattr(part, "content", None)
        content = getattr(binary_content, "data", None)
        claimed_media_type = getattr(binary_content, "media_type", None)
        if not isinstance(content, bytes):
            raise OpenAIGeneratedOutputError("generated file content is unsupported")
        media_type, extension = classify_generated_output_media(content)
        if claimed_media_type != media_type:
            raise OpenAIGeneratedOutputError("generated file media type does not match its content")
        self._reserve_file()
        self._direct_file_count += 1
        self._direct_byte_count += len(content)
        if self._direct_byte_count > MAX_GENERATED_OUTPUT_BYTES:
            raise OpenAIGeneratedOutputError("generated file batch exceeds its byte limit")
        output_ordinal = self._take_ordinal()
        return {
            "type": "output_asset",
            "content": content,
            "displayName": safe_generated_output_name("generated", content, output_ordinal, extension),
            "mediaType": media_type,
            "outputOrdinal": output_ordinal,
        }

    def _reserve_file(self) -> None:
        """Reserve one slot before any file can be observed or retrieved."""
        self._reserved_file_count += 1
        if self._reserved_file_count > MAX_GENERATED_OUTPUT_FILES:
            raise OpenAIGeneratedOutputError("generated file batch exceeds its file limit")

    def _take_ordinal(self) -> int:
        """Return one collision-free ordinal in observed provider order."""
        ordinal = self._next_ordinal
        self._next_ordinal += 1
        return ordinal


def openai_generated_output_configuration(
    admitted_capabilities: Sequence[str],
) -> OpenAIGeneratedOutputConfiguration:
    """Build only the native tools admitted by the immutable model route.

    Imports stay lazy so runtime protocol tests do not require provider packages. Unknown or
    repeated capability names fail closed instead of silently widening model authority.
    """
    capability_names = tuple(admitted_capabilities)
    if len(set(capability_names)) != len(capability_names):
        raise OpenAIGeneratedOutputError("generated-output capabilities are invalid")
    if set(capability_names) - _ADMITTED_CAPABILITIES:
        raise OpenAIGeneratedOutputError("generated-output capabilities are invalid")

    from pydantic_ai.capabilities import NativeTool
    from pydantic_ai.models.openai import OpenAIResponsesModelSettings
    from pydantic_ai.native_tools import CodeExecutionTool, ImageGenerationTool

    capabilities: list[object] = []
    if "image_png" in capability_names:
        capabilities.append(NativeTool(ImageGenerationTool(output_format="png", partial_images=0)))
    if "code_execution_files" in capability_names:
        capabilities.append(NativeTool(CodeExecutionTool()))
        model_settings = OpenAIResponsesModelSettings(
            openai_include_code_execution_outputs=True,
            openai_include_raw_annotations=True,
        )
    else:
        model_settings = OpenAIResponsesModelSettings()
    return OpenAIGeneratedOutputConfiguration(tuple(capabilities), model_settings)


def openai_container_file_references(event: object) -> tuple[OpenAIContainerFileReference, ...]:
    """Extract exact container citations from the final annotation-bearing text delta.

    Pydantic AI 2.13 adds raw annotations only on the empty ``TextDone`` delta. Earlier text
    fragments and generic file annotations are deliberately ignored because they are not proof of a
    completed OpenAI container file.
    """
    if getattr(event, "event_kind", None) != "part_delta":
        return ()
    delta = getattr(event, "delta", None)
    if getattr(delta, "part_delta_kind", None) != "text" or getattr(delta, "content_delta", None) != "":
        return ()
    provider_details = getattr(delta, "provider_details", None)
    if not isinstance(provider_details, Mapping):
        return ()
    annotations = provider_details.get("annotations")
    if not isinstance(annotations, list):
        return ()

    references: list[OpenAIContainerFileReference] = []
    for annotation in annotations:
        if not isinstance(annotation, Mapping) or annotation.get("type") != "container_file_citation":
            continue
        container_id = annotation.get("container_id")
        file_id = annotation.get("file_id")
        filename = annotation.get("filename")
        if not all(isinstance(value, str) and value for value in (container_id, file_id, filename)):
            raise OpenAIGeneratedOutputError("generated file reference is invalid")
        references.append(OpenAIContainerFileReference(container_id, file_id, filename))
    return tuple(references)


async def retrieve_openai_generated_outputs(
    references: Sequence[OpenAIContainerFileReference],
    *,
    base_url: str,
    attempt_key: str,
    starting_ordinal: int = 0,
    starting_file_count: int = 0,
    starting_byte_count: int = 0,
    output_ordinals: Sequence[int] | None = None,
    http_client: object | None = None,
) -> list[NeutralGeneratedOutput]:
    """Retrieve and classify one complete attempt-scoped batch with zero retries.

    All provider reads finish before a neutral output list is returned, so count, cumulative size,
    retrieval, and file-type failures cannot result in partial publication.
    """
    unique_references = _unique_references(references)
    if not isinstance(starting_file_count, int) or not 0 <= starting_file_count <= MAX_GENERATED_OUTPUT_FILES:
        raise OpenAIGeneratedOutputError("generated file count is invalid")
    if not isinstance(starting_byte_count, int) or not 0 <= starting_byte_count <= MAX_GENERATED_OUTPUT_BYTES:
        raise OpenAIGeneratedOutputError("generated file byte count is invalid")
    if starting_file_count + len(unique_references) > MAX_GENERATED_OUTPUT_FILES:
        raise OpenAIGeneratedOutputError("generated file batch exceeds its file limit")
    if not isinstance(starting_ordinal, int) or starting_ordinal < 0:
        raise OpenAIGeneratedOutputError("generated file ordinal is invalid")
    if output_ordinals is None:
        resolved_ordinals = tuple(starting_ordinal + offset for offset in range(len(unique_references)))
    else:
        resolved_ordinals = tuple(output_ordinals)
        if len(resolved_ordinals) != len(unique_references) or any(
            not isinstance(value, int) or value < 0 for value in resolved_ordinals
        ):
            raise OpenAIGeneratedOutputError("generated file ordinals are invalid")
        if len(set(resolved_ordinals)) != len(resolved_ordinals):
            raise OpenAIGeneratedOutputError("generated file ordinals are invalid")
    if not base_url or not attempt_key:
        raise OpenAIGeneratedOutputError("generated file retrieval configuration is invalid")

    from openai import AsyncOpenAI

    client_arguments: dict[str, object] = {
        "api_key": attempt_key,
        "base_url": base_url,
        "max_retries": 0,
    }
    if http_client is not None:
        client_arguments["http_client"] = http_client
    try:
        client = AsyncOpenAI(**client_arguments)
    except Exception:
        raise OpenAIGeneratedOutputError("generated file retrieval configuration is invalid") from None
    outputs: list[NeutralGeneratedOutput] = []
    total_bytes = starting_byte_count
    try:
        for offset, reference in enumerate(unique_references):
            content = bytearray()
            ordinal = resolved_ordinals[offset]
            try:
                with trace("agent_runtime.output.fetch", outputOrdinal=ordinal) as span:
                    # The streaming wrapper is required by openai-python 2.54; its direct binary
                    # helper eagerly buffers despite exposing ``aiter_bytes``.
                    async with client.containers.files.content.with_streaming_response.retrieve(
                        reference.file_id,
                        container_id=reference.container_id,
                    ) as response:
                        async for chunk in response.iter_bytes(_STREAM_CHUNK_BYTES):
                            if not isinstance(chunk, bytes):
                                raise OpenAIGeneratedOutputError("generated file retrieval failed")
                            total_bytes += len(chunk)
                            if total_bytes > MAX_GENERATED_OUTPUT_BYTES:
                                raise OpenAIGeneratedOutputError("generated file batch exceeds its byte limit")
                            content.extend(chunk)
                    if span is not None:
                        span.set_attribute("byteLength", len(content))
            except OpenAIGeneratedOutputError:
                raise
            except Exception:
                raise OpenAIGeneratedOutputError("generated file retrieval failed") from None

            file_bytes = bytes(content)
            media_type, extension = classify_generated_output_media(file_bytes)
            outputs.append(
                {
                    "type": "output_asset",
                    "content": file_bytes,
                    "displayName": safe_generated_output_name(
                        reference.filename,
                        file_bytes,
                        ordinal,
                        extension,
                    ),
                    "mediaType": media_type,
                    "outputOrdinal": ordinal,
                },
            )
    finally:
        try:
            await client.close()
        except Exception:
            # Closing an attempt-owned client must not replace the already-safe operation outcome.
            pass
    return outputs


def classify_generated_output_media(content: bytes) -> tuple[str, str]:
    """Classify an approved generated file from its bytes, never claimed metadata."""
    if not isinstance(content, bytes) or not content:
        raise OpenAIGeneratedOutputError("generated file content is unsupported")
    if content.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png", "png"
    if content.startswith(b"%PDF-"):
        return "application/pdf", "pdf"
    if content.startswith(b"ID3") or _has_mpeg_audio_frame_header(content):
        return "audio/mpeg", "mp3"
    if content.startswith((b"PK\x03\x04", b"PK\x05\x06", b"PK\x07\x08")):
        return _classify_zip_media(content)
    raise OpenAIGeneratedOutputError("generated file content is unsupported")


def safe_generated_output_name(
    suggested_name: str,
    content: bytes,
    ordinal: int,
    extension: str | None = None,
) -> str:
    """Create a bounded path-free name with a byte-derived collision suffix and extension."""
    if not isinstance(ordinal, int) or ordinal < 0:
        raise OpenAIGeneratedOutputError("generated file ordinal is invalid")
    if extension is None:
        _, extension = classify_generated_output_media(content)
    normalized = unicodedata.normalize("NFKC", suggested_name if isinstance(suggested_name, str) else "")
    leaf = normalized.replace("\\", "/").rsplit("/", 1)[-1]
    stem = leaf.rsplit(".", 1)[0] if "." in leaf else leaf
    stem = re.sub(r"[^A-Za-z0-9 _.-]+", "-", stem)
    stem = re.sub(r"[ ._-]+", "-", stem).strip("-")[:_MAX_DISPLAY_STEM_CHARACTERS]
    if not stem:
        stem = f"generated-{ordinal + 1}"
    digest = hashlib.sha256(content).hexdigest()[:12]
    return f"{stem}-{ordinal + 1}-{digest}.{extension}"


def _unique_references(
    references: Sequence[OpenAIContainerFileReference],
) -> tuple[OpenAIContainerFileReference, ...]:
    """Validate and de-duplicate provider coordinates without exposing them on failure."""
    unique: list[OpenAIContainerFileReference] = []
    seen: set[tuple[str, str]] = set()
    for reference in references:
        if not isinstance(reference, OpenAIContainerFileReference):
            raise OpenAIGeneratedOutputError("generated file reference is invalid")
        if not reference.container_id or not reference.file_id or not reference.filename:
            raise OpenAIGeneratedOutputError("generated file reference is invalid")
        identity = (reference.container_id, reference.file_id)
        if identity in seen:
            continue
        seen.add(identity)
        unique.append(reference)
    return tuple(unique)


def _has_mpeg_audio_frame_header(content: bytes) -> bool:
    """Recognize an MPEG audio frame header while rejecting reserved layer/rate fields."""
    if len(content) < 4 or content[0] != 0xFF or content[1] & 0xE0 != 0xE0:
        return False
    version = (content[1] >> 3) & 0x03
    layer = (content[1] >> 1) & 0x03
    bitrate = (content[2] >> 4) & 0x0F
    sample_rate = (content[2] >> 2) & 0x03
    return version != 0x01 and layer != 0x00 and bitrate not in (0x00, 0x0F) and sample_rate != 0x03


def _classify_zip_media(content: bytes) -> tuple[str, str]:
    """Distinguish Office Open XML from a generic ZIP by archive members."""
    try:
        with zipfile.ZipFile(io.BytesIO(content)) as archive:
            names = frozenset(archive.namelist())
            if "[Content_Types].xml" in names and "word/document.xml" in names:
                return "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx"
            if "[Content_Types].xml" in names and "xl/workbook.xml" in names:
                return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"
            return "application/zip", "zip"
    except (OSError, zipfile.BadZipFile, zipfile.LargeZipFile):
        raise OpenAIGeneratedOutputError("generated file content is unsupported") from None
