/** Coordinates accepted by the injected rotating payload cipher. */
export interface RoutinePageCursorPayloadCoordinates
{
	/** Authenticated caller subject. */
	readonly authorSubject: string;
	/** Purpose-separated endpoint and optional routine coordinate. */
	readonly conversationId: string;
	/** Versioned caller and endpoint binding. */
	readonly payloadRef: string;
	/** Organisation derived from trusted request state. */
	readonly siloId: string;
}

/** Encrypted bytes returned by the shared rotating payload cipher. */
export interface RoutinePageCursorPayload
{
	/** Authentication tag protecting ciphertext and coordinates. */
	readonly authTag: Uint8Array;
	/** Ciphertext containing the continuation position. */
	readonly ciphertext: Uint8Array;
	/** Digest checked by the shared cipher before decryption. */
	readonly ciphertextDigest: string;
	/** Mounted key used to encrypt this token. */
	readonly keyId: string;
	/** Unique nonce generated by the shared cipher. */
	readonly nonce: Uint8Array;
}

/** Structural cipher port implemented by the mounted conversation payload cipher. */
export interface RoutinePageCursorPayloadCipher
{
	/** Decrypts after verifying key, digest, tag, and authenticated coordinates. */
	decrypt(payload: RoutinePageCursorPayload, coordinates: RoutinePageCursorPayloadCoordinates): string;
	/** Encrypts the position while the shared cipher owns key rotation and nonce generation. */
	encrypt(plaintext: string, coordinates: RoutinePageCursorPayloadCoordinates): RoutinePageCursorPayload;
}
