import type { JsonValue } from "@opencrane/util";

/**
 * Exact MCP discovery and runtime name for the governed CSV producer.
 * Renaming it changes admitted tool snapshots and server capture matching. The server compiler
 * gives each admitted revision its own model declaration name.
 */
export const GENERATED_CSV_TOOL_NAME = "opencrane_files_create_csv";

/** Media type produced by the shared CSV serialization policy. */
export const GENERATED_CSV_MEDIA_TYPE = "text/csv;charset=utf-8";

/** Limits that bound validation work and generated bytes. */
export const GENERATED_CSV_LIMITS = Object.freeze({
	generatedBytes: 1_048_576,
	displayNameCharacters: 128,
	headerCount: 64,
	headerBytes: 256,
	rowCount: 10_000,
	cellCount: 100_000,
	stringCellBytes: 4_096,
});

/** JSON Schema discovered for the generator's sole tool. Runtime validation repeats these rules. */
export const GENERATED_CSV_INPUT_SCHEMA: JsonValue = {
	type: "object",
	additionalProperties: false,
	required: ["displayName", "headers", "rows"],
	properties: {
		displayName: { type: "string", minLength: 5, maxLength: GENERATED_CSV_LIMITS.displayNameCharacters, pattern: "^[A-Za-z0-9](?:[A-Za-z0-9 ._-]{0,122}[A-Za-z0-9_-])?\\.csv$" },
		headers: { type: "array", minItems: 1, maxItems: GENERATED_CSV_LIMITS.headerCount, uniqueItems: true, items: { type: "string", minLength: 1, maxLength: GENERATED_CSV_LIMITS.headerBytes } },
		rows: {
			type: "array",
			maxItems: GENERATED_CSV_LIMITS.rowCount,
			items: {
				type: "array",
				maxItems: GENERATED_CSV_LIMITS.headerCount,
				items: { anyOf: [{ type: "string", maxLength: GENERATED_CSV_LIMITS.stringCellBytes }, { type: "number" }, { type: "boolean" }, { type: "null" }] },
			},
		},
	},
};
