// @vitest-environment jsdom

import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { PLATFORM_ID, type Type, ɵgetComponentDef as getComponentDef, ɵresolveComponentResources as resolveComponentResources } from "@angular/core";
import { TestBed, type ComponentFixture } from "@angular/core/testing";
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from "@angular/platform-browser-dynamic/testing";
import { MessageProcessor } from "@a2ui/angular/v0_8";
import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { ResourceFeedbackComponent } from "@opencrane/elements/ui";

import { ConversationA2uiDisplayStates, type ConversationA2uiDisplayPresentation } from "../../../a2ui/conversation-a2ui-display.types";
import { _ConversationA2uiDisplayCatalog } from "../conversation-a2ui-display.catalogue";
import { ConversationA2uiDisplayComponent } from "../conversation-a2ui-display.component";
import { _ConversationA2uiDisplayFixture } from "./conversation-a2ui-display.fixtures";

/** Production component resources are compiled here rather than replaced with test templates. */
const _COMPONENT_DIRECTORY = join(process.cwd(), "src/lib/components/conversation-a2ui-display");
/** The shared feedback element retains its real status and error markup in this composition test. */
const _FEEDBACK_DIRECTORY = resolve(process.cwd(), "../../elements/ui/src/lib/components/resource-feedback");

beforeAll(async function _InitializeAngular()
{
	TestBed.initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
	await resolveComponentResources(async function _ResolveResource(url): Promise<string>
	{
		const name = url.split("/").at(-1)!;
		if (name.startsWith("conversation-a2ui-display.") || name.startsWith("conversation-a2ui-text."))
			return readFileSync(join(_COMPONENT_DIRECTORY, name), "utf8");
		if (name.startsWith("resource-feedback."))
			return readFileSync(join(_FEEDBACK_DIRECTORY, name), "utf8");
		return "";
	});
});
afterEach(function _ResetTestBed() { TestBed.resetTestingModule(); vi.restoreAllMocks(); });
afterAll(function _ResetEnvironment() { TestBed.resetTestEnvironment(); });

/** Supply signal metadata normally generated by Angular's compiler, absent in raw TypeScript JIT. */
function _signalMetadata(component: Type<unknown>, names: readonly string[]): void
{
	const definition = getComponentDef(component)!;
	const inputs = { ...definition.inputs };
	const declaredInputs = { ...definition.declaredInputs };
	for (const name of names)
	{
		inputs[name] = [name, 1, null];
		declaredInputs[name] = name;
	}
	Object.assign(definition, { inputs, declaredInputs });
}

/** Mounts the real visual tree with its local catalogue, theme and processor. */
async function _fixture(presentation: ConversationA2uiDisplayPresentation): Promise<ComponentFixture<ConversationA2uiDisplayComponent>>
{
	// jsdom cannot parse the vendor's modern global CSS. Keep the real DOM renderers but leave
	// browser styling to the production-provider stories, which these unit tests do not qualify.
	TestBed.configureTestingModule({ imports: [ConversationA2uiDisplayComponent], providers: [{ provide: PLATFORM_ID, useValue: "server" }] });
	_signalMetadata(ConversationA2uiDisplayComponent, ["presentation"]);
	_signalMetadata(ResourceFeedbackComponent, ["loading", "loadingLabel", "error", "retryAvailable"]);
	const fixture = TestBed.createComponent(ConversationA2uiDisplayComponent);
	fixture.componentRef.setInput("presentation", presentation);
	fixture.detectChanges();
	await fixture.whenStable();
	fixture.detectChanges();
	return fixture;
}

describe("ConversationA2uiDisplayComponent", function _ReadOnlyResult()
{
	it("renders every admitted static component with semantic headings and no controls", async function _StaticCatalogue()
	{
		const fixture = await _fixture(_ConversationA2uiDisplayFixture());
		const element: HTMLElement = fixture.nativeElement;
		expect(element.querySelector("h2")?.textContent).toBe("Customer summary");
		expect(element.textContent).toContain("Customer records checked.");
		expect(element.querySelector("hr")).not.toBeNull();
		expect(element.querySelector("a2ui-row")).not.toBeNull();
		expect(element.querySelector("a2ui-column")).not.toBeNull();
		expect(element.querySelector("a2ui-card")).not.toBeNull();
		expect(element.querySelector("section")?.getAttribute("aria-label")).toBe("Company assistant structured result");
		expect(element.querySelector("button, input, select, textarea, a, img, iframe, audio, video")).toBeNull();
		expect(element.textContent).not.toContain("display-fixture");
	});

	it.each(["h1", "h2", "h3", "h4", "h5"] as const)("normalizes the %s heading hint beneath the route heading", async function _HeadingHierarchy(headingHint)
	{
		const fixture = await _fixture(_ConversationA2uiDisplayFixture("Customer records checked.", "display-fixture", headingHint));
		const element: HTMLElement = fixture.nativeElement;
		const headings = element.querySelectorAll("h2");
		expect(headings).toHaveLength(1);
		expect(headings[0]?.textContent).toBe("Customer summary");
		expect(headings[0]?.getAttribute("data-usage-hint")).toBe(headingHint);
		expect(element.querySelector("h1, h3, h4, h5, h6")).toBeNull();
		expect(element.querySelector("p:not(.conversation-a2ui-text__caption)")).not.toBeNull();
		expect(element.querySelector("p.conversation-a2ui-text__caption")?.textContent).toBe("Based on the records in this conversation.");
	});

	it("escapes HTML and markdown without fetching, dispatching or resolving another data model", async function _LiteralOnly()
	{
		const dispatch = vi.spyOn(MessageProcessor.prototype, "dispatch");
		const data = vi.spyOn(MessageProcessor.prototype, "getData");
		const mutation = vi.spyOn(MessageProcessor.prototype, "setData");
		const fetch = vi.spyOn(globalThis, "fetch");
		const text = "<img src='https://example.invalid/private'> [Open](https://example.invalid) <script>alert(1)</script>";
		const fixture = await _fixture(_ConversationA2uiDisplayFixture(text));
		const element: HTMLElement = fixture.nativeElement;
		expect(element.textContent).toContain(text);
		expect(element.querySelector("img, a, script")).toBeNull();
		expect(dispatch).not.toHaveBeenCalled();
		expect(data).not.toHaveBeenCalled();
		expect(mutation).not.toHaveBeenCalled();
		expect(fetch).not.toHaveBeenCalled();
	});

	it.each([ConversationA2uiDisplayStates.Waiting, ConversationA2uiDisplayStates.Unavailable])("removes a ready result when its projection becomes %s", async function _NoStaleResult(state)
	{
		const presentation = _ConversationA2uiDisplayFixture("Previous private display");
		const fixture = await _fixture(presentation);
		fixture.componentRef.setInput("presentation", { ...presentation, state, surface: null, detail: null });
		fixture.detectChanges();
		await fixture.whenStable();
		const element: HTMLElement = fixture.nativeElement;
		expect(element.textContent).not.toContain("Previous private display");
		expect(element.querySelector("a2ui-surface")).toBeNull();
		expect(element.querySelector("button")).toBeNull();
		if (state === ConversationA2uiDisplayStates.Waiting)
			expect(element.querySelector('[role="status"]')?.textContent).toContain("Waiting for the structured result");
		else
			expect(element.textContent).toContain("This structured result is unavailable.");
	});

	it("replaces reused component text and isolates processors across equal surface ids", async function _SeparateInstances()
	{
		const first = await _fixture(_ConversationA2uiDisplayFixture("First conversation"));
		const second = TestBed.createComponent(ConversationA2uiDisplayComponent);
		second.componentRef.setInput("presentation", _ConversationA2uiDisplayFixture("Second conversation"));
		second.detectChanges();
		await second.whenStable();
		expect(first.debugElement.injector.get(MessageProcessor)).not.toBe(second.debugElement.injector.get(MessageProcessor));
		first.componentRef.setInput("presentation", _ConversationA2uiDisplayFixture("Updated first conversation"));
		first.detectChanges();
		await first.whenStable();
		expect(first.nativeElement.textContent).toContain("Updated first conversation");
		expect(first.nativeElement.textContent).not.toContain("Second conversation");
		expect(second.nativeElement.textContent).toContain("Second conversation");
	});

	it("has no registry entry for controls, media or inherited object names", function _FiniteCatalogue()
	{
		const catalogue = _ConversationA2uiDisplayCatalog();
		expect(Object.keys(catalogue).sort()).toEqual(["Card", "Column", "Divider", "Row", "Text"]);
		expect(Object.getPrototypeOf(catalogue)).toBeNull();
		for (const name of ["Button", "TextField", "Image", "Video", "Modal", "constructor", "__proto__"])
			expect(catalogue[name]).toBeUndefined();
	});
});
