import { randomUUID } from "node:crypto";

import { AGENT_RUNTIME_PROJECTED_TOKEN_AUDIENCE, MANAGED_AGENT_RUNTIME_PROJECTED_TOKEN_AUDIENCE } from "@opencrane/contracts";
import { AgentRunState, WarmRuntimeReservationState, WorkloadAssignmentState, WorkloadKind, Prisma, type AgentRun, type RunProofKey, type WarmRuntimeReservation, type WorkloadAssignment, type WorkloadBootstrap } from "@prisma/client";

import type { WarmRuntimeBindingIdentity, WarmRuntimeBindingPersistenceRepository, WarmRuntimeBindingSubmission, WarmRuntimeDatabaseBindingResult } from "./warm-runtime-binding.types";

/**
 * Aborts a binding transaction after an ownership check or compare-and-set no longer matches.
 *
 * Throwing, instead of returning `conflict`, makes Prisma roll back assignment, bootstrap, proof,
 * and reservation writes already made in the transaction. The unit of work catches this error and
 * returns the public `conflict` outcome.
 *
 * Called by: {@link PrismaWarmRuntimeBindingRepository.bind} and
 * {@link PrismaWarmRuntimeBindingUnitOfWork.bind}.
 */
export class WarmRuntimeBindingConflict extends Error {}

/**
 * Checks and spends the rows that bind a reviewed warm Pod to one AgentRun attempt.
 *
 * The caller owns the serializable transaction. This repository returns database evidence for
 * later credential minting but never mints a credential itself.
 *
 * Called by: {@link PrismaWarmRuntimeBindingUnitOfWork.bind}.
 * @implements WarmRuntimeBindingPersistenceRepository
 */
export class PrismaWarmRuntimeBindingRepository implements WarmRuntimeBindingPersistenceRepository
{
	/** Transaction that owns every typed fence and semantic write. */
	private readonly transaction: Prisma.TransactionClient;

	/** Bind this repository to the unit of work's transaction. */
	constructor(transaction: Prisma.TransactionClient)
	{
		this.transaction = transaction;
	}

	/**
	 * Bind a Ready reservation or return the still-valid Claimed replay.
	 *
	 * It follows the lock and write order required by {@link WarmRuntimeBindingPersistenceRepository}.
	 *
	 * @param identity - Pod identity already reviewed by Kubernetes TokenReview.
	 * @param submission - Public proof generated by that Pod process.
	 * @returns The binding result and the earliest saved credential expiry.
	 * @throws WarmRuntimeBindingConflict When linked ownership, state, expiry, or a compare-and-set changes.
	 */
	async bind(identity: WarmRuntimeBindingIdentity, submission: WarmRuntimeBindingSubmission): Promise<WarmRuntimeDatabaseBindingResult>
	{
		// 1. Find a Ready or Claimed reservation without changing it, so missing work is a clean conflict.
		const discovered = await this.transaction.warmRuntimeReservation.findUnique({ where: { namespace_podUid: { namespace: identity.namespace, podUid: identity.podUid } } });
		if (discovered === null)
			return { outcome: "conflict" };
		if (discovered.state !== WarmRuntimeReservationState.Ready && discovered.state !== WarmRuntimeReservationState.Claimed)
			return { outcome: "conflict" };
		const replay = discovered.state === WarmRuntimeReservationState.Claimed;
		const expectedProof = replay ? submission.proofKeyThumbprint : null;
		const expectedBoundAt = replay ? { not: null } : null;

		// 2. Check the AgentRun before the reservation owner so every binding transaction uses this order.
		await _RequireFence(this.transaction.agentRun.updateMany({ where: { id: discovered.runId, attempt: discovered.attempt, state: { in: [AgentRunState.Assigned, AgentRunState.WaitingForInput] } }, data: { state: discovered.generation === 1 ? AgentRunState.Assigned : AgentRunState.WaitingForInput } }));
		await _RequireFence(this.transaction.warmRuntimeReservation.updateMany({
			where: { runId: discovered.runId, attempt: discovered.attempt, generation: discovered.generation, siloId: discovered.siloId, namespace: identity.namespace, podUid: identity.podUid, serviceAccountName: identity.serviceAccountName, state: discovered.state, proofKeyThumbprint: expectedProof, boundAt: expectedBoundAt, deleteRequestedAt: null, deletedAt: null },
			data: { state: discovered.state },
		}));
		const reservation = await this.transaction.warmRuntimeReservation.findUnique({ where: { runId_attempt_generation: { runId: discovered.runId, attempt: discovered.attempt, generation: discovered.generation } } });
		const assignment = await this.transaction.workloadAssignment.findUnique({ where: { runId_attempt: { runId: discovered.runId, attempt: discovered.attempt } } });
		const bootstrap = await this.transaction.workloadBootstrap.findUnique({ where: { runId_attempt_generation: { runId: discovered.runId, attempt: discovered.attempt, generation: discovered.generation } } });
		const run = await this.transaction.agentRun.findUnique({ where: { id: discovered.runId }, include: { inputSnapshot: true } });
		if (reservation === null || assignment === null || bootstrap === null || run === null || run.inputSnapshot === null || !_RowsMatch(identity, run, reservation, assignment, bootstrap))
			throw new WarmRuntimeBindingConflict();
		const proofKey = await this.transaction.runProofKey.findUnique({ where: { runId_attempt_generation: { runId: discovered.runId, attempt: discovered.attempt, generation: discovered.generation } } });
		const now = new Date();

		// 3. A replay succeeds only while every saved owner, proof, and expiry still matches.
		if (reservation.state === WarmRuntimeReservationState.Claimed)
		{
			if (!_IsExactReplay(identity, submission, reservation, assignment, bootstrap, proofKey, now))
				throw new WarmRuntimeBindingConflict();
			if (proofKey === null)
				throw new WarmRuntimeBindingConflict();
			return { outcome: "idempotent" as const, receiptId: bootstrap.receiptId, runId: run.id, attempt: run.attempt, siloId: run.siloId, modelRoute: run.inputSnapshot.modelRoute, budgetPolicy: run.inputSnapshot.budgetPolicy, credentialExpiresAt: _EarliestExpiry(reservation.idleDeadline, assignment.expiresAt, bootstrap.expiresAt, proofKey.expiresAt) };
		}
		if (reservation.proofKeyThumbprint !== null || reservation.boundAt !== null || assignment.state !== WorkloadAssignmentState.PendingPod || assignment.registeredAt !== null || bootstrap.consumedAt !== null || bootstrap.consumedByPodUid !== null || bootstrap.revokedAt !== null || bootstrap.receiptId !== null || proofKey !== null)
			throw new WarmRuntimeBindingConflict();
		if (reservation.idleDeadline.getTime() <= now.getTime() || assignment.expiresAt.getTime() <= now.getTime() || bootstrap.expiresAt.getTime() <= now.getTime())
			throw new WarmRuntimeBindingConflict();
		const receiptId = randomUUID();

		// 4. Spend the assignment and bootstrap before saving the proof generated by this Pod process.
		await _RequireFence(this.transaction.workloadAssignment.updateMany({
			where: { runId: reservation.runId, attempt: reservation.attempt, bindingGeneration: reservation.generation, agentServiceId: assignment.agentServiceId, agentRevisionId: assignment.agentRevisionId, siloId: reservation.siloId, subjectId: assignment.subjectId, audience: assignment.audience, serviceAccountName: identity.serviceAccountName, namespace: identity.namespace, workloadKind: WorkloadKind.Deployment, workloadUid: assignment.workloadUid, podUid: assignment.podUid, state: WorkloadAssignmentState.PendingPod, registeredAt: null, revokedAt: null, expiresAt: assignment.expiresAt },
			data: { state: WorkloadAssignmentState.Registered, registeredAt: now },
		}));
		await _RequireFence(this.transaction.workloadBootstrap.updateMany({
			where: { id: bootstrap.id, runId: reservation.runId, attempt: reservation.attempt, generation: reservation.generation, agentServiceId: assignment.agentServiceId, agentRevisionId: assignment.agentRevisionId, siloId: reservation.siloId, subjectId: assignment.subjectId, audience: assignment.audience, serviceAccountName: identity.serviceAccountName, namespace: identity.namespace, workloadKind: WorkloadKind.Deployment, workloadUid: assignment.workloadUid, consumedAt: null, consumedByPodUid: null, revokedAt: null, receiptId: null, expiresAt: bootstrap.expiresAt },
			data: { consumedAt: now, consumedByPodUid: identity.podUid, receiptId },
		}));
		await this.transaction.runProofKey.create({ data: { id: randomUUID(), bootstrapId: bootstrap.id, runId: reservation.runId, attempt: reservation.attempt, generation: reservation.generation, workloadKind: WorkloadKind.Deployment, workloadUid: assignment.workloadUid, podUid: reservation.podUid, publicKeyJwk: submission.proofPublicJwk as unknown as Prisma.InputJsonValue, keyThumbprint: submission.proofKeyThumbprint, expiresAt: bootstrap.expiresAt } });

		// 5. Change the reservation last; losing this compare-and-set rolls back every write above.
		await _RequireFence(this.transaction.warmRuntimeReservation.updateMany({
			where: { runId: reservation.runId, attempt: reservation.attempt, generation: reservation.generation, siloId: reservation.siloId, namespace: identity.namespace, podUid: identity.podUid, serviceAccountName: identity.serviceAccountName, state: WarmRuntimeReservationState.Ready, proofKeyThumbprint: null, boundAt: null, deleteRequestedAt: null, deletedAt: null, idleDeadline: reservation.idleDeadline },
			data: { state: WarmRuntimeReservationState.Claimed, proofKeyThumbprint: submission.proofKeyThumbprint, boundAt: now },
		}));
		return { outcome: "bound" as const, receiptId, runId: run.id, attempt: run.attempt, siloId: run.siloId, modelRoute: run.inputSnapshot.modelRoute, budgetPolicy: run.inputSnapshot.budgetPolicy, credentialExpiresAt: _EarliestExpiry(reservation.idleDeadline, assignment.expiresAt, bootstrap.expiresAt) };
	}
}

/** Require one typed fence touch or abort the serializable transaction. */
async function _RequireFence(result: Promise<{ readonly count: number }>): Promise<void>
{
	if ((await result).count !== 1)
		throw new WarmRuntimeBindingConflict();
}

/** Return the earliest persisted authority expiry that limits one model credential. */
function _EarliestExpiry(...expiries: Date[]): Date
{
	return new Date(Math.min(...expiries.map(function _Timestamp(expiry) { return expiry.getTime(); })));
}

/** Cross-check the reviewed Pod and run ownership across every binding row. */
function _RowsMatch(identity: WarmRuntimeBindingIdentity, run: AgentRun, reservation: WarmRuntimeReservation, assignment: WorkloadAssignment, bootstrap: WorkloadBootstrap): boolean
{
	const runtimeAudience = assignment.audience === AGENT_RUNTIME_PROJECTED_TOKEN_AUDIENCE || assignment.audience === MANAGED_AGENT_RUNTIME_PROJECTED_TOKEN_AUDIENCE;
	const runIdentity = run.id === reservation.runId && run.attempt === reservation.attempt && run.siloId === reservation.siloId && run.agentServiceId === assignment.agentServiceId && run.agentRevisionId === assignment.agentRevisionId && (run.state === AgentRunState.Assigned || run.state === AgentRunState.WaitingForInput);
	const assignmentIdentity = assignment.runId === reservation.runId && assignment.attempt === reservation.attempt && assignment.bindingGeneration === reservation.generation && assignment.siloId === reservation.siloId && assignment.namespace === identity.namespace && assignment.serviceAccountName === identity.serviceAccountName && assignment.workloadKind === WorkloadKind.Deployment && assignment.revokedAt === null;
	const bootstrapIdentity = bootstrap.runId === assignment.runId && bootstrap.attempt === assignment.attempt && bootstrap.generation === reservation.generation && bootstrap.agentServiceId === assignment.agentServiceId && bootstrap.agentRevisionId === assignment.agentRevisionId && bootstrap.siloId === assignment.siloId && bootstrap.subjectId === assignment.subjectId && bootstrap.audience === assignment.audience && bootstrap.namespace === identity.namespace && bootstrap.serviceAccountName === identity.serviceAccountName && bootstrap.workloadKind === WorkloadKind.Deployment && bootstrap.workloadUid === assignment.workloadUid && bootstrap.revokedAt === null;
	return runtimeAudience && runIdentity && assignmentIdentity && bootstrapIdentity && reservation.namespace === identity.namespace && reservation.podUid === identity.podUid && reservation.serviceAccountName === identity.serviceAccountName && reservation.deleteRequestedAt === null && reservation.deletedAt === null;
}

/** Accept replay only when every already-bound row names the same Pod and proof. */
function _IsExactReplay(identity: WarmRuntimeBindingIdentity, submission: WarmRuntimeBindingSubmission, reservation: WarmRuntimeReservation, assignment: WorkloadAssignment, bootstrap: WorkloadBootstrap, proofKey: RunProofKey | null, now: Date): bootstrap is WorkloadBootstrap & { readonly receiptId: string }
{
	return reservation.state === WarmRuntimeReservationState.Claimed && reservation.proofKeyThumbprint === submission.proofKeyThumbprint && reservation.boundAt !== null && reservation.idleDeadline.getTime() > now.getTime() && assignment.bindingGeneration === reservation.generation && assignment.state === WorkloadAssignmentState.Registered && assignment.registeredAt !== null && assignment.expiresAt.getTime() > now.getTime() && bootstrap.generation === reservation.generation && bootstrap.consumedAt !== null && bootstrap.consumedByPodUid === identity.podUid && bootstrap.revokedAt === null && bootstrap.receiptId !== null && bootstrap.expiresAt.getTime() > now.getTime() && proofKey !== null && proofKey.generation === reservation.generation && proofKey.bootstrapId === bootstrap.id && proofKey.runId === reservation.runId && proofKey.attempt === reservation.attempt && proofKey.workloadKind === WorkloadKind.Deployment && proofKey.workloadUid === assignment.workloadUid && proofKey.podUid === identity.podUid && proofKey.keyThumbprint === submission.proofKeyThumbprint && proofKey.expiresAt.getTime() > now.getTime() && proofKey.revokedAt === null;
}
