import { createHash, createPublicKey, type JsonWebKey } from "node:crypto";

import { WARM_RUNTIME_SERVICE_ACCOUNT_NAME } from "@opencrane/contracts";
import { Prisma, type PrismaClient } from "@prisma/client";
import type { Es256PublicJwk } from "@opencrane/models/authorization";

import type { WarmRuntimeBindingAuthority, WarmRuntimeBindingIdentity, WarmRuntimeBindingResult, WarmRuntimeBindingSubmission } from "./warm-runtime-binding.types";
import type { AgentRunWorkflowControllerAuthorityOptions } from "./agent-run-workflow-controller-authority.types";
import { PrismaWarmRuntimeBindingRepository, WarmRuntimeBindingConflict } from "./prisma-warm-runtime-binding-repository";
import { _BuildRunAttemptCredentialMintInputs } from "./run-attempt-credential-minting";

/** Retries database serialization conflicts while two requests race for one Pod. */
const _SERIALIZABLE_ATTEMPTS = 3;

/**
 * Commits a warm Pod's proof binding before minting its short-lived model key.
 *
 * The model key expires no later than the earliest saved binding deadline. The authority checks that
 * limit again after minting because issuer latency can consume the remaining lifetime; a key that
 * would outlive database authority is revoked before this method returns `conflict`.
 *
 * Called by: {@link __CreateWarmRuntimeBindingRouter}.
 * @implements WarmRuntimeBindingAuthority
 */
export class PrismaWarmRuntimeBindingUnitOfWork implements WarmRuntimeBindingAuthority
{
	/** Opens short transactions against product authority. */
	private readonly prisma: PrismaClient;
	/** Mints the raw attempt key only after proof binding commits. */
	private readonly options: Pick<AgentRunWorkflowControllerAuthorityOptions, "assignmentTtlMilliseconds" | "issueAttemptModelKey">;

	/** Create the binding authority over the main database. */
	constructor(prisma: PrismaClient, options: Pick<AgentRunWorkflowControllerAuthorityOptions, "assignmentTtlMilliseconds" | "issueAttemptModelKey">)
	{
		this.prisma = prisma;
		this.options = options;
	}

	/**
	 * Bind the reviewed Pod and mint a model key only after the database transaction commits.
	 *
	 * @param identity - Pod identity returned by Kubernetes TokenReview.
	 * @param submission - Public proof key generated by that Pod process.
	 * @returns `bound` or `idempotent` with a model key, or `conflict` without a usable key.
	 * @throws Error When persistence or the key issuer fails unexpectedly, or serialization retries run out.
	 * @see WarmRuntimeBindingPersistenceRepository.bind
	 */
	async bind(identity: WarmRuntimeBindingIdentity, submission: WarmRuntimeBindingSubmission): Promise<WarmRuntimeBindingResult>
	{
		// 1. Reject malformed identity or proof data before opening a transaction.
		if (!_IdentityIsValid(identity) || !_SubmissionIsValid(submission))
			return { outcome: "conflict" };
		let conflict: Prisma.PrismaClientKnownRequestError | null = null;
		for (let attempt = 1; attempt <= _SERIALIZABLE_ATTEMPTS; attempt += 1)
		{
			try
			{
				// 2. Commit Pod ownership and proof before any raw model credential exists.
				const bound = await this.prisma.$transaction(async function _Bind(transaction)
				{
					const repository = new PrismaWarmRuntimeBindingRepository(transaction);
					return await repository.bind(identity, submission);
				}, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
				if (!("modelRoute" in bound))
					return bound;

				// 3. Cap the requested key lifetime at the earliest deadline saved by the transaction.
				const remainingCredentialLifetime = Math.min(this.options.assignmentTtlMilliseconds, bound.credentialExpiresAt.getTime() - Date.now());
				if (remainingCredentialLifetime < 1_000)
					return { outcome: "conflict" };
				const credentials = _BuildRunAttemptCredentialMintInputs({ modelRoute: bound.modelRoute, budgetPolicy: bound.budgetPolicy, runId: bound.runId, attempt: bound.attempt, siloId: bound.siloId, assignmentTtlMilliseconds: remainingCredentialLifetime });
				if (credentials === null)
					return { outcome: "conflict" };

				// 4. Mint only after commit so a failed database transaction never creates a usable key.
				const minted = await this.options.issueAttemptModelKey({ ...credentials, siloId: bound.siloId });
				if (typeof minted.key !== "string" || minted.key.length === 0)
					return { outcome: "conflict" };

				// 5. Revoke a late key when issuer delay would let it outlive the saved binding deadline.
				if (Date.now() + credentials.expirySeconds * 1_000 > bound.credentialExpiresAt.getTime())
				{
					await this.options.issueAttemptModelKey.revokeAttemptKey({ keyAlias: credentials.keyAlias, key: minted.key });
					return { outcome: "conflict" };
				}
				return { outcome: bound.outcome, receiptId: bound.receiptId, attemptModelKey: minted.key };
			}
			catch (error)
			{
				if (error instanceof WarmRuntimeBindingConflict)
					return { outcome: "conflict" };
				if (!(error instanceof Prisma.PrismaClientKnownRequestError) || (error.code !== "P2002" && error.code !== "P2034"))
					throw error;
				conflict = error;
			}
		}
		throw new Error("warm runtime binding conflicted after three attempts", { cause: conflict ?? undefined });
	}
}

/** Validate the reviewed identity before it selects a database row. */
function _IdentityIsValid(identity: WarmRuntimeBindingIdentity): boolean
{
	return identity.serviceAccountName === WARM_RUNTIME_SERVICE_ACCOUNT_NAME && identity.namespace.trim().length > 0 && identity.podUid.trim().length > 0;
}

/** Re-derive the submitted public-key thumbprint before any database mutation. */
function _SubmissionIsValid(submission: WarmRuntimeBindingSubmission): boolean
{
	try
	{
		return submission.proofKeyThumbprint.length <= 128 && _ComputeProofKeyThumbprint(submission.proofPublicJwk) === submission.proofKeyThumbprint;
	}
	catch
	{
		return false;
	}
}

/** Compute an RFC 7638 thumbprint only for an importable public P-256 key. */
function _ComputeProofKeyThumbprint(jwk: Es256PublicJwk): string
{
	const candidate = jwk as Es256PublicJwk & { readonly d?: unknown };
	if (candidate.kty !== "EC" || candidate.crv !== "P-256" || Object.hasOwn(candidate, "d") || !_IsP256Coordinate(candidate.x) || !_IsP256Coordinate(candidate.y))
		throw new TypeError("warm runtime proof key must be a public P-256 JWK");
	createPublicKey({ key: candidate as JsonWebKey, format: "jwk" });
	const canonical = JSON.stringify({ crv: candidate.crv, kty: candidate.kty, x: candidate.x, y: candidate.y });
	return createHash("sha256").update(canonical, "utf8").digest("base64url");
}

/** Accept one canonical unpadded base64url P-256 coordinate. */
function _IsP256Coordinate(value: unknown): value is string
{
	if (typeof value !== "string" || !/^[A-Za-z0-9_-]+$/u.test(value) || value.length % 4 === 1)
		return false;
	const decoded = Buffer.from(value, "base64url");
	return decoded.length === 32 && decoded.toString("base64url") === value;
}
