import { randomUUID } from "node:crypto";

import { AGENT_RUNTIME_PROJECTED_TOKEN_AUDIENCE, MANAGED_AGENT_RUNTIME_PROJECTED_TOKEN_AUDIENCE, RunInputSnapshotIdentityKinds } from "@opencrane/contracts";
import { AgentRunState, ModelRoutingScope, WarmRuntimeReservationState, WorkloadAssignmentState, WorkloadKind, Prisma, type AgentRun, type RunModelCredentialMintAuthorization, type RunProofKey, type WarmRuntimeReservation, type WorkloadAssignment, type WorkloadBootstrap } from "@prisma/client";

import { __DigestCanonicalJson, type AuthorizationAuthority } from "@opencrane/backend/server/iam/authorization";
import { AuthorizationDecisionOutcomes, ProductAuthorizationActions, ProductAuthorizationResourceKinds } from "@opencrane/models/authorization";

import { __BuildRunAttemptKeyAlias } from "./run-attempt-credential-minting";
import type { RunModelCredentialMintAuthorizationClaimRepository, WarmRuntimeBindingIdentity, WarmRuntimeBindingPersistenceRepository, WarmRuntimeBindingSubmission, WarmRuntimeDatabaseBindingResult } from "./warm-runtime-binding.types";

/**
 * Aborts a binding transaction after an ownership check or compare-and-set no longer matches.
 *
 * Throwing, instead of returning `conflict`, makes Prisma roll back assignment, bootstrap, proof,
 * and reservation writes already made in the transaction. The unit of work catches this error and
 * returns the public `conflict` outcome.
 *
 * Called by: {@link PrismaWarmRuntimeBindingRepository.bind} and
 * {@link PrismaWarmRuntimeBindingUnitOfWork.bind}.
 */
export class WarmRuntimeBindingConflict extends Error {}

/**
 * Checks and spends the rows that bind a reviewed warm Pod to one AgentRun attempt.
 *
 * The caller owns the serializable transaction. This repository returns database evidence for
 * later credential minting but never mints a credential itself.
 *
 * Called by: {@link PrismaWarmRuntimeBindingUnitOfWork.bind}.
 * @implements WarmRuntimeBindingPersistenceRepository
 */
export class PrismaWarmRuntimeBindingRepository implements WarmRuntimeBindingPersistenceRepository
{
	/** Transaction that owns every typed fence and semantic write. */
	private readonly transaction: Prisma.TransactionClient;
	/** Central authority sharing the binding transaction. */
	private readonly authorization: AuthorizationAuthority;

	/** Bind this repository to the unit of work's transaction. */
	constructor(transaction: Prisma.TransactionClient, authorization: AuthorizationAuthority)
	{
		this.transaction = transaction;
		this.authorization = authorization;
	}

	/**
	 * Bind a Ready reservation or return the still-valid Claimed replay.
	 *
	 * It follows the lock and write order required by {@link WarmRuntimeBindingPersistenceRepository}.
	 *
	 * @param identity - Pod identity already reviewed by Kubernetes TokenReview.
	 * @param submission - Public proof generated by that Pod process.
	 * @returns The binding result and the earliest saved credential expiry.
	 * @throws WarmRuntimeBindingConflict When linked ownership, state, expiry, or a compare-and-set changes.
	 */
	async bind(identity: WarmRuntimeBindingIdentity, submission: WarmRuntimeBindingSubmission): Promise<WarmRuntimeDatabaseBindingResult>
	{
		// 1. Find a Ready or Claimed reservation without changing it, so missing work is a clean conflict.
		const discovered = await this.transaction.warmRuntimeReservation.findUnique({ where: { namespace_podUid: { namespace: identity.namespace, podUid: identity.podUid } } });
		if (discovered === null)
			return { outcome: "conflict" };
		if (discovered.state !== WarmRuntimeReservationState.Ready && discovered.state !== WarmRuntimeReservationState.Claimed)
			return { outcome: "conflict" };
		const replay = discovered.state === WarmRuntimeReservationState.Claimed;
		const expectedProof = replay ? submission.proofKeyThumbprint : null;
		const expectedBoundAt = replay ? { not: null } : null;

		// 2. Check the AgentRun before the reservation owner so every binding transaction uses this order.
		await _RequireFence(this.transaction.agentRun.updateMany({ where: { id: discovered.runId, attempt: discovered.attempt, state: { in: [AgentRunState.Assigned, AgentRunState.WaitingForInput] } }, data: { state: discovered.generation === 1 ? AgentRunState.Assigned : AgentRunState.WaitingForInput } }));
		await _RequireFence(this.transaction.warmRuntimeReservation.updateMany({
			where: { runId: discovered.runId, attempt: discovered.attempt, generation: discovered.generation, siloId: discovered.siloId, namespace: identity.namespace, podUid: identity.podUid, serviceAccountName: identity.serviceAccountName, state: discovered.state, proofKeyThumbprint: expectedProof, boundAt: expectedBoundAt, deleteRequestedAt: null, deletedAt: null },
			data: { state: discovered.state },
		}));
		const reservation = await this.transaction.warmRuntimeReservation.findUnique({ where: { runId_attempt_generation: { runId: discovered.runId, attempt: discovered.attempt, generation: discovered.generation } } });
		const assignment = await this.transaction.workloadAssignment.findUnique({ where: { runId_attempt: { runId: discovered.runId, attempt: discovered.attempt } } });
		const bootstrap = await this.transaction.workloadBootstrap.findUnique({ where: { runId_attempt_generation: { runId: discovered.runId, attempt: discovered.attempt, generation: discovered.generation } } });
		const run = await this.transaction.agentRun.findUnique({ where: { id: discovered.runId }, include: { inputSnapshot: true } });
		if (reservation === null || assignment === null || bootstrap === null || run === null || run.inputSnapshot === null || !_RowsMatch(identity, run, reservation, assignment, bootstrap))
			throw new WarmRuntimeBindingConflict();
		const proofKey = await this.transaction.runProofKey.findUnique({ where: { runId_attempt_generation: { runId: discovered.runId, attempt: discovered.attempt, generation: discovered.generation } } });
		const now = new Date();
		const modelAuthorization = await this._AuthorizeCurrentModelCredential(run, reservation, now);
		if (modelAuthorization === null)
			throw new WarmRuntimeBindingConflict();

		// 3. A replay succeeds only while every saved owner, proof, and expiry still matches.
		if (reservation.state === WarmRuntimeReservationState.Claimed)
		{
			if (!_IsExactReplay(identity, submission, reservation, assignment, bootstrap, proofKey, now))
				throw new WarmRuntimeBindingConflict();
			if (proofKey === null)
				throw new WarmRuntimeBindingConflict();
			const mintAuthorization = await this.transaction.runModelCredentialMintAuthorization.findUnique({ where: { runId_attempt_generation: { runId: run.id, attempt: run.attempt, generation: reservation.generation } } });
			if (mintAuthorization === null || !_MintAuthorizationMatches(mintAuthorization, modelAuthorization, run.id, run.attempt, reservation.generation, run.siloId))
				throw new WarmRuntimeBindingConflict();
			return { outcome: "idempotent" as const, receiptId: bootstrap.receiptId, runId: run.id, attempt: run.attempt, siloId: run.siloId, modelRoute: run.inputSnapshot.modelRoute, budgetPolicy: run.inputSnapshot.budgetPolicy, credentialExpiresAt: mintAuthorization.expiresAt, mintAuthorizationId: mintAuthorization.id };
		}
		if (reservation.proofKeyThumbprint !== null || reservation.boundAt !== null || assignment.state !== WorkloadAssignmentState.PendingPod || assignment.registeredAt !== null || bootstrap.consumedAt !== null || bootstrap.consumedByPodUid !== null || bootstrap.revokedAt !== null || bootstrap.receiptId !== null || proofKey !== null)
			throw new WarmRuntimeBindingConflict();
		if (reservation.idleDeadline.getTime() <= now.getTime() || assignment.expiresAt.getTime() <= now.getTime() || bootstrap.expiresAt.getTime() <= now.getTime())
			throw new WarmRuntimeBindingConflict();
		const receiptId = randomUUID();

		// 4. Spend the assignment and bootstrap before saving the proof generated by this Pod process.
		await _RequireFence(this.transaction.workloadAssignment.updateMany({
			where: { runId: reservation.runId, attempt: reservation.attempt, bindingGeneration: reservation.generation, agentServiceId: assignment.agentServiceId, agentRevisionId: assignment.agentRevisionId, siloId: reservation.siloId, subjectId: assignment.subjectId, audience: assignment.audience, serviceAccountName: identity.serviceAccountName, namespace: identity.namespace, workloadKind: WorkloadKind.Deployment, workloadUid: assignment.workloadUid, podUid: assignment.podUid, state: WorkloadAssignmentState.PendingPod, registeredAt: null, revokedAt: null, expiresAt: assignment.expiresAt },
			data: { state: WorkloadAssignmentState.Registered, registeredAt: now },
		}));
		await _RequireFence(this.transaction.workloadBootstrap.updateMany({
			where: { id: bootstrap.id, runId: reservation.runId, attempt: reservation.attempt, generation: reservation.generation, agentServiceId: assignment.agentServiceId, agentRevisionId: assignment.agentRevisionId, siloId: reservation.siloId, subjectId: assignment.subjectId, audience: assignment.audience, serviceAccountName: identity.serviceAccountName, namespace: identity.namespace, workloadKind: WorkloadKind.Deployment, workloadUid: assignment.workloadUid, consumedAt: null, consumedByPodUid: null, revokedAt: null, receiptId: null, expiresAt: bootstrap.expiresAt },
			data: { consumedAt: now, consumedByPodUid: identity.podUid, receiptId },
		}));
		await this.transaction.runProofKey.create({ data: { id: randomUUID(), bootstrapId: bootstrap.id, runId: reservation.runId, attempt: reservation.attempt, generation: reservation.generation, workloadKind: WorkloadKind.Deployment, workloadUid: assignment.workloadUid, podUid: reservation.podUid, publicKeyJwk: submission.proofPublicJwk as unknown as Prisma.InputJsonValue, keyThumbprint: submission.proofKeyThumbprint, expiresAt: bootstrap.expiresAt } });
		const credentialExpiresAt = _EarliestExpiry(reservation.idleDeadline, assignment.expiresAt, bootstrap.expiresAt, modelAuthorization.membershipTrustedUntil);
		const mintAuthorization = await this.transaction.runModelCredentialMintAuthorization.create({
			data: {
				id: randomUUID(),
				runId: run.id,
				attempt: run.attempt,
				generation: reservation.generation,
				principalId: modelAuthorization.principalId,
				modelDefinitionId: modelAuthorization.modelDefinitionId,
				providerConnectionId: modelAuthorization.providerConnectionId,
				authorizationDigest: modelAuthorization.authorizationDigest,
				keyAlias: __BuildRunAttemptKeyAlias(run.id, run.attempt, run.siloId),
				expiresAt: credentialExpiresAt,
			},
		});

		// 5. Change the reservation last; losing this compare-and-set rolls back every write above.
		await _RequireFence(this.transaction.warmRuntimeReservation.updateMany({
			where: { runId: reservation.runId, attempt: reservation.attempt, generation: reservation.generation, siloId: reservation.siloId, namespace: identity.namespace, podUid: identity.podUid, serviceAccountName: identity.serviceAccountName, state: WarmRuntimeReservationState.Ready, proofKeyThumbprint: null, boundAt: null, deleteRequestedAt: null, deletedAt: null, idleDeadline: reservation.idleDeadline },
			data: { state: WarmRuntimeReservationState.Claimed, proofKeyThumbprint: submission.proofKeyThumbprint, boundAt: now },
		}));
		return { outcome: "bound" as const, receiptId, runId: run.id, attempt: run.attempt, siloId: run.siloId, modelRoute: run.inputSnapshot.modelRoute, budgetPolicy: run.inputSnapshot.budgetPolicy, credentialExpiresAt, mintAuthorizationId: mintAuthorization.id };
	}

	/** Recheck the exact current model and provider grants before authorizing one post-commit mint. */
	private async _AuthorizeCurrentModelCredential(run: AgentRun & { readonly inputSnapshot: { readonly identitySnapshot: Prisma.JsonValue; readonly modelRoute: Prisma.JsonValue } | null }, reservation: WarmRuntimeReservation, now: Date): Promise<_ModelCredentialAuthorization | null>
	{
		if (run.inputSnapshot === null)
			return null;
		const actor = _SnapshotActor(run.inputSnapshot.identitySnapshot, now);
		const route = _SnapshotModelRoute(run.inputSnapshot.modelRoute);
		if (actor === null || route === null)
			return null;
		const model = await this.transaction.modelDefinition.findUnique({ where: { id: route.modelDefinitionId }, select: { id: true, scope: true, clusterTenant: true, publicModelName: true, litellmModelId: true, providerCredential: { select: { id: true, scope: true, clusterTenant: true } } } });
		if (model === null || !_ModelIsCurrentForSilo(model, route, run.siloId))
			return null;
		const argumentsValue = { runId: run.id, attempt: run.attempt, generation: reservation.generation, keyAlias: __BuildRunAttemptKeyAlias(run.id, run.attempt, run.siloId), modelDefinitionId: model.id, providerConnectionId: model.providerCredential?.id ?? null };
		const modelAdmission = await this.authorization.admitPrincipal({ siloId: run.siloId, principalId: actor.principalId, actorKind: actor.actorKind, actorId: actor.principalId, resource: { kind: ProductAuthorizationResourceKinds.ModelDefinition, id: model.id }, action: ProductAuthorizationActions.Use, argumentsDigest: __DigestCanonicalJson(argumentsValue), membershipRevision: actor.membershipRevision, nowEpochMs: now.getTime() });
		if (modelAdmission.outcome !== AuthorizationDecisionOutcomes.Allow || modelAdmission.evidence === null)
			return null;
		let providerDecisionDigest: string | null = null;
		if (model.providerCredential !== null)
		{
			const providerAdmission = await this.authorization.admitPrincipal({ siloId: run.siloId, principalId: actor.principalId, actorKind: actor.actorKind, actorId: actor.principalId, resource: { kind: ProductAuthorizationResourceKinds.ProviderConnection, id: model.providerCredential.id }, action: ProductAuthorizationActions.Use, argumentsDigest: __DigestCanonicalJson(argumentsValue), membershipRevision: actor.membershipRevision, nowEpochMs: now.getTime() });
			if (providerAdmission.outcome !== AuthorizationDecisionOutcomes.Allow || providerAdmission.evidence === null)
				return null;
			providerDecisionDigest = __DigestCanonicalJson({ effectiveAuthorizationDigest: providerAdmission.evidence.effectiveAuthorizationDigest, policyRevisionHash: providerAdmission.evidence.policyRevisionHash });
		}
		return {
			principalId: actor.principalId,
			modelDefinitionId: model.id,
			providerConnectionId: model.providerCredential?.id ?? null,
			authorizationDigest: __DigestCanonicalJson({ modelEffectiveAuthorizationDigest: modelAdmission.evidence.effectiveAuthorizationDigest, modelPolicyRevisionHash: modelAdmission.evidence.policyRevisionHash, providerEffectiveAuthorizationDigest: providerDecisionDigest }),
			membershipTrustedUntil: actor.membershipTrustedUntil,
		};
	}
}

/** Owns the second serializable transaction that spends one post-commit mint authorization. */
export class PrismaRunModelCredentialMintAuthorizationRepository implements RunModelCredentialMintAuthorizationClaimRepository
{
	/** Transaction that owns the one-use compare-and-set. */
	private readonly transaction: Prisma.TransactionClient;

	/** Bind the claim repository to its caller's transaction. */
	constructor(transaction: Prisma.TransactionClient)
	{
		this.transaction = transaction;
	}

	/** @inheritdoc */
	async claim(command: { readonly authorizationId: string; readonly runId: string; readonly attempt: number; readonly keyAlias: string; readonly claimedAt: Date }): Promise<boolean>
	{
		const result = await this.transaction.runModelCredentialMintAuthorization.updateMany({
			where: { id: command.authorizationId, runId: command.runId, attempt: command.attempt, keyAlias: command.keyAlias, claimedAt: null, expiresAt: { gt: command.claimedAt } },
			data: { claimedAt: command.claimedAt },
		});
		return result.count === 1;
	}
}

/** Current model and provider decision evidence saved before one external key mint. */
interface _ModelCredentialAuthorization
{
	readonly principalId: string;
	readonly modelDefinitionId: string;
	readonly providerConnectionId: string | null;
	readonly authorizationDigest: string;
	readonly membershipTrustedUntil: Date;
}

/** Validate and normalize the frozen execution actor whose current grants authorize the mint. */
function _SnapshotActor(value: Prisma.JsonValue, now: Date): { readonly principalId: string; readonly actorKind: "user" | "agent-service"; readonly membershipRevision: number; readonly membershipTrustedUntil: Date } | null
{
	if (value === null || typeof value !== "object" || Array.isArray(value))
		return null;
	const identity = value as Record<string, unknown>;
	const kind = identity["kind"];
	const principalId = kind === RunInputSnapshotIdentityKinds.User ? identity["principalId"] : identity["executionSubjectId"];
	const membershipRevision = identity["fleetMembershipRevision"];
	const trustedUntilValue = identity["fleetMembershipTrustedUntil"];
	if ((kind !== RunInputSnapshotIdentityKinds.User && kind !== RunInputSnapshotIdentityKinds.Service) || typeof principalId !== "string" || principalId.trim().length === 0 || !Number.isSafeInteger(membershipRevision) || typeof trustedUntilValue !== "string")
		return null;
	const membershipTrustedUntil = new Date(trustedUntilValue);
	if (!Number.isFinite(membershipTrustedUntil.getTime()) || membershipTrustedUntil.getTime() <= now.getTime())
		return null;
	return { principalId, actorKind: kind === RunInputSnapshotIdentityKinds.User ? "user" : "agent-service", membershipRevision: membershipRevision as number, membershipTrustedUntil };
}

/** Parse the exact model coordinates frozen by run admission. */
function _SnapshotModelRoute(value: Prisma.JsonValue): { readonly modelDefinitionId: string; readonly alias: string; readonly litellmModelId: string } | null
{
	if (value === null || typeof value !== "object" || Array.isArray(value))
		return null;
	const route = value as Record<string, unknown>;
	if (typeof route["modelDefinitionId"] !== "string" || typeof route["alias"] !== "string" || typeof route["litellmModelId"] !== "string")
		return null;
	return { modelDefinitionId: route["modelDefinitionId"], alias: route["alias"], litellmModelId: route["litellmModelId"] };
}

/** Require the persisted definition and provider connection to remain available to this silo. */
function _ModelIsCurrentForSilo(model: { readonly scope: ModelRoutingScope; readonly clusterTenant: string | null; readonly publicModelName: string; readonly litellmModelId: string; readonly providerCredential: { readonly scope: ModelRoutingScope; readonly clusterTenant: string | null } | null }, route: { readonly alias: string; readonly litellmModelId: string }, siloId: string): boolean
{
	const modelAvailable = model.scope === ModelRoutingScope.Global ? model.clusterTenant === null : model.clusterTenant === siloId;
	const providerAvailable = model.providerCredential === null || (model.providerCredential.scope === ModelRoutingScope.Global ? model.providerCredential.clusterTenant === null : model.providerCredential.clusterTenant === siloId);
	return modelAvailable && providerAvailable && model.publicModelName === route.alias && model.litellmModelId === route.litellmModelId;
}

/** Ensure a replay references the same durable one-use authorization derived by the new check. */
function _MintAuthorizationMatches(saved: RunModelCredentialMintAuthorization, current: _ModelCredentialAuthorization, runId: string, attempt: number, generation: number, siloId: string): boolean
{
	return saved.runId === runId && saved.attempt === attempt && saved.generation === generation && saved.principalId === current.principalId && saved.modelDefinitionId === current.modelDefinitionId && saved.providerConnectionId === current.providerConnectionId && saved.authorizationDigest === current.authorizationDigest && saved.keyAlias === __BuildRunAttemptKeyAlias(runId, attempt, siloId) && saved.expiresAt.getTime() <= current.membershipTrustedUntil.getTime();
}

/** Require one typed fence touch or abort the serializable transaction. */
async function _RequireFence(result: Promise<{ readonly count: number }>): Promise<void>
{
	if ((await result).count !== 1)
		throw new WarmRuntimeBindingConflict();
}

/** Return the earliest persisted authority expiry that limits one model credential. */
function _EarliestExpiry(...expiries: Date[]): Date
{
	return new Date(Math.min(...expiries.map(function _Timestamp(expiry) { return expiry.getTime(); })));
}

/** Cross-check the reviewed Pod and run ownership across every binding row. */
function _RowsMatch(identity: WarmRuntimeBindingIdentity, run: AgentRun, reservation: WarmRuntimeReservation, assignment: WorkloadAssignment, bootstrap: WorkloadBootstrap): boolean
{
	const runtimeAudience = assignment.audience === AGENT_RUNTIME_PROJECTED_TOKEN_AUDIENCE || assignment.audience === MANAGED_AGENT_RUNTIME_PROJECTED_TOKEN_AUDIENCE;
	const runIdentity = run.id === reservation.runId && run.attempt === reservation.attempt && run.siloId === reservation.siloId && run.agentServiceId === assignment.agentServiceId && run.agentRevisionId === assignment.agentRevisionId && (run.state === AgentRunState.Assigned || run.state === AgentRunState.WaitingForInput);
	const assignmentIdentity = assignment.runId === reservation.runId && assignment.attempt === reservation.attempt && assignment.bindingGeneration === reservation.generation && assignment.siloId === reservation.siloId && assignment.namespace === identity.namespace && assignment.serviceAccountName === identity.serviceAccountName && assignment.workloadKind === WorkloadKind.Deployment && assignment.revokedAt === null;
	const bootstrapIdentity = bootstrap.runId === assignment.runId && bootstrap.attempt === assignment.attempt && bootstrap.generation === reservation.generation && bootstrap.agentServiceId === assignment.agentServiceId && bootstrap.agentRevisionId === assignment.agentRevisionId && bootstrap.siloId === assignment.siloId && bootstrap.subjectId === assignment.subjectId && bootstrap.audience === assignment.audience && bootstrap.namespace === identity.namespace && bootstrap.serviceAccountName === identity.serviceAccountName && bootstrap.workloadKind === WorkloadKind.Deployment && bootstrap.workloadUid === assignment.workloadUid && bootstrap.revokedAt === null;
	return runtimeAudience && runIdentity && assignmentIdentity && bootstrapIdentity && reservation.namespace === identity.namespace && reservation.podUid === identity.podUid && reservation.serviceAccountName === identity.serviceAccountName && reservation.deleteRequestedAt === null && reservation.deletedAt === null;
}

/** Accept replay only when every already-bound row names the same Pod and proof. */
function _IsExactReplay(identity: WarmRuntimeBindingIdentity, submission: WarmRuntimeBindingSubmission, reservation: WarmRuntimeReservation, assignment: WorkloadAssignment, bootstrap: WorkloadBootstrap, proofKey: RunProofKey | null, now: Date): bootstrap is WorkloadBootstrap & { readonly receiptId: string }
{
	return reservation.state === WarmRuntimeReservationState.Claimed && reservation.proofKeyThumbprint === submission.proofKeyThumbprint && reservation.boundAt !== null && reservation.idleDeadline.getTime() > now.getTime() && assignment.bindingGeneration === reservation.generation && assignment.state === WorkloadAssignmentState.Registered && assignment.registeredAt !== null && assignment.expiresAt.getTime() > now.getTime() && bootstrap.generation === reservation.generation && bootstrap.consumedAt !== null && bootstrap.consumedByPodUid === identity.podUid && bootstrap.revokedAt === null && bootstrap.receiptId !== null && bootstrap.expiresAt.getTime() > now.getTime() && proofKey !== null && proofKey.generation === reservation.generation && proofKey.bootstrapId === bootstrap.id && proofKey.runId === reservation.runId && proofKey.attempt === reservation.attempt && proofKey.workloadKind === WorkloadKind.Deployment && proofKey.workloadUid === assignment.workloadUid && proofKey.podUid === identity.podUid && proofKey.keyThumbprint === submission.proofKeyThumbprint && proofKey.expiresAt.getTime() > now.getTime() && proofKey.revokedAt === null;
}
