import type { Es256PublicJwk } from "@opencrane/models/authorization";

/** Kubernetes-reviewed identity presented by one warm runtime Pod. */
export interface WarmRuntimeBindingIdentity
{
	/** Full ServiceAccount subject returned by TokenReview. */
	readonly subject: string;
	/** Namespace containing the reviewed Pod. */
	readonly namespace: string;
	/** Fixed warm runtime ServiceAccount name. */
	readonly serviceAccountName: string;
	/** Pod UID bound into the reviewed token. */
	readonly podUid: string;
}

/** Public evidence a warm Pod submits for its one-use claim. */
export interface WarmRuntimeBindingSubmission
{
	/** Public P-256 key generated by this runtime process. */
	readonly proofPublicJwk: Es256PublicJwk;
	/** RFC 7638 thumbprint the server re-derives before binding. */
	readonly proofKeyThumbprint: string;
}

/** Successful first binding or exact replay of the same proof key. */
export type WarmRuntimeBindingResult =
	| { readonly outcome: "bound" | "idempotent"; readonly receiptId: string; readonly attemptModelKey: string }
	| { readonly outcome: "conflict" };

/** Owns the database transaction that spends one warm reservation. */
export interface WarmRuntimeBindingAuthority
{
	/** Bind the reviewed Pod to the first valid proof key, or accept the exact replay. */
	bind(identity: WarmRuntimeBindingIdentity, submission: WarmRuntimeBindingSubmission): Promise<WarmRuntimeBindingResult>;
}

/** Reviews a token only for the dedicated warm runtime audience. */
export interface WarmRuntimeBindingTokenReviewer
{
	/** Return the Kubernetes-reviewed Pod identity, or null for every authentication denial. */
	__Review(token: string): Promise<WarmRuntimeBindingIdentity | null>;
}

/** Logs an unavailable warm binding authority without recording request secrets. */
export interface WarmRuntimeBindingLogger
{
	/** Record one internal failure. */
	error(bindings: { readonly err: unknown; readonly operation: string }, message: string): void;
}

/** Dependencies of the workload-authenticated warm binding route. */
export interface WarmRuntimeBindingRouterDependencies
{
	/** Reviews the projected warm token. */
	readonly tokenReviewer: WarmRuntimeBindingTokenReviewer;
	/** Spends the matching database reservation. */
	readonly authority: WarmRuntimeBindingAuthority;
	/** Records only unexpected server failures. */
	readonly logger: WarmRuntimeBindingLogger;
}
