import type { Es256PublicJwk } from "@opencrane/models/authorization";

/** Kubernetes-reviewed identity presented by one warm runtime Pod. */
export interface WarmRuntimeBindingIdentity
{
	/** Full ServiceAccount subject returned by TokenReview. */
	readonly subject: string;
	/** Namespace containing the reviewed Pod. */
	readonly namespace: string;
	/** Fixed warm runtime ServiceAccount name. */
	readonly serviceAccountName: string;
	/** Pod UID bound into the reviewed token. */
	readonly podUid: string;
}

/** Public evidence a warm Pod submits for its one-use claim. */
export interface WarmRuntimeBindingSubmission
{
	/** Public P-256 key generated by this runtime process. */
	readonly proofPublicJwk: Es256PublicJwk;
	/** RFC 7638 thumbprint the server re-derives before binding. */
	readonly proofKeyThumbprint: string;
}

/** Successful first binding or exact replay of the same proof key. */
export type WarmRuntimeBindingResult =
	| { readonly outcome: "bound" | "idempotent"; readonly receiptId: string; readonly attemptModelKey: string }
	| { readonly outcome: "unreserved" }
	| { readonly outcome: "conflict" };

/**
 * Carries a successful database binding to the unit of work that mints the model key after commit.
 *
 * `bound` means this transaction spent the reservation; `idempotent` means the same Pod and proof
 * were already bound and remain valid. Both carry the earliest saved expiry so the model key cannot
 * outlive the reservation, assignment, bootstrap, or proof. `conflict` is a refusal found before
 * writes start; {@link WarmRuntimeBindingConflict} aborts the transaction if a later fence loses.
 *
 * Called by: {@link PrismaWarmRuntimeBindingUnitOfWork.bind}.
 */
export type WarmRuntimeDatabaseBindingResult =
	| { readonly outcome: "unreserved" }
	| { readonly outcome: "conflict" }
	| { readonly outcome: "bound" | "idempotent"; readonly receiptId: string; readonly runId: string; readonly attempt: number; readonly siloId: string; readonly modelRoute: unknown; readonly budgetPolicy: unknown; readonly credentialExpiresAt: Date; readonly mintAuthorizationId: string };

/**
 * Spends a warm reservation inside a serializable database transaction opened by its caller.
 *
 * Implementations must check the AgentRun before the reservation owner, then change the assignment
 * and bootstrap before changing the reservation. The reservation update is last so losing it throws
 * and rolls back every earlier write. This port never mints or returns a model key.
 *
 * Called by: {@link PrismaWarmRuntimeBindingUnitOfWork.bind}.
 */
export interface WarmRuntimeBindingPersistenceRepository
{
	/**
	 * Bind the reviewed Pod or return its still-valid replay.
	 *
	 * @param identity - Pod identity returned by Kubernetes TokenReview.
	 * @param submission - Public proof key and thumbprint supplied by that Pod.
	 * @returns `bound`, `idempotent`, `unreserved`, or a pre-write `conflict` with the expiry that limits later credentials.
	 * @throws WarmRuntimeBindingConflict When ownership, state, expiry, or a compare-and-set changes after checks begin.
	 */
	bind(identity: WarmRuntimeBindingIdentity, submission: WarmRuntimeBindingSubmission): Promise<WarmRuntimeDatabaseBindingResult>;
}

/** Spends one durable post-commit model-key mint authorization. */
export interface RunModelCredentialMintAuthorizationClaimRepository
{
	/** Atomically spend the exact authorization once. */
	claim(command: { readonly authorizationId: string; readonly runId: string; readonly attempt: number; readonly keyAlias: string; readonly claimedAt: Date }): Promise<boolean>;
}

/** Owns the database transaction that spends one warm reservation. */
export interface WarmRuntimeBindingAuthority
{
	/** Bind the reviewed Pod to the first valid proof key, or accept the exact replay. */
	bind(identity: WarmRuntimeBindingIdentity, submission: WarmRuntimeBindingSubmission): Promise<WarmRuntimeBindingResult>;
}

/** Reviews a token only for the dedicated warm runtime audience. */
export interface WarmRuntimeBindingTokenReviewer
{
	/** Return the Kubernetes-reviewed Pod identity, or null for every authentication denial. */
	__Review(token: string): Promise<WarmRuntimeBindingIdentity | null>;
}

/** Logs an unavailable warm binding authority without recording request secrets. */
export interface WarmRuntimeBindingLogger
{
	/** Record one internal failure. */
	error(bindings: { readonly err: unknown; readonly operation: string }, message: string): void;
}

/** Dependencies of the workload-authenticated warm binding route. */
export interface WarmRuntimeBindingRouterDependencies
{
	/** Reviews the projected warm token. */
	readonly tokenReviewer: WarmRuntimeBindingTokenReviewer;
	/** Spends the matching database reservation. */
	readonly authority: WarmRuntimeBindingAuthority;
	/** Records only unexpected server failures. */
	readonly logger: WarmRuntimeBindingLogger;
}
