import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ConversationModelPreForwardContracts, ConversationModelResponseKinds } from "@opencrane/contracts";

import { __CreateConversationModelTransport } from "../retry/conversation-model-transport";
import { __RequestConversationModel } from "../core/conversation-model";
import { ConversationModelFailureCodes } from "../core/conversation-model.types";
import { _RETRY_ENDPOINT, _RETRY_NOW, _RetryAuthentication, _RetryEnvironment, _RetryReceipt, _RetryRequest, _RetryResponse } from "./conversation-model-retry.fixture";

const _telemetry = vi.hoisted(function _telemetryFixture() { return { fields: [] as unknown[], errors: [] as unknown[], failed: 0 }; });

vi.mock("@opencrane/backend/observability", function _observability()
{
	return {
		async ___DoWithTrace(_name: string, fields: unknown, work: () => Promise<unknown>)
		{
			_telemetry.fields.push(fields);
			try { return await work(); }
			catch (error) { _telemetry.errors.push(error); throw error; }
		},
		___DoWithoutTrace(work: () => unknown) { return work(); },
		___MarkActiveSpanFailed() { _telemetry.failed++; },
	};
});

beforeEach(function _setup()
{
	vi.useFakeTimers(); vi.setSystemTime(_RETRY_NOW);
	_telemetry.fields.length = 0; _telemetry.errors.length = 0; _telemetry.failed = 0;
});

afterEach(function _cleanup() { vi.unstubAllGlobals(); vi.restoreAllMocks(); vi.useRealTimers(); });

describe("qualified pre-provider rejection transport", function _suite()
{
	it("verifies the wire vector emitted by the production Python receipt encoder", async function _pythonWireVector()
	{
		// Generated by proxy.context.capture_request and signed_receipt with this synthetic input.
		const authentication = "c138fdf9747e52aaa5a8615d778e4b4d8d0682c919a714b69c1a75c694032606";
		const fetchMock = vi.fn(function _proxy(_url: URL, init: RequestInit)
		{
			const receipt = _RetryReceipt(init);
			expect(receipt.requestBodySha256).toBe("3c9621d38c00912c8e0ddc586511f0e2c903bdab339ef8c92ef79b21ea304143");
			return Promise.resolve(new Response(JSON.stringify({ receipt }), { status: 429, headers: { "content-type": "application/json", "x-opencrane-preforward-receipt": authentication } }));
		});
		vi.stubGlobal("fetch", fetchMock);
		await expect(__CreateConversationModelTransport(_RetryEnvironment()).request(_RetryRequest())).resolves.toMatchObject({ kind: ConversationModelResponseKinds.PreForwardRejected });
	});

	it("returns authenticated evidence after one send without waiting or retrying", async function _verifiedReceipt()
	{
		const fetchMock = vi.fn(function _proxy(_url: URL, init: RequestInit) { return Promise.resolve(_RetryResponse(init)); });
		vi.stubGlobal("fetch", fetchMock);
		const transport = __CreateConversationModelTransport(_RetryEnvironment());
		const result = await transport.request(_RetryRequest());
		expect(result).toMatchObject({ kind: ConversationModelResponseKinds.PreForwardRejected, receipt: { physicalNonce: "a".repeat(64), logicalFence: "b".repeat(64), deadlineEpochMs: _RETRY_NOW + 25_000, retryAtEpochMs: _RETRY_NOW + 1_000 } });
		expect(fetchMock).toHaveBeenCalledTimes(1);
		const init = fetchMock.mock.calls[0]![1];
		expect(new Headers(init.headers).get("x-opencrane-preforward-contract")).toBe(ConversationModelPreForwardContracts.V1);
		expect(String(init.body)).not.toContain("x-opencrane");
		expect(String(init.body)).not.toContain("sk-synthetic-attempt");
		expect(_telemetry).toEqual({ fields: [{}], errors: [], failed: 1 });
		await vi.advanceTimersByTimeAsync(30_000);
		expect(fetchMock).toHaveBeenCalledTimes(1);
		expect(vi.getTimerCount()).toBe(0);
	});

	it.each([
		{ physicalNonce: "c".repeat(64) }, { logicalFence: "c".repeat(64) }, { requestBodySha256: "c".repeat(64) },
		{ deadlineEpochMs: _RETRY_NOW + 25_001 }, { retryAtEpochMs: _RETRY_NOW }, { retryAtEpochMs: _RETRY_NOW + 25_000 },
		{ retryAtEpochMs: _RETRY_NOW + 0.5 }, { version: "unknown" as never }, { reason: "provider-rate-limit" as never },
	])("rejects even a correctly signed receipt with changed request fields %j", async function _changedReceipt(overrides)
	{
		const fetchMock = vi.fn(function _proxy(_url: URL, init: RequestInit) { return Promise.resolve(_RetryResponse(init, overrides)); });
		vi.stubGlobal("fetch", fetchMock);
		await expect(__CreateConversationModelTransport(_RetryEnvironment()).request(_RetryRequest())).rejects.toMatchObject({ code: ConversationModelFailureCodes.HttpRejected });
		expect(fetchMock).toHaveBeenCalledTimes(1);
	});

	it.each(["wrong-key", "missing", "duplicate", "upper-case", "extra-field", "provider-envelope", "wrong-mime", "redirected", "oversize", "oversize-stream", "invalid-unicode"])("rejects invalid proof transport: %s", async function _invalidProof(kind)
	{
		const fetchMock = vi.fn(function _proxy(_url: URL, init: RequestInit)
		{
			const receipt = _RetryReceipt(init);
			const headers = new Headers({ "content-type": "application/json", "x-opencrane-preforward-receipt": _RetryAuthentication(receipt) });
			if (kind === "wrong-key")
				headers.set("x-opencrane-preforward-receipt", _RetryAuthentication(receipt, "sk-other"));
			if (kind === "missing")
				headers.delete("x-opencrane-preforward-receipt");
			if (kind === "duplicate")
				headers.append("x-opencrane-preforward-receipt", _RetryAuthentication(receipt));
			if (kind === "upper-case")
				headers.set("x-opencrane-preforward-receipt", _RetryAuthentication(receipt).toUpperCase());
			if (kind === "wrong-mime")
				headers.set("content-type", "text/plain");
			if (kind === "oversize")
				headers.set("content-length", "2049");
			let body: BodyInit = JSON.stringify({ receipt });
			if (kind === "extra-field")
				body = JSON.stringify({ receipt, providerCost: 0 });
			if (kind === "provider-envelope")
				body = JSON.stringify({ error: { code: 429, message: "No provider cost" } });
			if (kind === "oversize-stream")
				body += " ".repeat(2049);
			if (kind === "invalid-unicode")
				body = new Uint8Array([0xff]);
			const response = new Response(body, { status: 429, headers });
			if (kind === "redirected")
				Object.defineProperty(response, "redirected", { value: true });
			return Promise.resolve(response);
		});
		vi.stubGlobal("fetch", fetchMock);
		await expect(__CreateConversationModelTransport(_RetryEnvironment()).request(_RetryRequest())).rejects.toThrow();
		expect(fetchMock).toHaveBeenCalledTimes(1);
		expect(JSON.stringify(_telemetry)).not.toContain("sk-synthetic-attempt");
		expect(JSON.stringify(_telemetry)).not.toContain("Private question");
	});

	it.each([{}, { LITELLM_ENDPOINT: _RETRY_ENDPOINT }, { LITELLM_PREFORWARD_CONTRACT: "", LITELLM_PREFORWARD_ENDPOINT: "" }])("does not infer qualification from signed responses: %j", async function _unqualified(environment)
	{
		const fetchMock = vi.fn(function _proxy(_url: URL, init: RequestInit) { return Promise.resolve(_RetryResponse(init)); });
		vi.stubGlobal("fetch", fetchMock);
		await expect(__CreateConversationModelTransport(environment).request(_RetryRequest())).rejects.toMatchObject({ code: ConversationModelFailureCodes.HttpRejected });
		expect(Object.keys(fetchMock.mock.calls[0]![1].headers!)).not.toContain("x-opencrane-preforward-contract");
		expect(fetchMock).toHaveBeenCalledTimes(1);
	});

	it("keeps the direct adapter unqualified and does not send unsaved coordinates", async function _legacyCaller()
	{
		const fetchMock = vi.fn(function _proxy(_url: URL, init: RequestInit) { return Promise.resolve(_RetryResponse(init)); });
		vi.stubGlobal("fetch", fetchMock);
		await expect(__RequestConversationModel(_RetryRequest())).rejects.toMatchObject({ code: ConversationModelFailureCodes.HttpRejected });
		await expect(__CreateConversationModelTransport(_RetryEnvironment()).request(_RetryRequest({ delivery: undefined }))).rejects.toMatchObject({ code: ConversationModelFailureCodes.HttpRejected });
		for (const call of fetchMock.mock.calls)
			expect(new Headers(call[1].headers).has("x-opencrane-request-nonce")).toBe(false);
	});

	it("does not send after retry input bytes change", async function _changedBody()
	{
		const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock);
		await expect(__CreateConversationModelTransport(_RetryEnvironment()).request(_RetryRequest({ delivery: { physicalNonce: "a".repeat(64), logicalFence: "b".repeat(64), expectedRequestBodySha256: "0".repeat(64) } }))).rejects.toMatchObject({ code: ConversationModelFailureCodes.InvalidRequest });
		expect(fetchMock).not.toHaveBeenCalled();
	});

	it("captures request coordinates before a caller can mutate them", async function _detachedInput()
	{
		const request = _RetryRequest();
		const fetchMock = vi.fn(function _proxy(_url: URL, init: RequestInit)
		{
			Object.assign(request.delivery!, { physicalNonce: "c".repeat(64) });
			return Promise.resolve(_RetryResponse(init));
		});
		vi.stubGlobal("fetch", fetchMock);
		await expect(__CreateConversationModelTransport(_RetryEnvironment()).request(request)).resolves.toMatchObject({ kind: ConversationModelResponseKinds.PreForwardRejected, receipt: { physicalNonce: "a".repeat(64) } });
	});

	it("accepts a reset that elapsed in transit but never an expired deadline", async function _slowReceipt()
	{
		let elapsed = 1_500;
		const fetchMock = vi.fn(function _proxy(_url: URL, init: RequestInit)
		{
			const response = _RetryResponse(init); vi.setSystemTime(_RETRY_NOW + elapsed); return Promise.resolve(response);
		});
		vi.stubGlobal("fetch", fetchMock);
		const transport = __CreateConversationModelTransport(_RetryEnvironment());
		await expect(transport.request(_RetryRequest())).resolves.toMatchObject({ kind: ConversationModelResponseKinds.PreForwardRejected });
		vi.setSystemTime(_RETRY_NOW); elapsed = 25_000;
		await expect(transport.request(_RetryRequest())).rejects.toMatchObject({ code: ConversationModelFailureCodes.DeadlineExceeded });
	});

	it("does not interpret a signed-looking 200 response as rejection evidence", async function _successIsNotProof()
	{
		const fetchMock = vi.fn(function _proxy(_url: URL, init: RequestInit)
		{
			const receipt = _RetryReceipt(init);
			return Promise.resolve(new Response(JSON.stringify({ receipt }), { headers: { "content-type": "application/json", "x-opencrane-preforward-receipt": _RetryAuthentication(receipt) } }));
		});
		vi.stubGlobal("fetch", fetchMock);
		await expect(__CreateConversationModelTransport(_RetryEnvironment()).request(_RetryRequest())).rejects.toMatchObject({ code: ConversationModelFailureCodes.UnsupportedResponse });
	});
});

describe("deployment-owned qualification", function _configuration()
{
	it.each([
		{ LITELLM_PREFORWARD_ENDPOINT: undefined }, { LITELLM_PREFORWARD_CONTRACT: undefined },
		{ LITELLM_PREFORWARD_CONTRACT: "true" }, { LITELLM_PREFORWARD_CONTRACT: "other-version" },
		{ LITELLM_ENDPOINT: "http://other-litellm:4000" }, { LITELLM_PREFORWARD_ENDPOINT: `${_RETRY_ENDPOINT}/path` },
		{ LITELLM_PREFORWARD_ENDPOINT: `${_RETRY_ENDPOINT}/?key=private` }, { LITELLM_PREFORWARD_ENDPOINT: `http://user:secret@testv6-opencrane-litellm:4000` },
		{ LITELLM_ENDPOINT: "https://shared.example", LITELLM_PREFORWARD_ENDPOINT: "https://shared.example" },
	])("fails closed for invalid configuration %j", function _invalidConfiguration(overrides)
	{
		expect(function _create() { __CreateConversationModelTransport({ ..._RetryEnvironment(), ...overrides }); }).toThrow("Model proxy qualification is invalid");
	});

	it("freezes qualification and refuses a request to a different origin", async function _frozenConfiguration()
	{
		const environment = _RetryEnvironment();
		const transport = __CreateConversationModelTransport(environment);
		environment["LITELLM_PREFORWARD_ENDPOINT"] = "http://other-litellm:4000";
		const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock);
		await expect(transport.request(_RetryRequest({ endpoint: "http://other-litellm:4000" }))).rejects.toMatchObject({ code: ConversationModelFailureCodes.InvalidRequest });
		expect(fetchMock).not.toHaveBeenCalled();
	});
});
