/** MCP operator access and explicit resource-sharing OpenAPI components. */
export const _McpIamOpenapiSchemas = {
	McpCatalogServer: {
		type: "object",
		description: "An MCP server exposed by the operator API. Fields other than id are optional because this shape serves both the entitled catalogue and the organisation-admin governance view.",
		required: ["id"],
		properties: {
			id: { type: "string", description: "Stable server identifier." },
			name: { type: "string", description: "Display name shown in the catalogue." },
			description: { type: "string", description: "Short summary shown to callers deciding whether to install the server." },
			publisher: { type: "string", description: "Organisation or author label for the server." },
			glyph: { type: "string", description: "Frontend icon key for the server." },
			type: { type: "string", enum: ["single-user", "multi-user", "remote-oauth"], description: "How the server is configured for connection: single-user requires a caller-owned credential through an external custody flow, multi-user uses an administrator-managed shared key, and remote-oauth requires an OAuth handshake outside this API." },
			approvalStatus: { type: "string", enum: ["pending-review", "approved", "published", "disabled"], description: "Organisation-admin review state. Only published servers appear in the user-facing catalogue; approved servers remain hidden until publication." },
			credentialSchema: { type: "array", description: "Input fields required by an external custody flow for a single-user connection. This API describes requested values but neither receives nor returns credential material.", items: { $ref: "#/components/schemas/CredentialField" } },
			entitlementSummary: { type: "string", description: "Human-readable summary of access grants, returned for the governance view." },
		},
	},
	CredentialField: {
		type: "object",
		description: "One input an external custody flow requires to connect a single-user MCP server. This API describes the input but neither receives nor returns its value.",
		required: ["key", "label", "required", "sensitive"],
		properties: {
			key: { type: "string", description: "Stable submission key for the value." },
			label: { type: "string", description: "Human-readable label for the input." },
			required: { type: "boolean", description: "Whether a caller must supply this value to connect." },
			sensitive: { type: "boolean", description: "Whether the client must treat the value as a secret, including masking it and never echoing it." },
			placeholder: { type: "string", description: "Optional example or placeholder shown in the input." },
			hint: { type: "string", description: "Optional help text shown below the input." },
		},
	},
	McpInstalled: {
		type: "object",
		description: "An MCP server installed by the calling user, with its current connection state.",
		required: ["serverId"],
		properties: {
			serverId: { type: "string", description: "Identifier of the installed server." },
			connectionStatus: { type: "string", enum: ["needs-credential", "shared-key"], description: "Recorded activation requirement: needs-credential requires an external custody flow, while shared-key records an administrator-managed shared key. This API does not activate either state." },
			lastUsed: { type: ["string", "null"], format: "date-time", description: "ISO-8601 timestamp of the server's last use, or null when it has never been used." },
		},
	},
	EntitledUser: {
		type: "object",
		description: "A local principal displayed in the MCP access editor or its selectable directory.",
		required: ["id", "name", "initials", "color"],
		properties: {
			id: { type: "string", description: "Stable local Principal identifier used by authorization grants." },
			name: { type: "string", description: "Display name shown in the access editor." },
			initials: { type: "string", description: "Initials derived from the display name for an avatar." },
			color: { type: "string", description: "Deterministic avatar colour derived from the identifier." },
		},
	},
	EntitledGroup: {
		type: "object",
		description: "A local group that can receive an MCP authorization grant.",
		required: ["id", "name"],
		properties: {
			id: { type: "string", description: "Stable local Group identifier used by authorization grants." },
			name: { type: "string", description: "Display name shown in the access editor. Authorization uses the identifier, not this value." },
		},
	},
	McpAccessPolicy: {
		type: "object",
		description: "The user and group grants managed by the MCP access editor for one server. It does not list authorization grants managed by other sources.",
		required: ["serverId", "groups", "users"],
		properties: {
			serverId: { type: "string", description: "Identifier of the governed server." },
			groups: { type: "array", description: "Groups with an active allow grant managed by the MCP access editor.", items: { $ref: "#/components/schemas/EntitledGroup" } },
			users: { type: "array", description: "Principals with an active allow grant managed by the MCP access editor.", items: { $ref: "#/components/schemas/EntitledUser" } },
		},
	},
	McpDirectory: {
		type: "object",
		description: "The users and groups that an organisation administrator can select when editing MCP access.",
		required: ["users", "groups"],
		properties: {
			users: { type: "array", description: "All local principals eligible to receive an MCP authorization grant.", items: { $ref: "#/components/schemas/EntitledUser" } },
			groups: { type: "array", description: "All local groups eligible to receive an MCP authorization grant.", items: { $ref: "#/components/schemas/EntitledGroup" } },
		},
	},
	McpbValidationSubmission: {
		type: "object",
		description: "An organisation-admin request to verify one exact published MCP bundle. The idempotency key makes a retried request return the same saved validation.",
		required: ["idempotencyKey", "artifactId", "artifactRevisionId"],
		additionalProperties: false,
		properties: {
			idempotencyKey: { type: "string", minLength: 1, maxLength: 128, description: "Caller-chosen key that safely retries this submission." },
			artifactId: { type: "string", description: "Published artifact identifier in the caller's silo." },
			artifactRevisionId: { type: "string", description: "Exact immutable published revision to verify." },
		},
	},
	McpbValidation: {
		type: "object",
		description: "Saved status of one MCP bundle validation. A background workflow verifies the signed package and its manifest after this record is created.",
		required: ["id", "artifactId", "artifactRevisionId", "byteLength", "mediaType", "submissionDigest", "state"],
		properties: {
			id: { type: "string", description: "Stable validation identifier." },
			artifactId: { type: "string", description: "Published artifact identifier selected at submission." },
			artifactRevisionId: { type: "string", description: "Immutable artifact revision selected at submission." },
			byteLength: { type: "integer", minimum: 0, description: "Saved compressed bundle size in bytes." },
			mediaType: { type: "string", description: "Media type saved with the artifact revision." },
			submissionDigest: { type: "string", description: "Digest that binds the background job to its immutable input." },
			state: { type: "string", enum: ["Pending", "Verified", "Rejected"], description: "Current validation result." },
			manifestName: { type: ["string", "null"], description: "Verified bundle name, or null until verification succeeds." },
			bundleVersion: { type: ["string", "null"], description: "Verified bundle version, or null until verification succeeds." },
			manifestDigest: { type: ["string", "null"], description: "Digest of the verified root manifest, or null until verification succeeds." },
			publisher: { type: ["string", "null"], description: "Trusted signing certificate publisher, or null until verification succeeds." },
			signerFingerprint: { type: ["string", "null"], description: "Trusted signing certificate fingerprint, or null until verification succeeds." },
			failureCode: { type: ["string", "null"], enum: ["artifact_mismatch", "bundle_too_large", "invalid_archive", "invalid_manifest", "invalid_signature", "unsupported_manifest_version", null], description: "Bounded rejection reason, or null while pending or verified." },
		},
	},
	ResourceShare: {
		type: "object",
		description: "A direct file, chat, or dataset share. Each recipient relation is backed by an explicit authorization grant.",
		required: ["id", "resourceType", "resourceId", "ownerPrincipalId", "recipientPrincipalIds"],
		properties: {
			id: { type: "string", description: "Stable share identifier used to manage recipients." },
			resourceType: { type: "string", enum: ["file", "chat", "dataset"], description: "Family of the governed resource." },
			resourceId: { type: "string", description: "Identifier of the governed resource within its family." },
			ownerPrincipalId: { type: "string", description: "Local Principal that owns the resource and may revoke its recipient relations." },
			recipientPrincipalIds: { type: "array", description: "Local Principals with explicit live recipient relations and grants.", items: { type: "string" } },
		},
	},
} as const;
