import type { ArtifactPromotionReceiptClaims, ArtifactWriteLeaseClaims } from "@opencrane/backend/artifacts/authorization";

/** TokenReview-projected runtime identity before durable attempt binding. */
export interface ConversationAssetOutputRuntimeIdentity
{
	/** Kubernetes namespace authenticated by projected TokenReview. */
	readonly namespace: string;
	/** Runtime ServiceAccount name authenticated by projected TokenReview. */
	readonly serviceAccountName: string;
	/** Exact Pod UID bound into the projected token. */
	readonly podUid: string;
}

/** Minimal runtime TokenReview seam owned by the internal output transport. */
export interface ConversationAssetOutputIdentityReviewer
{
	/** Reviews one bearer token into its minimum runtime identity. */
	__Review(token: string): Promise<ConversationAssetOutputRuntimeIdentity | null>;
}

/** Retry-stable generated-output metadata supplied before any bytes are accepted. */
export interface ReserveConversationAssetOutput
{
	/** Canonical run that created the output. */
	readonly runId: string;
	/** Exact run attempt currently assigned to the runtime. */
	readonly runAttempt: number;
	/** Runtime message identifier resolved by the server to its unique persisted start event. */
	readonly messageId: string;
	/** Retry coordinate unique inside the run attempt. */
	readonly idempotencyKey: string;
	/** Display-safe file name shown to conversation participants. */
	readonly displayName: string;
	/** Approved media type expected from ArtifactStore. */
	readonly mediaType: string;
	/** Exact positive byte length expected from ArtifactStore. */
	readonly byteLength: number;
	/** Exact SHA-256 content address expected from ArtifactStore. */
	readonly contentAddress: string;
}

/** Stable outcomes returned by generated-output reservation authority. */
export enum ConversationAssetOutputReservationOutcomes
{
	/** A new server-owned output ticket and hidden asset were created. */
	Issued = "issued",
	/** The exact retry reused its existing output ticket and asset. */
	Idempotent = "idempotent",
	/** Authority rejected the request without issuing storage capability. */
	Denied = "denied",
}

/** Stable outcomes returned after generated bytes are brokered. */
export enum ConversationAssetOutputPublishOutcomes
{
	/** Verified bytes were committed as a quarantined revision. */
	Accepted = "accepted",
	/** The exact ticket had already committed its verified revision. */
	Idempotent = "idempotent",
	/** Authority rejected or could not safely commit the bytes. */
	Denied = "denied",
}

/** Bounded denial reasons safe for the internal runtime transport. */
export enum ConversationAssetOutputDenialReasons
{
	/** Reservation metadata violated the model contract. */
	InvalidRequest = "invalid_request",
	/** The exact registered run assignment is no longer active. */
	RuntimeUnavailable = "runtime_unavailable",
	/** A retry disagreed with the immutable ticket metadata. */
	OutputConflict = "output_conflict",
	/** No live ticket and upload target matched the request. */
	OutputUnavailable = "output_unavailable",
	/** ArtifactStore promotion or receipt verification failed. */
	UploadFailed = "upload_failed",
}

/** Internal ticket response without write authority or storage coordinates. */
export type ConversationAssetOutputReservationResult = { readonly outcome: ConversationAssetOutputReservationOutcomes.Issued; readonly ticketId: string } | { readonly outcome: ConversationAssetOutputReservationOutcomes.Idempotent; readonly ticketId: string } | { readonly outcome: ConversationAssetOutputReservationOutcomes.Denied; readonly reason: ConversationAssetOutputDenialReasons.InvalidRequest | ConversationAssetOutputDenialReasons.RuntimeUnavailable | ConversationAssetOutputDenialReasons.OutputConflict };

/** Internal content publication response projected without receipt or storage evidence. */
export type ConversationAssetOutputPublishResult = { readonly outcome: ConversationAssetOutputPublishOutcomes.Accepted } | { readonly outcome: ConversationAssetOutputPublishOutcomes.Idempotent } | { readonly outcome: ConversationAssetOutputPublishOutcomes.Denied; readonly reason: ConversationAssetOutputDenialReasons.RuntimeUnavailable | ConversationAssetOutputDenialReasons.OutputUnavailable | ConversationAssetOutputDenialReasons.UploadFailed };

/** Server-only status for a retry-stable generated-output target. */
export enum ConversationAssetOutputTargetStatuses
{
	/** Ticket still owns one live expected-content write lease. */
	Issued = "issued",
	/** Ticket already committed its immutable revision. */
	Completed = "completed",
}

/** Transaction-scoped issued output target kept server-side. */
export type ConversationAssetOutputTarget = { readonly status: ConversationAssetOutputTargetStatuses.Issued; readonly lease: ArtifactWriteLeaseClaims } | { readonly status: ConversationAssetOutputTargetStatuses.Completed };

/** Persistence contract for exact generated-output issuance and finalization. */
export interface ConversationAssetOutputRepository
{
	/** Reserves or replays the exact generated output aggregate. */
	reserve(identity: ConversationAssetOutputRuntimeIdentity, command: ReserveConversationAssetOutput): Promise<ConversationAssetOutputReservationResult>;
	/** Reads one server-only active write target. */
	readUploadTarget(identity: ConversationAssetOutputRuntimeIdentity, ticketId: string): Promise<ConversationAssetOutputTarget | null>;
	/** Finalizes one verified receipt into quarantine. */
	finalize(identity: ConversationAssetOutputRuntimeIdentity, ticketId: string, promotion: ArtifactPromotionReceiptClaims, receiptDigest: string): Promise<ConversationAssetOutputPublishResult>;
}

/** Runtime-facing generated-output authority; raw leases and receipts stay behind this port. */
export interface ConversationAssetOutputAuthority
{
	/** Reserves one runtime-owned generated output. */
	reserve(identity: ConversationAssetOutputRuntimeIdentity, command: ReserveConversationAssetOutput): Promise<ConversationAssetOutputReservationResult>;
	/** Brokers exact bytes for one server-owned ticket. */
	publish(identity: ConversationAssetOutputRuntimeIdentity, ticketId: string, bytes: AsyncIterable<Uint8Array>): Promise<ConversationAssetOutputPublishResult>;
}

/** Internal router dependencies fixed by app composition. */
export interface ConversationAssetOutputRouterDependencies
{
	/** Projected runtime identity reviewer. */
	readonly tokenReviewer: ConversationAssetOutputIdentityReviewer;
	/** Durable generated-output authority. */
	readonly authority: ConversationAssetOutputAuthority;
	/** Structured failure logger with redaction applied upstream. */
	readonly logger: { error(value: object, message: string): void };
}
