import type { Es256PublicJwk } from "@opencrane/models/authorization";
import type { AgentRuntimeProjectedTokenAudience, ManagedAgentRuntimeProjectedTokenAudience } from "@opencrane/contracts";

import type { RuntimeBootstrapRepository } from "./runtime-proof.types.js";

/** TokenReview-confirmed identity of a runtime workload presenting a projected credential. */
export interface RuntimeBootstrapReviewedIdentity
{
	/** Exact Kubernetes username returned by TokenReview. */
	readonly subject: string;
	/** Kubernetes namespace parsed from the reviewed subject. */
	readonly namespace: string;
	/** Kubernetes ServiceAccount name parsed from the reviewed subject. */
	readonly serviceAccountName: string;
	/** Kubernetes Pod UID asserted by TokenReview for this projected token. */
	readonly podUid: string;
}

/**
 * Asks Kubernetes who a projected ServiceAccount token belongs to.
 *
 * This is the only thing that authenticates the bootstrap route — there is no session and no API
 * key — so the reviewer must be bound to the runtime audience, not a general-purpose one.
 */
export interface RuntimeBootstrapTokenReviewer
{
	/** Reviews one token against the dedicated agent-runtime audience. */
	__Review(token: string): Promise<RuntimeBootstrapReviewedIdentity | null>;
}

/** Trusted server clock used to fence bootstrap expiry rather than a runtime-supplied time. */
export interface RuntimeBootstrapClock
{
	/** Returns the trusted current epoch milliseconds. */
	nowEpochMs(): number;
}

/** Body a runtime submits to bind its freshly generated public proof key to one bootstrap. */
export interface RuntimeBootstrapSubmission
{
	/** Opaque one-use bootstrap reference projected into the runtime Pod. */
	readonly bootstrapReference: string;
	/** Public P-256 key generated by the runtime for this run binding. */
	readonly proofPublicJwk: Es256PublicJwk;
	/** Runtime-proposed RFC 7638 thumbprint, re-derived from the public key before binding. */
	readonly proofKeyThumbprint: string;
}

/** Durable authority loaded for one bootstrap, split into its bootstrap and assignment sources. */
export interface RuntimeBootstrapExchangeRecord
{
	/** WorkloadBootstrap primary key equal to the opaque reference. */
	readonly bootstrapId: string;
	/** Silo recorded on the bootstrap row. */
	readonly bootstrapSiloId: string;
	/** Subject recorded on the bootstrap row. */
	readonly bootstrapSubjectId: string;
	/** Projected-token audience recorded on the bootstrap row. */
	readonly bootstrapAudience: AgentRuntimeProjectedTokenAudience | ManagedAgentRuntimeProjectedTokenAudience;
	/** ServiceAccount recorded on the bootstrap row. */
	readonly bootstrapServiceAccountName: string;
	/** Namespace recorded on the bootstrap row. */
	readonly bootstrapNamespace: string;
	/** Controller workload kind recorded on the bootstrap row. */
	readonly bootstrapWorkloadKind: "job" | "deployment";
	/** Controller workload UID recorded on the bootstrap row. */
	readonly bootstrapWorkloadUid: string;
	/** Run recorded on the bootstrap row. */
	readonly bootstrapRunId: string;
	/** AgentService recorded on the bootstrap row. */
	readonly bootstrapAgentServiceId: string;
	/** Attempt recorded on the bootstrap row. */
	readonly bootstrapAttempt: number;
	/** AgentRevision recorded on the bootstrap row. */
	readonly bootstrapAgentRevisionId: string;
	/** Hard bootstrap expiry in epoch milliseconds. */
	readonly bootstrapExpiresAtEpochMs: number;
	/** Silo recorded on the independent assignment row. */
	readonly assignmentSiloId: string;
	/** Subject recorded on the independent assignment row. */
	readonly assignmentSubjectId: string;
	/** Projected-token audience recorded on the independent assignment row. */
	readonly assignmentAudience: AgentRuntimeProjectedTokenAudience | ManagedAgentRuntimeProjectedTokenAudience;
	/** Controller workload kind recorded on the independent assignment row. */
	readonly assignmentWorkloadKind: "job" | "deployment";
	/** Controller workload UID recorded on the independent assignment row. */
	readonly assignmentWorkloadUid: string;
	/** Registered runtime Pod UID recorded on the independent assignment row. */
	readonly assignmentPodUid: string;
	/** Run recorded on the independent assignment row. */
	readonly assignmentRunId: string;
	/** AgentService recorded on the independent assignment row. */
	readonly assignmentAgentServiceId: string;
	/** Attempt recorded on the independent assignment row. */
	readonly assignmentAttempt: number;
	/** AgentRevision recorded on the independent assignment row. */
	readonly assignmentAgentRevisionId: string;
}

/**
 * Loads a bootstrap together with the separate assignment row, then spends it.
 *
 * Extends {@link RuntimeBootstrapRepository} with the read half so one dependency covers both. The
 * read deliberately returns BOTH rows' fields, un-merged, so the router can compare two independent
 * sources rather than trust either alone.
 *
 * Implemented by: ./prisma-runtime-bootstrap-exchange.ts.
 */
export interface RuntimeBootstrapExchangeRepository extends RuntimeBootstrapRepository
{
	/**
	 * Loads one bootstrap and the assignment row for the same run attempt.
	 * @param bootstrapReference - The opaque one-use reference projected into the runtime pod.
	 * @returns Both rows' fields side by side, or null when the bootstrap is missing, no pod has
	 *   registered yet, or either row's audience is not a recognised runtime audience. Null is not an
	 *   error — the router answers 409.
	 */
	loadBootstrapExchange(bootstrapReference: string): Promise<RuntimeBootstrapExchangeRecord | null>;
}

/** The one logger method this router needs. */
export interface RuntimeBootstrapLogger
{
	/** Records a failed internal operation without serialising credentials or key material. */
	error(bindings: { readonly err: unknown; readonly operation: string }, message: string): void;
}

/**
 * Everything {@link __CreateRuntimeBootstrapRouter} needs, all injected.
 *
 * Nothing here is read from the request. The clock in particular is a dependency so a runtime can
 * never extend its own bootstrap deadline by sending a time. `runtimeNamespaces` is a fixed pair —
 * personal and managed — and a reviewed pod outside both is rejected before any database read.
 *
 * Composed in: apps/opencrane/src/app/runtime-composition.ts.
 */
export interface RuntimeBootstrapRouterDependencies
{
	/** Dedicated projected-token identity reviewer for the runtime audience. */
	readonly tokenReviewer: RuntimeBootstrapTokenReviewer;
	/** Exact personal and managed namespaces in which runtime ServiceAccounts may exist. */
	readonly runtimeNamespaces: readonly [string, string];
	/** Durable bootstrap load-and-consume authority. */
	readonly repository: RuntimeBootstrapExchangeRepository;
	/** Trusted server clock. */
	readonly clock: RuntimeBootstrapClock;
	/** Shared process logger carrying request and trace context. */
	readonly logger: RuntimeBootstrapLogger;
}
