"""Publish one generated conversation asset through the private control-plane byte broker."""

import hashlib
import json
from collections.abc import Callable
from urllib.request import Request, urlopen


_MAXIMUM_OUTPUT_BYTES = 200 * 1024 * 1024


def publish_output_asset(
    control_plane_url: str,
    token: str,
    coordinates: dict[str, object],
    message_id: str,
    output: dict[str, object],
    send_json: Callable[[str, str, dict[str, object], float], tuple[int, dict[str, object]]] | None = None,
    send_bytes: Callable[[str, str, bytes, float], tuple[int, dict[str, object]]] | None = None,
) -> None:
    """Reserve and upload exact bytes once without exposing server storage authority.

    Transport failures are ambiguous after dispatch, so this client never retries. The server owns
    idempotent replay through the supplied output key and returns no lease, receipt, or address.
    """
    content = output.get("content")
    display_name = output.get("displayName")
    media_type = output.get("mediaType")
    idempotency_key = output.get("idempotencyKey")
    if (
        not isinstance(content, bytes)
        or not 0 < len(content) <= _MAXIMUM_OUTPUT_BYTES
        or not isinstance(display_name, str)
        or not 0 < len(display_name.strip()) <= 255
        or not isinstance(media_type, str)
        or not 0 < len(media_type.strip()) <= 255
        or not isinstance(idempotency_key, str)
        or not 0 < len(idempotency_key.strip()) <= 128
    ):
        raise ValueError("generated output is invalid")
    run_id = coordinates.get("runId")
    attempt = coordinates.get("attempt")
    if not isinstance(run_id, str) or not isinstance(attempt, int) or attempt < 1:
        raise ValueError("generated output coordinates are invalid")
    reserve = send_json or _post_json
    publish = send_bytes or _put_bytes
    base = control_plane_url.rstrip("/")
    status, reservation = reserve(
        f"{base}/conversation-assets/outputs:reserve",
        token,
        {
            "runId": run_id,
            "runAttempt": attempt,
            "messageId": message_id,
            "idempotencyKey": idempotency_key.strip(),
            "displayName": display_name.strip(),
            "mediaType": media_type.strip(),
            "byteLength": len(content),
            "contentAddress": "sha256:" + hashlib.sha256(content).hexdigest(),
        },
        30,
    )
    ticket_id = reservation.get("ticketId")
    if status not in (200, 201) or reservation.get("outcome") not in ("issued", "idempotent") or not isinstance(ticket_id, str):
        raise RuntimeError(f"generated output reservation returned unexpected status {status}")
    publish_status, result = publish(
        f"{base}/conversation-assets/outputs/{ticket_id}/content",
        token,
        content,
        30,
    )
    if publish_status not in (200, 202) or result.get("outcome") not in ("accepted", "idempotent"):
        raise RuntimeError(f"generated output publication returned unexpected status {publish_status}")


def _post_json(url: str, token: str, body: dict[str, object], timeout: float) -> tuple[int, dict[str, object]]:
    """Send one authenticated JSON request and decode one bounded result object."""
    request = Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json", "Accept": "application/json"},
        method="POST",
    )
    return _read_json(request, timeout)


def _put_bytes(url: str, token: str, content: bytes, timeout: float) -> tuple[int, dict[str, object]]:
    """Send exact generated bytes once; credentials remain header-only."""
    request = Request(
        url,
        data=content,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/octet-stream", "Accept": "application/json"},
        method="PUT",
    )
    return _read_json(request, timeout)


def _read_json(request: Request, timeout: float) -> tuple[int, dict[str, object]]:
    """Decode only a small JSON object returned by the private output authority."""
    with urlopen(request, timeout=timeout) as response:
        raw = response.read(64 * 1024 + 1)
        if len(raw) > 64 * 1024:
            raise RuntimeError("generated output response exceeded its bound")
        parsed = json.loads(raw.decode("utf-8"))
        if not isinstance(parsed, dict):
            raise RuntimeError("generated output response is invalid")
        return response.status, parsed
