/** Links a child to the immutable group message that requested its work. */
const _GroupChildOriginSchema = { type: "object", additionalProperties: false, required: ["requestId", "parentConversationId", "parentMessageId", "parentMessagePosition"], properties: { requestId: { type: "string", format: "uuid" }, parentConversationId: { type: "string" }, parentMessageId: { type: "string", format: "uuid" }, parentMessagePosition: { type: "string", pattern: "^[1-9][0-9]{0,19}$" } } } as const;
/** Reports admitted creation without exposing identity or execution internals. */
const _GroupChildViewSchema = { type: "object", additionalProperties: false, required: ["conversationId", "parentConversationId", "parentMessageId", "parentMessagePosition", "state", "agentName"], properties: { conversationId: { type: "string" }, parentConversationId: { type: "string" }, parentMessageId: { type: "string", format: "uuid" }, parentMessagePosition: { type: "string", pattern: "^[1-9][0-9]{0,19}$" }, state: { type: "string", enum: ["pending", "ready", "unavailable"] }, agentName: { type: "string" } } } as const;
/** Uses indistinguishable absent and inaccessible failures for child commands. */
const _GroupChildFailures = { 400: { description: "Malformed command." }, 401: { description: "Authentication required." }, 404: { description: "Conversation or selected source unavailable." }, 409: { description: "The retry key already names a different command." }, 503: { description: "Conversation dependency unavailable." } } as const;
/** Immutable participant conversation entry schema shared by KurrentDB history responses. */
const _ConversationEntrySchema = { type: "object", additionalProperties: true, required: ["schemaVersion", "id", "conversationId", "position", "kind", "author", "provenance", "visibility", "runId", "causationId", "correlationId", "idempotencyKey", "occurredAt", "attestation"], properties: { schemaVersion: { type: "integer", enum: [1] }, id: { type: "string", format: "uuid" }, conversationId: { type: "string" }, position: { type: "string", pattern: "^(0|[1-9][0-9]*)$" }, kind: { type: "string", enum: ["message", "log", "a2ui"] }, author: { type: "object" }, provenance: { type: "string", enum: ["human-authored", "agent-authored", "service-attested"] }, visibility: { type: "object" }, runId: { type: ["string", "null"] }, causationId: { type: "string" }, correlationId: { type: "string" }, idempotencyKey: { type: "string" }, occurredAt: { type: "string", format: "date-time" }, attestation: { type: ["object", "null"] } } } as const;
/** Projection summary schema that contains opaque membership references but no transcript. */
const _SummarySchema = { type: "object", additionalProperties: false, required: ["id", "mode", "lifecycle", "agentServiceId", "participantRefs", "archivedAt", "readThroughPosition", "updatedAt"], properties: { id: { type: "string" }, mode: { type: "string", enum: ["agent_session", "direct", "group"] }, lifecycle: { type: "string", enum: ["open", "closed"] }, agentServiceId: { type: ["string", "null"] }, participantRefs: { type: "array", items: { type: "string" } }, archivedAt: { type: ["string", "null"], format: "date-time" }, readThroughPosition: { type: "string" }, updatedAt: { type: "string", format: "date-time" } } } as const;
/** Projection detail adds participant bounds but deliberately has no relational messages field. */
const _DetailSchema = { ..._SummarySchema, required: [..._SummarySchema.required, "visibleFromPosition", "accessEndedPosition", "parent"], properties: { ..._SummarySchema.properties, visibleFromPosition: { type: "string" }, accessEndedPosition: { type: ["string", "null"] }, parent: { anyOf: [_GroupChildOriginSchema, { type: "null" }] } } } as const;
/** Exact projection detail envelope shared by lifecycle operations. */
const _DetailEnvelopeSchema = { type: "object", additionalProperties: false, required: ["conversation"], properties: { conversation: _DetailSchema } } as const;
/** Shared path coordinate for every active-computer review operation. */
const _ReviewConversationParameter = { name: "conversationId", in: "path", required: true, schema: { type: "string" } } as const;
/** Shared relative workspace path used by file and diff review. */
const _ReviewPathParameter = { name: "path", in: "query", required: true, schema: { type: "string", minLength: 1 } } as const;
/** Bounded command response returned by the private computer review surface. */
const _ReviewCommandSchema = { type: "object", additionalProperties: false, required: ["exitCode", "outcome", "output", "truncated"], properties: { exitCode: { type: ["integer", "null"] }, outcome: { type: "string", enum: ["completed", "timed_out", "output_limited"] }, output: { type: "string" }, truncated: { type: "boolean" } } } as const;

/** OpenAPI fragment for participant-authorized KurrentDB conversation history. */
export const _SelfConversationHistoryOpenapiPaths = {
	"/me/conversations/{conversationId}/children": {
		get: { operationId: "listMyGroupConversationChildren", parameters: [_ReviewConversationParameter], responses: { 200: { description: "Currently visible shared child requests.", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["children"], properties: { children: { type: "array", items: _GroupChildViewSchema } } } } } }, ..._GroupChildFailures } },
		post: { operationId: "createMyGroupConversationChild", summary: "Ask the company assistant about one own group message", description: "Admits an idempotent shared child for a caller-owned conversation-audience text message. Every admitted recipient must already see the originating revision. Requires current parent Delegate, conversation creation and selected service Invoke. The child begins pending and becomes ready only after cold history and its activation are durable.", parameters: [_ReviewConversationParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["parentMessageId", "parentMessagePosition", "agentServiceId", "idempotencyKey"], properties: { parentMessageId: { type: "string", format: "uuid" }, parentMessagePosition: { type: "string", pattern: "^[1-9][0-9]{0,19}$" }, agentServiceId: { type: "string", minLength: 1, maxLength: 256 }, idempotencyKey: { type: "string", format: "uuid" } } } } } }, responses: { 202: { description: "Child creation admitted or its original request recovered.", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["child"], properties: { child: _GroupChildViewSchema } } } } }, ..._GroupChildFailures } }
	},
	"/me/conversations/{conversationId}/share": { post: { operationId: "shareMyGroupConversationChildResult", summary: "Share reviewed assistant text back to its parent group", description: "Posts as the sharing human after current parent and child access checks. The verified child source becomes causation and the originating group message becomes the reply target. A retry key binds the source and exact reviewed text; this route grants no runtime parent writer.", parameters: [_ReviewConversationParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["sourceEntryId", "sourcePosition", "text", "idempotencyKey"], properties: { sourceEntryId: { type: "string", format: "uuid" }, sourcePosition: { type: "string", pattern: "^[1-9][0-9]{0,19}$" }, text: { type: "string", minLength: 1, maxLength: 65536, description: "Human-reviewed text, limited to 65536 UTF-8 bytes." }, idempotencyKey: { type: "string", format: "uuid" } } } } } }, responses: { 202: { description: "Reviewed text accepted.", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["outcome", "position"], properties: { outcome: { type: "string", enum: ["accepted"] }, position: { type: "string" } } } } } }, 200: { description: "The same reviewed share was already accepted.", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["outcome", "position"], properties: { outcome: { type: "string", enum: ["idempotent"] }, position: { type: "string" } } } } } }, ..._GroupChildFailures } } },

	"/me/conversations/directory": { get: { operationId: "getMyConversationCreationDirectory", responses: { 200: { description: "Projection-only creation directory.", content: { "application/json": { schema: { type: "object", required: ["directory"], properties: { directory: { type: "object", required: ["participants", "personalAgentStatus", "personalAgent", "companyAssistants"], properties: { companyAssistants: { type: "array", items: { type: "object", additionalProperties: false, required: ["agentServiceId", "displayName"], properties: { agentServiceId: { type: "string" }, displayName: { type: "string" } } } }, participants: { type: "array", items: { type: "object", required: ["participantRef", "displayName", "isSelf"], properties: { participantRef: { type: "string" }, displayName: { type: "string", minLength: 1, description: "Member display name, or a generic label when no name is available. Never a login subject or email fallback." }, isSelf: { type: "boolean" } } } }, personalAgentStatus: { type: "string", enum: ["ready", "unavailable", "ambiguous"] }, personalAgent: { type: ["object", "null"] } } } } } } } } } } },
	"/me/conversations": { get: { operationId: "listMyConversations", parameters: [{ name: "includeArchived", in: "query", required: false, schema: { type: "boolean" } }], responses: { 200: { description: "Participant conversation projections.", content: { "application/json": { schema: { type: "object", required: ["conversations"], properties: { conversations: { type: "array", items: _SummarySchema } } } } } } } }, post: { operationId: "createMyConversation", requestBody: { required: true, content: { "application/json": { schema: { oneOf: [{ type: "object", additionalProperties: false, required: ["mode", "personalAgentRef", "idempotencyKey"], properties: { mode: { const: "agent_session" }, personalAgentRef: { type: "string", minLength: 1 }, idempotencyKey: { type: "string", format: "uuid", description: "Reuse this UUID for retries of the same session creation; a new UUID starts a separate session." } } }, { type: "object", additionalProperties: false, required: ["mode", "participantRefs", "idempotencyKey"], properties: { mode: { type: "string", enum: ["direct", "group"] }, participantRefs: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 99 }, idempotencyKey: { type: "string", format: "uuid", description: "Reuse this UUID for retries of the same creation request; a new UUID starts a separate conversation." } } }] } } } }, responses: { 201: { description: "Conversation projection created.", content: { "application/json": { schema: _DetailEnvelopeSchema } } }, 404: { description: "Creation target unavailable." } } } },
	"/me/conversations/{conversationId}": { get: { operationId: "openMyConversation", parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }], responses: { 200: { description: "Conversation projection without transcript data.", content: { "application/json": { schema: _DetailEnvelopeSchema } } }, 404: { description: "Conversation unavailable." } } } },
	"/me/conversations/{conversationId}/archive": { patch: { operationId: "archiveMyConversation", parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["archived"], properties: { archived: { type: "boolean" } } } } } }, responses: { 200: { description: "Participant archive projection changed.", content: { "application/json": { schema: _DetailEnvelopeSchema } } }, 404: { description: "Conversation unavailable." } } } },
	"/me/conversations/{conversationId}/close": { post: { operationId: "closeMyConversation", parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }], responses: { 200: { description: "Conversation projection closed.", content: { "application/json": { schema: _DetailEnvelopeSchema } } }, 404: { description: "Conversation unavailable." } } } },
	"/me/conversations/{conversationId}/events": { get: { operationId: "streamMyConversationEvents", summary: "Stream participant-visible conversation updates", description: "Same-origin authenticated SSE on the public listener. History frames use event: history, id: nextPosition, and JSON data {entries,payloads,nextPosition,computer:null}; every bounded page rechecks current Conversation:Read authority. The exclusive Last-Event-ID revision overrides the initial afterPosition query on reconnect. Hidden entries advance the cursor without exposing their payload. event: unavailable carries a fixed conversation_unavailable or conversation_history_unavailable error and ends automatic replay. A normal bounded close is resumable. Limits per connection: 60 seconds, 30 seconds without new history, 10-second authority-refresh heartbeats, 512 KiB per frame, 2 MiB total, 128 history frames, and 5 seconds waiting for a slow browser. Each listener allows two concurrent streams and twelve starts per minute per authenticated silo/subject. Disconnect cancels upstream history and subscription work.", tags: ["Conversations"], parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }, { name: "afterPosition", in: "query", required: false, schema: { type: "string", pattern: "^(0|[1-9][0-9]{0,19})$", maxLength: 20 }, description: "Exclusive stream revision; defaults to zero." }, { name: "Last-Event-ID", in: "header", required: false, schema: { type: "string", pattern: "^(0|[1-9][0-9]{0,19})$", maxLength: 20 }, description: "Exclusive resume revision; overrides the original query cursor." }], responses: { 200: { description: "Bounded SSE history and terminal unavailable frames; keep-alive comments do not advance the cursor.", content: { "text/event-stream": { schema: { type: "string" } } } }, 400: { description: "Malformed or out-of-range stream revision." }, 401: { description: "Authentication required." }, 403: { description: "Same-origin browser evidence required." }, 404: { description: "Conversation unavailable to the current participant." }, 429: { description: "Subject or listener event budget exhausted; Retry-After is 60 seconds." }, 503: { description: "History unavailable before the stream opens." } } } },
	"/me/conversations/{conversationId}/history": { get: { operationId: "readMyConversationHistory", summary: "Read participant-visible conversation history", description: "Reads immutable KurrentDB entries after an exclusive position cursor, then separately decrypts only private payloads referenced by entries visible to the currently authorized participant.", tags: ["Conversations"], parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }, { name: "afterPosition", in: "query", required: false, schema: { type: "string", pattern: "^(0|[1-9][0-9]*)$" }, description: "Exclusive immutable stream position." }], responses: { 200: { description: "Authorized immutable history and separately decrypted payloads.", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["entries", "payloads", "nextPosition", "computer"], properties: { entries: { type: "array", items: _ConversationEntrySchema }, payloads: { type: "object", additionalProperties: { type: "string" } }, nextPosition: { type: "string", pattern: "^(0|[1-9][0-9]*)$" }, computer: { type: ["object", "null"] } } } } } }, 400: { description: "Malformed position cursor." }, 401: { description: "Authentication required." }, 404: { description: "Conversation is unavailable to the current participant." }, 503: { description: "Conversation history or private payload authority unavailable." } } } },
	"/me/conversations/{conversationId}/messages": { post: { operationId: "postMyConversationMessage", summary: "Post one encrypted participant message", description: "Encrypts plaintext and atomically binds up to ten selected Ready PDF assets before appending opaque text and artifact coordinates to KurrentDB. Text may be empty only when at least one asset is selected. Exact retries preserve the original text, asset set, author and activation.", tags: ["Conversations"], parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["idempotencyKey", "text", "assetIds", "activation"], properties: { idempotencyKey: { type: "string", format: "uuid" }, text: { type: "string", maxLength: 65536, description: "Participant text limited to 65536 UTF-8 bytes; it may be empty only when assetIds is non-empty." }, assetIds: { type: "array", minItems: 0, maxItems: 10, uniqueItems: true, items: { type: "string", minLength: 1, maxLength: 128, pattern: "^[\\x21-\\x7E]+$" }, description: "Unique conversation asset identifiers; the server stores them in ASCII order." }, activation: { type: "string", enum: ["none", "start", "interrupt", "stop"], description: "Stop requests cancellation of the original requester's current turn without starting another turn. Admission is not cancellation completion." } } } } } }, responses: { 202: { description: "A new immutable entry was accepted.", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["outcome", "position"], properties: { outcome: { type: "string", enum: ["accepted"] }, position: { type: "string" } } } } } }, 200: { description: "The exact immutable entry was already accepted.", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["outcome", "position"], properties: { outcome: { type: "string", enum: ["idempotent"] }, position: { type: "string" } } } } } }, 400: { description: "Malformed message command." }, 401: { description: "Authentication required." }, 404: { description: "Conversation or selected asset is unavailable to the current participant." }, 409: { description: "Idempotency, asset binding or activation conflict." }, 503: { description: "Conversation history or private payload authority unavailable." } } } },
	"/me/conversations/{conversationId}/review/files": { get: { operationId: "readMyConversationComputerFile", summary: "Read one computer workspace file", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter, _ReviewPathParameter], responses: { 200: { description: "Bounded file bytes.", content: { "application/octet-stream": { schema: { type: "string", format: "binary" } } } }, 404: { description: "Active computer unavailable." }, 503: { description: "Review surface unavailable." } } } },
	"/me/conversations/{conversationId}/review/diff": { get: { operationId: "readMyConversationComputerDiff", summary: "Read one workspace diff", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter, _ReviewPathParameter], responses: { 200: { description: "Bounded diff command result.", content: { "application/json": { schema: _ReviewCommandSchema } } }, 404: { description: "Active computer unavailable." }, 503: { description: "Review surface unavailable." } } } },
	"/me/conversations/{conversationId}/review/commands": { post: { operationId: "runMyConversationComputerCommand", summary: "Run one allowlisted workspace command", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["argv"], properties: { argv: { type: "array", minItems: 1, items: { type: "string", minLength: 1 } }, cwd: { type: "string" } } } } } }, responses: { 200: { description: "Bounded command result.", content: { "application/json": { schema: _ReviewCommandSchema } } }, 404: { description: "Active computer unavailable." }, 503: { description: "Review surface unavailable." } } } },
	"/me/conversations/{conversationId}/review/browser/version": { get: { operationId: "readMyConversationComputerBrowserVersion", summary: "Read private browser metadata", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter], responses: { 200: { description: "Chromium version metadata.", content: { "application/json": { schema: { type: "object", additionalProperties: true } } } }, 404: { description: "Active computer unavailable." } } } },
	"/me/conversations/{conversationId}/review/browser/targets": { get: { operationId: "listMyConversationComputerBrowserTargets", summary: "List private browser pages", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter], responses: { 200: { description: "Current Chromium targets.", content: { "application/json": { schema: { type: "array", items: { type: "object", additionalProperties: true } } } } }, 404: { description: "Active computer unavailable." } } } },
	"/me/conversations/{conversationId}/review/browser/pages": { post: { operationId: "openMyConversationComputerBrowserPage", summary: "Open an allowlisted localhost page", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["port", "path"], properties: { port: { type: "integer" }, path: { type: "string" } } } } } }, responses: { 201: { description: "Created Chromium target.", content: { "application/json": { schema: { type: "object", additionalProperties: true } } } }, 404: { description: "Active computer unavailable." } } } },
	"/me/conversations/{conversationId}/review/browser/screenshots": { post: { operationId: "captureMyConversationComputerBrowserScreenshot", summary: "Capture an allowlisted localhost page", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["port", "path", "width", "height"], properties: { port: { type: "integer" }, path: { type: "string" }, width: { type: "integer" }, height: { type: "integer" } } } } } }, responses: { 200: { description: "PNG screenshot.", content: { "image/png": { schema: { type: "string", format: "binary" } } } }, 404: { description: "Active computer unavailable." } } } },
	"/me/conversations/{conversationId}/review/previews/{port}/{path}": { get: { operationId: "readMyConversationComputerPreview", summary: "Read an allowlisted localhost preview", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter, { name: "port", in: "path", required: true, schema: { type: "integer" } }, { name: "path", in: "path", required: true, schema: { type: "string" } }], responses: { 200: { description: "Preview response body.", content: { "text/html": { schema: { type: "string" } }, "text/plain": { schema: { type: "string" } }, "application/json": { schema: {} } } }, 400: { description: "Preview port or path unavailable." }, 404: { description: "Active computer unavailable." } } } },
} as const;
