/** Names the URL fragment field used to deliver one private Tier 2 browser session. */
const _CREDENTIAL_FRAGMENT = "development-session";

/** Names the session-scoped browser storage entry cleared when its browsing context closes. */
const _CREDENTIAL_STORAGE = "opencrane.tier2.development-session";

/** Accepts the URL-safe 256-bit credential generated by the Tier 2 launcher. */
const _CREDENTIAL_PATTERN = /^[A-Za-z0-9_-]{43}$/u;

/** Checks whether a browser value has the launcher's credential shape. */
function _isDevelopmentSessionCredential(value: string | null): value is string
{
	return value !== null && _CREDENTIAL_PATTERN.test(value);
}

/**
 * Reads a private Tier 2 browser credential without writing it to durable browser storage.
 *
 * A supplied fragment value always replaces or clears the prior tab value and is then removed from
 * browser history. Fragments stay out of HTTP requests, proxy logs and referrers. A plain URL can
 * reuse a valid credential after the private URL has been consumed in this browsing context, or
 * when a same-origin opener caused the context to inherit a copy.
 */
function _readDevelopmentSessionCredential(): string | null
{
	const url = new URL(window.location.href);
	const fragment = new URLSearchParams(url.hash.slice(1));
	const suppliedValues = fragment.getAll(_CREDENTIAL_FRAGMENT);

	if (suppliedValues.length > 0)
	{
		const supplied = suppliedValues.length === 1 && Array.from(fragment.keys()).length === 1
			? suppliedValues[0] ?? null
			: null;
		url.hash = "";
		window.history.replaceState(window.history.state, "", `${url.pathname}${url.search}${url.hash}`);
		if (_isDevelopmentSessionCredential(supplied))
		{
			window.sessionStorage.setItem(_CREDENTIAL_STORAGE, supplied);
			return supplied;
		}

		window.sessionStorage.removeItem(_CREDENTIAL_STORAGE);
		return null;
	}

	const stored = window.sessionStorage.getItem(_CREDENTIAL_STORAGE);
	if (_isDevelopmentSessionCredential(stored))
		return stored;

	window.sessionStorage.removeItem(_CREDENTIAL_STORAGE);
	return null;
}

/** Credential read by the Tier 2 header provider and route composition for this page load. */
export const OPENCRANE_TIER2_DEVELOPMENT_SESSION_CREDENTIAL = _readDevelopmentSessionCredential();
