import { Tier2DevelopmentSessionGuidanceStates, type Tier2DevelopmentSessionDocumentReplacer } from "./tier2-development-session.types";

/** Names the URL fragment field used to deliver one private Tier 2 browser session. */
const _CREDENTIAL_FRAGMENT = "development-session";

/** Names the session-scoped browser storage entry cleared when its browsing context closes. */
const _CREDENTIAL_STORAGE = "opencrane.tier2.development-session";

/** Records only why a credential-free tab needs guidance, never the discarded credential. */
const _GUIDANCE_STORAGE = "opencrane.tier2.development-session-guidance";

/** Accepts the URL-safe 256-bit credential generated by the Tier 2 launcher. */
const _CREDENTIAL_PATTERN = /^[A-Za-z0-9_-]{43}$/u;

/** Prevents concurrent failed requests from replacing the document more than once. */
let _replacementStarted = false;

/** Checks whether a browser value has the launcher's credential shape. */
function _isDevelopmentSessionCredential(value: string | null): value is string
{
	return value !== null && _CREDENTIAL_PATTERN.test(value);
}

/**
 * Reads a private Tier 2 browser credential without writing it to durable browser storage.
 *
 * A supplied fragment value always replaces or clears the prior tab value and is then removed from
 * browser history. Fragments stay out of HTTP requests, proxy logs and referrers. A plain URL can
 * reuse a valid credential after the private URL has been consumed in this browsing context, or
 * when a same-origin opener caused the context to inherit a copy.
 */
function _readDevelopmentSessionCredential(): string | null
{
	const url = new URL(window.location.href);
	const fragment = new URLSearchParams(url.hash.slice(1));
	const suppliedValues = fragment.getAll(_CREDENTIAL_FRAGMENT);

	if (suppliedValues.length > 0)
	{
		const supplied = suppliedValues.length === 1 && Array.from(fragment.keys()).length === 1
			? suppliedValues[0] ?? null
			: null;
		url.hash = "";
		window.history.replaceState(window.history.state, "", `${url.pathname}${url.search}${url.hash}`);
		if (_isDevelopmentSessionCredential(supplied))
		{
			window.sessionStorage.setItem(_CREDENTIAL_STORAGE, supplied);
			window.sessionStorage.removeItem(_GUIDANCE_STORAGE);
			return supplied;
		}

		window.sessionStorage.removeItem(_CREDENTIAL_STORAGE);
		return null;
	}

	const stored = window.sessionStorage.getItem(_CREDENTIAL_STORAGE);
	if (_isDevelopmentSessionCredential(stored))
		return stored;

	window.sessionStorage.removeItem(_CREDENTIAL_STORAGE);
	return null;
}

/** Reads the non-secret explanation that the credential-free route should present. */
function _readGuidanceState(): Tier2DevelopmentSessionGuidanceStates
{
	const stored = window.sessionStorage.getItem(_GUIDANCE_STORAGE);

	if (stored === Tier2DevelopmentSessionGuidanceStates.Replaced)
		return Tier2DevelopmentSessionGuidanceStates.Replaced;

	window.sessionStorage.removeItem(_GUIDANCE_STORAGE);
	return Tier2DevelopmentSessionGuidanceStates.Missing;
}

/** Uses the browser navigation primitive without exposing it as mutable application state. */
function _replaceCurrentDocument(url: string): void
{
	window.location.replace(url);
}

/**
 * Ends an obsolete Tier 2 tab session and reloads it as terminal guidance.
 *
 * The marker contains no credential. A valid private URL consumed by the new tab clears it.
 */
export function _ReplaceTier2DevelopmentSession(replaceDocument: Tier2DevelopmentSessionDocumentReplacer = _replaceCurrentDocument): void
{
	if (_replacementStarted)
		return;

	_replacementStarted = true;
	window.sessionStorage.removeItem(_CREDENTIAL_STORAGE);
	window.sessionStorage.setItem(_GUIDANCE_STORAGE, Tier2DevelopmentSessionGuidanceStates.Replaced);
	replaceDocument(`${window.location.pathname}${window.location.search}`);
}

/** Credential read by the Tier 2 header provider and route composition for this page load. */
export const OPENCRANE_TIER2_DEVELOPMENT_SESSION_CREDENTIAL = _readDevelopmentSessionCredential();

/** Guidance selected for a credential-free Tier 2 route on this page load. */
export const OPENCRANE_TIER2_DEVELOPMENT_SESSION_GUIDANCE_STATE = _readGuidanceState();
