import type { McpToolCallResult } from "@opencrane/contracts";
import type { ProductAuthorizationRunContext, ProductAuthorizationWorkloadContext } from "@opencrane/backend/server/iam/authorization";
import type { RuntimeWorkloadIdentity } from "@opencrane/backend/server/infra/workload-identity";
import type { JsonValue } from "@opencrane/util";

/** Coordinates copied from the authenticated MCP terminal request before capture authority is checked. */
export interface GeneratedFileCaptureProof
{
	/** Current companion fence issued for this invocation delivery. */
	readonly claimFence: string;
	/** Saved MCP runtime execution selected by the companion claim. */
	readonly executionId: string;
	/** Opaque execution reference originally projected to the companion. */
	readonly executionReference: string;
	/** Pod UID repeated by the strict terminal request. */
	readonly podUid: string;
	/** TokenReview-confirmed identity for the companion Pod. */
	readonly workload: RuntimeWorkloadIdentity;
}

/** One checked MCP result offered to the generated-file transaction participant. */
export interface CaptureGeneratedFileCommand extends GeneratedFileCaptureProof
{
	/** Strict MCP result before embedded bytes are removed from durable tool output. */
	readonly result: McpToolCallResult;
}

/** Personal execution facts proven current by the existing run, lease, membership and tool owners. */
export interface GeneratedFileCurrentExecutionEvidence
{
	/** Immutable agent revision and service coordinates used by product authorization. */
	readonly authorizationRun: ProductAuthorizationRunContext;
	/** TokenReview-confirmed MCP executor identity used by product authorization. */
	readonly authorizationWorkload: ProductAuthorizationWorkloadContext;
	/** Conversation turn bootstrap command that selected the tool. */
	readonly bootstrapId: string;
	/** Current personal conversation computer. */
	readonly computerId: string;
	/** Personal conversation that will own the generated asset. */
	readonly conversationId: string;
	/** Current MCP execution and companion fence matched against the terminal request. */
	readonly execution: Pick<GeneratedFileCaptureProof, "claimFence" | "executionId" | "executionReference">;
	/** Canonical effective arguments already admitted for the exact tool invocation. */
	readonly effectiveArguments: JsonValue;
	/** Immutable identity of the personal agent that authored the generated bytes. */
	readonly agentIdentityId: string;
	/** Positive attempt of the current personal run. */
	readonly attempt: number;
	/** Current conversation computer lease generation. */
	readonly leaseGeneration: number;
	/** Current conversation computer lease identity. */
	readonly leaseId: string;
	/** Absolute authority deadline; capture must finish its writes before this instant. */
	readonly notAfterEpochMs: number;
	/** Human Principal represented by the personal run and owner of the generated Artifact. */
	readonly requesterPrincipalId: string;
	/** Current participant subject belonging to the represented requester. */
	readonly requesterSubjectId: string;
	/** Personal AgentRun that owns the invocation. */
	readonly runId: string;
	/** Immutable MCP server revision that executed the tool. */
	readonly serverRevisionId: string;
	/** Silo shared by the run, conversation, MCP execution and future Artifact. */
	readonly siloId: string;
	/** Database identity of the authorization-owned ToolInvocation. */
	readonly toolInvocationRowId: string;
	/** Runtime tool call identifier returned to the model. */
	readonly toolInvocationId: string;
	/** Exact first-party tool name loaded from the selected MCP revision. */
	readonly toolName: string;
	/** Immutable MCP tool revision selected by the run. */
	readonly toolRevisionId: string;
}

/** Same-transaction authority adapter over the existing conversation tool dispatch checks. */
export interface GeneratedFileCurrentExecutionAuthority
{
	/**
	 * Return a current personal execution or null after any task, managed, inactive requester,
	 * closed conversation, stale run, lease, tool, server, invocation or workload proof is refused.
	 */
	admitCurrent(proof: GeneratedFileCaptureProof, now: Date): Promise<GeneratedFileCurrentExecutionEvidence | null>;
}

/** Closed outcomes let the MCP owner distinguish ordinary scalar results from captured files. */
export enum GeneratedFileCaptureOutcomes
{
	/** The selected tool returned no embedded resource and belongs to the ordinary result path. */
	NotApplicable = "not_applicable",
	/** Exact generated bytes entered encrypted custody and were replaced by metadata. */
	Captured = "captured",
}

/** Result returned to the MCP completion owner after this transaction participant runs. */
export type GeneratedFileCaptureResult =
	| { readonly outcome: GeneratedFileCaptureOutcomes.NotApplicable }
	| { readonly outcome: GeneratedFileCaptureOutcomes.Captured; readonly result: McpToolCallResult };

/** Transaction-bound participant that captures one eligible generated resource before MCP completion commits. */
export interface GeneratedFileCaptureRepository
{
	/** Capture encrypted bytes and immutable publication coordinates, or preserve an ordinary MCP result. */
	capture(command: CaptureGeneratedFileCommand): Promise<GeneratedFileCaptureResult>;
}

/** Identifier-only input for the asynchronous promotion and scan owner. */
export interface ConversationGeneratedFileTaskInput
{
	/** Immutable operation whose encrypted bytes the worker must reload. */
	readonly operationId: string;
	/** Silo used to scope every worker read. */
	readonly siloId: string;
}

/** Every deterministic database coordinate allocated for one immutable invocation capture. */
export interface GeneratedFileCaptureIdentity
{
	/** Requester-owned logical Artifact that will eventually expose a checked revision. */
	readonly artifactId: string;
	/** Conversation asset kept Uploading until the promotion and scan owner advances it. */
	readonly assetId: string;
	/** Opaque one-lease capability identity; this value is never returned to the MCP peer. */
	readonly capabilityJti: string;
	/** Immutable operation uniquely bound to the authorization-owned ToolInvocation row. */
	readonly operationId: string;
	/** Reserved first immutable revision identity used by later promotion. */
	readonly revisionId: string;
	/** Stable workflow admission key for this one operation. */
	readonly taskKey: string;
	/** Reserved write lease used by the generated-file worker. */
	readonly uploadLeaseId: string;
}

/** Immutable operation projection required to validate one exact capture replay. */
export interface PersistedGeneratedFileReplay
{
	/** Authoring personal agent identity. */
	readonly agentIdentityId: string;
	/** Requester-owned Artifact identity. */
	readonly artifactId: string;
	/** Conversation asset identity. */
	readonly assetId: string;
	/** Positive run attempt. */
	readonly attempt: number;
	/** Original turn bootstrap identity. */
	readonly bootstrapId: string;
	/** Complete plaintext byte length. */
	readonly byteLength: bigint;
	/** Exact number of required ciphertext rows. */
	readonly chunkCount: number;
	/** Ordered relational custody manifest. */
	readonly chunks: readonly PersistedGeneratedFileReplayChunk[];
	/** Digest binding the complete ordered ciphertext manifest. */
	readonly ciphertextManifestDigest: string;
	/** Original conversation computer identity. */
	readonly computerId: string;
	/** Complete plaintext content address. */
	readonly contentAddress: string;
	/** Owning personal conversation. */
	readonly conversationId: string;
	/** Persisted custody format. */
	readonly custodyManifestVersion: string;
	/** Safe display name derived from admitted arguments. */
	readonly displayName: string;
	/** Immutable generated-file operation identity. */
	readonly id: string;
	/** Original computer lease generation. */
	readonly leaseGeneration: number;
	/** Original computer lease identity. */
	readonly leaseId: string;
	/** Fixed generated CSV media type. */
	readonly mediaType: string;
	/** Digest of the original strict MCP result. */
	readonly rawResultDigest: string;
	/** Human Principal that owns the Artifact. */
	readonly requesterPrincipalId: string;
	/** Human participant subject that owns the ConversationAsset. */
	readonly requesterSubject: string;
	/** Reserved first artifact revision identity. */
	readonly revisionId: string;
	/** Original personal AgentRun identity. */
	readonly runId: string;
	/** Exact executed MCP server revision. */
	readonly serverRevisionId: string;
	/** Owning silo. */
	readonly siloId: string;
	/** Runtime-facing tool call identifier. */
	readonly toolInvocationId: string;
	/** Authorization-owned ToolInvocation database identity. */
	readonly toolInvocationRowId: string;
	/** Exact executed MCP tool revision. */
	readonly toolRevisionId: string;
	/** Reserved upload lease identity. */
	readonly uploadLeaseId: string;
	/** Engine-owned task identity returned by transactional admission. */
	readonly workflowTaskId: string;
	/** Domain-owned task idempotency key. */
	readonly workflowTaskKey: string;
	/** Declared generated-file task name. */
	readonly workflowTaskName: string;
}

/** Ordered child evidence used to reconstruct a saved generated file. */
export interface PersistedGeneratedFileReplayChunk
{
	/** Digest of the exact encrypted payload row. */
	readonly ciphertextDigest: string;
	/** Expected decoded byte length at this position. */
	readonly decodedByteLength: number;
	/** Zero-based contiguous manifest position. */
	readonly index: number;
	/** Deterministic private-payload reference. */
	readonly payloadRef: string;
}
