/** Content-free failure that forces the surrounding MCP completion transaction to roll back. */
export class GeneratedFileCaptureError extends Error
{
	/** Create one stable capture failure without retaining tool arguments or generated bytes. */
	constructor(message: string)
	{
		super(message);
		this.name = "GeneratedFileCaptureError";
	}
}
