BEGIN;

CREATE FUNCTION pg_temp.expect_failure(test_name TEXT, statement TEXT, expected_message TEXT) RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE actual_message TEXT;
BEGIN
    BEGIN EXECUTE statement;
    EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS actual_message = MESSAGE_TEXT;
        IF strpos(actual_message, expected_message) > 0 THEN RAISE NOTICE 'PASS: %', test_name; RETURN; END IF;
        RAISE EXCEPTION 'FAIL: % returned unexpected error: %', test_name, actual_message;
    END;
    RAISE EXCEPTION 'FAIL: % unexpectedly succeeded', test_name;
END;
$$;

INSERT INTO "persona_profiles" ("id", "silo_id", "user_id", "updated_at") VALUES ('preference-profile','silo-preference','user-1',clock_timestamp());
INSERT INTO "preference_facts" ("id", "silo_id", "user_id", "persona_profile_id", "preference_key", "statement", "state", "consent_state", "provenance_kind", "provenance", "confidence", "sensitivity", "recorded_by", "idempotency_key") VALUES ('preference-candidate','silo-preference','user-1','preference-profile','answer.tone','Use a calm tone.','candidate','pending','explicit_statement','{"source":"user"}',1,'ordinary','user-1','preference-candidate');
SELECT pg_temp.expect_failure('candidate cannot forge acceptance evidence while forgotten', $statement$UPDATE "preference_facts" SET "state" = 'forgotten', "consent_state" = 'confirmed', "accepted_by" = 'user-1', "accepted_at" = clock_timestamp(), "forgotten_at" = clock_timestamp() WHERE "id" = 'preference-candidate'$statement$, 'forgotten PreferenceFact must retain only prior acceptance evidence');
UPDATE "preference_facts" SET "state" = 'accepted', "consent_state" = 'confirmed', "accepted_by" = 'user-1', "accepted_at" = clock_timestamp() WHERE "id" = 'preference-candidate';
SELECT pg_temp.expect_failure('promoted candidate acceptance remains immutable', $statement$UPDATE "preference_facts" SET "accepted_at" = clock_timestamp() WHERE "id" = 'preference-candidate'$statement$, 'PreferenceFact acceptance evidence is immutable');
INSERT INTO "preference_facts" ("id", "silo_id", "user_id", "persona_profile_id", "preference_key", "statement", "state", "consent_state", "provenance_kind", "provenance", "confidence", "sensitivity", "recorded_by", "accepted_by", "idempotency_key", "accepted_at") VALUES ('preference-1','silo-preference','user-1','preference-profile','answer.order','Give the conclusion first.','accepted','explicit','explicit_statement','{"source":"user"}',1,'ordinary','user-1','user-1','preference-key-1',clock_timestamp());
SELECT pg_temp.expect_failure('accepted preference requires its owner approval', $statement$INSERT INTO "preference_facts" ("id", "silo_id", "user_id", "persona_profile_id", "preference_key", "statement", "state", "consent_state", "provenance_kind", "provenance", "confidence", "sensitivity", "recorded_by", "accepted_by", "idempotency_key", "accepted_at") VALUES ('preference-wrong-approver','silo-preference','user-1','preference-profile','answer.length','Keep answers brief.','accepted','explicit','explicit_statement','{"source":"user"}',1,'ordinary','user-1','another-user','preference-wrong-approver',clock_timestamp())$statement$, 'accepted PreferenceFact requires owner consent and approval');
INSERT INTO "preference_facts" ("id", "silo_id", "user_id", "persona_profile_id", "preference_key", "statement", "state", "consent_state", "provenance_kind", "provenance", "confidence", "sensitivity", "supersedes_fact_id", "recorded_by", "accepted_by", "idempotency_key", "accepted_at") VALUES ('preference-2','silo-preference','user-1','preference-profile','answer.order','Use a short conclusion, then the reasoning.','accepted','confirmed','explicit_statement','{"source":"correction"}',1,'ordinary','preference-1','user-1','user-1','preference-key-2',clock_timestamp());
SELECT pg_temp.expect_failure('accepted preference approver remains immutable', $statement$UPDATE "preference_facts" SET "accepted_by" = 'another-user' WHERE "id" = 'preference-2'$statement$, 'PreferenceFact acceptance evidence is immutable');
SELECT pg_temp.expect_failure('accepted preference time remains immutable', $statement$UPDATE "preference_facts" SET "accepted_at" = clock_timestamp() WHERE "id" = 'preference-2'$statement$, 'PreferenceFact acceptance evidence is immutable');
SELECT pg_temp.expect_failure('accepted preference consent remains immutable', $statement$UPDATE "preference_facts" SET "consent_state" = 'explicit' WHERE "id" = 'preference-2'$statement$, 'PreferenceFact acceptance evidence is immutable');
SELECT pg_temp.expect_failure('candidate correction cannot replace an accepted preference', $statement$INSERT INTO "preference_facts" ("id", "silo_id", "user_id", "persona_profile_id", "preference_key", "statement", "state", "consent_state", "provenance_kind", "provenance", "confidence", "sensitivity", "supersedes_fact_id", "recorded_by", "idempotency_key") VALUES ('preference-candidate-correction','silo-preference','user-1','preference-profile','answer.order','An unconfirmed correction.','candidate','pending','explicit_statement','{"source":"candidate"}',1,'ordinary','preference-2','user-1','preference-candidate-correction')$statement$, 'PreferenceFact correction successor must be accepted with owner consent');
SELECT pg_temp.expect_failure('one preference cannot have two correction successors', $statement$INSERT INTO "preference_facts" ("id", "silo_id", "user_id", "persona_profile_id", "preference_key", "statement", "state", "consent_state", "provenance_kind", "provenance", "confidence", "sensitivity", "supersedes_fact_id", "recorded_by", "accepted_by", "idempotency_key", "accepted_at") VALUES ('preference-3','silo-preference','user-1','preference-profile','answer.order','A competing correction.','accepted','confirmed','explicit_statement','{"source":"correction"}',1,'ordinary','preference-1','user-1','user-1','preference-key-3',clock_timestamp())$statement$, 'PreferenceFact correction must supersede an accepted same-owner fact');
SELECT pg_temp.expect_failure('sensitive inferred preference is rejected', $statement$INSERT INTO "preference_facts" ("id", "silo_id", "user_id", "persona_profile_id", "preference_key", "statement", "state", "consent_state", "provenance_kind", "provenance", "confidence", "sensitivity", "source_message_id", "recorded_by", "idempotency_key") VALUES ('preference-sensitive','silo-preference','user-1','preference-profile','sensitive.trait','Inferred sensitive trait.','candidate','pending','inferred','{"evidence":3}',0.5,'sensitive','missing-message','user-1','preference-sensitive')$statement$, 'sensitive PreferenceFact cannot be inferred');
SELECT pg_temp.expect_failure('accepted preference needs consent', $statement$INSERT INTO "preference_facts" ("id", "silo_id", "user_id", "persona_profile_id", "preference_key", "statement", "state", "consent_state", "provenance_kind", "provenance", "confidence", "sensitivity", "recorded_by", "idempotency_key", "accepted_at") VALUES ('preference-no-consent','silo-preference','user-1','preference-profile','tone.direct','Be direct.','accepted','pending','explicit_statement','{"source":"user"}',1,'ordinary','user-1','preference-no-consent',clock_timestamp())$statement$, 'accepted PreferenceFact requires owner consent and approval');
SELECT pg_temp.expect_failure('preference evidence cannot be deleted', $statement$DELETE FROM "preference_facts" WHERE "id"='preference-1'$statement$, 'PreferenceFact rows use explicit forget lifecycle');
UPDATE "preference_facts" SET "state"='forgotten', "forgotten_at"=clock_timestamp() WHERE "id"='preference-2';
SELECT pg_temp.expect_failure('forgotten preference cannot reactivate', $statement$UPDATE "preference_facts" SET "state"='accepted', "forgotten_at"=NULL WHERE "id"='preference-2'$statement$, 'invalid PreferenceFact lifecycle transition');

ROLLBACK;
