"""Focused generated-output tests for runtime projection and byte publication."""

import hashlib
import json
import types
import unittest
import unittest.mock
from urllib.error import URLError

from src.attempts.execution import execute_start_attempt as _execute_start_attempt
from src.constants import PROTOCOL_VERSION
from src.model_loop import generated_output_policy as _generated_output_policy
from src.model_loop.driver import translate_framework_event as _translate_framework_event
from src.model_loop.generated_output_policy import (
    validate_generated_output_batch as _validate_generated_output_batch,
)
from src.model_loop.openai_generated_outputs import OpenAIGeneratedOutputCollector as _OpenAIGeneratedOutputCollector
from src.protocol.event_projector import RuntimeEventProjector as _RuntimeEventProjector
from src.transport.output import publish_output_asset as _publish_output_asset


_CONTENT = b"\x89PNG\r\n\x1a\nexact generated bytes\x00\xff"
_TOKEN = "projected-runtime-secret"


def _compiled_input() -> dict:
    """Build the minimal frozen input needed by one start-attempt command."""
    return {
        "promptCompilerVersion": "v1",
        "runId": "run-output",
        "attempt": 2,
        "instructions": "generate one file",
        "messages": [{"role": "user", "content": "create it"}],
        "tools": [],
        "model": {"modelAlias": "silo-default", "generatedOutputCapabilities": ["image_png"]},
        "budget": {},
        "digest": "sha256:generated-output",
    }


def _start_command() -> dict:
    """Build one valid command whose coordinates must bind the output reservation."""
    return {
        "kind": "start_attempt",
        "protocolVersion": PROTOCOL_VERSION,
        "runtimeInstanceId": "runtime-output",
        "commandId": "command-output",
        "sequence": 1,
        "fence": 7,
        "assignment": {"runId": "run-output", "attempt": 2},
        "payload": {
            "snapshot": {"inputGeneration": 3},
            "compiledInput": _compiled_input(),
        },
    }


def _output_asset() -> dict:
    """Build one exact neutral generated-output event."""
    return {
        "type": "output_asset",
        "content": _CONTENT,
        "displayName": " result.png ",
        "mediaType": " image/png ",
        "outputOrdinal": 0,
        "idempotencyKey": " output-key-1 ",
    }


def _coordinates() -> dict[str, object]:
    """Build valid runtime coordinates for direct publisher failure tests."""
    return {"runId": "run-output", "attempt": 2}


class GeneratedOutputJourneyTests(unittest.TestCase):
    """Prove output projection starts a message before exact reserve and publish calls."""

    def test_output_asset_starts_message_then_reserves_and_publishes_exact_bytes(self) -> None:
        """The injected publisher receives the saved message id and sends the exact digest/body."""
        journey: list[str] = []
        emitted: list[dict] = []
        reserve_calls: list[dict[str, object]] = []
        publish_calls: list[bytes] = []

        def _post_candidate(candidate: dict) -> None:
            emitted.append(candidate)
            journey.append(str(candidate.get("eventType")))

        def _reserve(url: str, token: str, body: dict[str, object], _timeout: float):
            self.assertEqual(
                url,
                "https://control.example/internal/runtime/conversation-assets/outputs:reserve",
            )
            self.assertEqual(token, _TOKEN)
            reserve_calls.append(body)
            journey.append("reserve")
            return 201, {"outcome": "issued", "ticketId": "ticket-output"}

        def _publish(url: str, token: str, content: bytes, _timeout: float):
            self.assertEqual(
                url,
                "https://control.example/internal/runtime/conversation-assets/outputs/ticket-output/content",
            )
            self.assertEqual(token, _TOKEN)
            publish_calls.append(content)
            journey.append("publish")
            return 202, {"outcome": "accepted"}

        def _publish_output(coordinates: dict[str, object], message_id: str, output: dict[str, object]) -> None:
            _publish_output_asset(
                "https://control.example/internal/runtime/",
                _TOKEN,
                coordinates,
                message_id,
                output,
                send_json=_reserve,
                send_bytes=_publish,
            )

        _execute_start_attempt(
            _start_command(),
            "runtime-output",
            _post_candidate,
            event_source=lambda _compiled, _cancel, _steering: iter([_output_asset()]),
            publish_output=_publish_output,
        )

        self.assertEqual(
            journey,
            ["run.started", "message.started", "reserve", "publish", "message.completed", "run.completed"],
        )
        self.assertEqual(len(reserve_calls), 1)
        self.assertEqual(
            reserve_calls[0],
            {
                "runId": "run-output",
                "runAttempt": 2,
                "messageId": "assistant:command-output",
                "idempotencyKey": "model-file:" + hashlib.sha256(f"assistant:command-output\0{0}\0{hashlib.sha256(_CONTENT).hexdigest()}".encode()).hexdigest(),
                "displayName": "result.png",
                "mediaType": "image/png",
                "byteLength": len(_CONTENT),
                "contentAddress": "sha256:" + hashlib.sha256(_CONTENT).hexdigest(),
            },
        )
        self.assertEqual(publish_calls, [_CONTENT])
        self.assertNotIn(_TOKEN, json.dumps(reserve_calls[0], sort_keys=True))
        self.assertEqual(emitted[1]["payload"]["messageId"], "assistant:command-output")

    def test_projected_output_identity_is_stable_and_message_bound(self) -> None:
        """A replay keeps its key while another message or different bytes cannot collide."""
        def _key(command_id: str, content: bytes) -> str:
            published: list[dict[str, object]] = []
            projector = _RuntimeEventProjector(
                {"runId": "run-output", "attempt": 2, "commandId": command_id, "fence": 7},
                _compiled_input(),
                lambda _candidate: None,
                lambda _coordinates, _message_id, output: published.append(output),
            )
            projector.emit({**_output_asset(), "content": content, "outputOrdinal": 0})
            return str(published[0]["idempotencyKey"])

        first = _key("command-a", _CONTENT)
        self.assertEqual(first, _key("command-a", _CONTENT))
        self.assertNotEqual(first, _key("command-b", _CONTENT))
        self.assertNotEqual(first, _key("command-a", _CONTENT + b"different"))

    def test_completed_framework_file_maps_without_provider_coordinates(self) -> None:
        """The exact pinned FilePart shape maps only completed raw bytes and stable local metadata."""
        event = types.SimpleNamespace(
            event_kind="part_start",
            index=3,
            part=types.SimpleNamespace(
                part_kind="file",
                id="provider-file-secret",
                provider_name="openai",
                provider_details={"secret": "never-forward"},
                content=types.SimpleNamespace(data=_CONTENT, media_type="image/png"),
            ),
        )

        output = _OpenAIGeneratedOutputCollector().observe(event, 2)

        self.assertEqual(
            output,
            {
                "type": "output_asset",
                "content": _CONTENT,
                "displayName": f"generated-3-{hashlib.sha256(_CONTENT).hexdigest()[:12]}.png",
                "mediaType": "image/png",
                "outputOrdinal": 2,
            },
        )
        self.assertNotIn("provider", str(output).lower())
        self.assertNotIn("secret", str(output).lower())

    def test_provider_native_tool_call_is_not_an_external_action(self) -> None:
        """Image-generation bookkeeping never crosses into OpenCrane's external-action authority."""
        event = types.SimpleNamespace(
            part=types.SimpleNamespace(
                part_kind="builtin-tool-call",
                tool_name="image_generation",
                tool_call_id="provider-call",
                args_as_json_str=lambda: "{}",
            ),
        )

        self.assertEqual(_translate_framework_event(event), {"type": "output_text", "text": ""})

    def test_part_end_file_is_not_misread_as_a_second_output(self) -> None:
        """Only the pinned adapter's complete PartStartEvent shape produces one generated output."""
        event = types.SimpleNamespace(
            event_kind="part_end",
            part=types.SimpleNamespace(
                part_kind="file",
                content=types.SimpleNamespace(data=_CONTENT, media_type="image/png"),
            ),
        )

        self.assertEqual(_translate_framework_event(event), {"type": "output_text", "text": ""})

    def test_eleventh_file_rejects_the_whole_batch_before_publication(self) -> None:
        """Batch validation fails before the event iterator can yield any generated file."""
        published: list[dict[str, object]] = []

        def _source(_compiled, _cancel, _steering):
            outputs = [{**_output_asset(), "idempotencyKey": f"output-{index}"} for index in range(11)]
            _validate_generated_output_batch(outputs)
            return iter(outputs)

        emitted: list[dict] = []
        _execute_start_attempt(_start_command(), "runtime-output", emitted.append, event_source=_source, publish_output=lambda *_args: published.append(_args[-1]))

        self.assertEqual(published, [])
        self.assertEqual([event.get("eventType") for event in emitted], ["run.started", "run.failed"])

    def test_cumulative_size_rejects_the_whole_batch_before_publication(self) -> None:
        """Individually valid files cannot exceed the shared message total through partial sends."""
        published: list[dict[str, object]] = []

        def _source(_compiled, _cancel, _steering):
            outputs = [{**_output_asset(), "content": b"1234", "idempotencyKey": "first"}, {**_output_asset(), "content": b"5678", "idempotencyKey": "second"}]
            with unittest.mock.patch.object(_generated_output_policy, "MAX_GENERATED_OUTPUT_BYTES", 7):
                _validate_generated_output_batch(outputs)
            return iter(outputs)

        emitted: list[dict] = []
        _execute_start_attempt(_start_command(), "runtime-output", emitted.append, event_source=_source, publish_output=lambda *_args: published.append(_args[-1]))

        self.assertEqual(published, [])
        self.assertEqual([event.get("eventType") for event in emitted], ["run.started", "run.failed"])


class GeneratedOutputFailureTests(unittest.TestCase):
    """Prove ambiguous or refused generated-output transport is attempted only once."""

    def test_reservation_refusal_is_not_retried_and_never_publishes(self) -> None:
        """A refused reservation stops after one request without sending bytes."""
        reserve_attempts = 0
        publish_attempts = 0

        def _reserve(_url: str, _token: str, _body: dict[str, object], _timeout: float):
            nonlocal reserve_attempts
            reserve_attempts += 1
            return 503, {"outcome": "unavailable"}

        def _publish(_url: str, _token: str, _content: bytes, _timeout: float):
            nonlocal publish_attempts
            publish_attempts += 1
            return 202, {"outcome": "accepted"}

        with self.assertRaises(RuntimeError):
            _publish_output_asset(
                "https://control.example/internal/runtime",
                _TOKEN,
                _coordinates(),
                "assistant:command-output",
                _output_asset(),
                send_json=_reserve,
                send_bytes=_publish,
            )

        self.assertEqual(reserve_attempts, 1)
        self.assertEqual(publish_attempts, 0)

    def test_ambiguous_publication_failure_is_not_retried(self) -> None:
        """A byte-dispatch network failure propagates after exactly one reserve and one publish."""
        reserve_attempts = 0
        publish_attempts = 0

        def _reserve(_url: str, _token: str, _body: dict[str, object], _timeout: float):
            nonlocal reserve_attempts
            reserve_attempts += 1
            return 200, {"outcome": "idempotent", "ticketId": "ticket-existing"}

        def _publish(_url: str, _token: str, content: bytes, _timeout: float):
            nonlocal publish_attempts
            publish_attempts += 1
            self.assertEqual(content, _CONTENT)
            raise URLError("connection reset after dispatch")

        with self.assertRaises(URLError):
            _publish_output_asset(
                "https://control.example/internal/runtime",
                _TOKEN,
                _coordinates(),
                "assistant:command-output",
                _output_asset(),
                send_json=_reserve,
                send_bytes=_publish,
            )

        self.assertEqual(reserve_attempts, 1)
        self.assertEqual(publish_attempts, 1)


if __name__ == "__main__":
    unittest.main()
