import { randomUUID } from "node:crypto";

import { Absurd } from "absurd-sdk";
import pg from "pg";
import { ArtifactKind, PrismaClient } from "@prisma/client";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { _RegisterConversationGeneratedFileWorkflow } from "@opencrane/backend/server/conversation-assets";
import { McpCompanionCommandKinds } from "@opencrane/backend/server/gateways/mcp";
import { AesGcmConversationPrivatePayloadCipher } from "@opencrane/backend/server/conversations/history";
import { _CreateAbsurdWorkflowEngine } from "@opencrane/backend/server/infra/workflows/infra_absurd";
import { GeneratedFileResultKinds } from "@opencrane/contracts";
import { ___DigestCanonicalJson, type JsonValue } from "@opencrane/util";

import { _GeneratedFileInvocationResultsSqlFixture, _PrepareConversationGeneratedFileCaptureSqlFixture } from "./conversation-generated-file-capture.sql-fixture";
import { _ToolHandoffSqlRuntime, _WaitPastSqlDeadline } from "./conversation-tool-handoff.sql-fixture";

/** Independent database clients prove that capture and replay do not depend on process memory. */
const _First = new PrismaClient();
/** Recovery client used after the first MCP unit of work has committed or rolled back. */
const _Recovery = new PrismaClient();
/** Shared test-owned PostgreSQL pool used only by the real Absurd adapter. */
const _Pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, max: 4 });
/** Queue unique to this capture suite so task evidence cannot come from another test. */
const _Queue = `file-capture-${randomUUID()}`;
/** Synthetic mounted key; it never leaves this process or represents a deployment credential. */
const _Cipher = AesGcmConversationPrivatePayloadCipher.fromDocument({ currentKeyId: "generated-file-sql-key", keys: { "generated-file-sql-key": Buffer.alloc(32, 7).toString("base64url") } });
/** Reads committed Absurd task receipts without starting a workflow worker. */
let _QueueOwner: Absurd;

/** Create a new workflow facade and register the production task declaration and handler. */
function _Engine()
{
	const engine = _CreateAbsurdWorkflowEngine({ databaseUrl: process.env.DATABASE_URL!, databasePool: _Pool, databasePoolSize: 2, queueAuthority: { queueForTask: function _QueueForTask() { return _Queue; } } });
	_RegisterConversationGeneratedFileWorkflow(engine, {
		persistence: {
			async loadCurrent() { throw new Error("Capture SQL proof never starts a generated-file worker"); },
			async openVerifiedBytes() { throw new Error("Capture SQL proof never starts a generated-file worker"); },
			async finalizeQuarantine() { throw new Error("Capture SQL proof never starts a generated-file worker"); },
		},
		promotion: { async promote() { throw new Error("Capture SQL proof never calls Artifact transport"); } },
	});
	return engine;
}

/** Submit the exact claimed command and its actual generated resource result. */
function _Complete(prepared: Awaited<ReturnType<typeof _PrepareConversationGeneratedFileCaptureSqlFixture>>, claimFence = prepared.command.claimFence)
{
	return prepared.runtime.authority.completeCompanion(prepared.registered.identity, {
		executionReference: prepared.registered.executionReference,
		podUid: prepared.registered.identity.podUid,
		executionId: prepared.command.executionId,
		claimFence,
		completion: { kind: McpCompanionCommandKinds.Invocation, result: prepared.rawResult },
	});
}

/** Assert that a refused completion admitted no generated bytes, product row, or Artifact. */
async function _ExpectNoCapture(fixture: Awaited<ReturnType<typeof _PrepareConversationGeneratedFileCaptureSqlFixture>>): Promise<void>
{
	expect(await _Recovery.conversationGeneratedFile.count({ where: { runId: fixture.fixture.runId } })).toBe(0);
	expect(await _Recovery.conversationPrivatePayload.count({ where: { conversationId: fixture.fixture.turn.binding.conversationId } })).toBe(0);
	expect(await _Recovery.conversationAsset.count({ where: { conversationId: fixture.fixture.turn.binding.conversationId } })).toBe(0);
	expect(await _Recovery.artifact.count({ where: { siloId: fixture.fixture.siloId, ownerPrincipalId: fixture.fixture.principalId, kind: ArtifactKind.Generated } })).toBe(0);
}

describe("generated-file capture through real MCP completion on fresh PostgreSQL", function _Suite()
{
	beforeAll(async function _Connect()
	{
		if (!process.env.DATABASE_URL)
			throw new Error("Generated-file capture SQL proof requires DATABASE_URL and the fresh target baseline");
		await Promise.all([_First.$connect(), _Recovery.$connect()]);
		_QueueOwner = new Absurd({ db: _Pool, queueName: _Queue });
		await _QueueOwner.createQueue(_Queue);
	});
	afterAll(async function _Close()
	{
		await Promise.all([_First.$disconnect(), _Recovery.$disconnect()]);
		await _QueueOwner?.close();
		await _Pool.end();
	});

	it("captures one encrypted file, terminal result and real task across a new client and engine", async function _CaptureAndReplay()
	{
		const firstEngine = _Engine();
		const recoveryEngine = _Engine();
		try
		{
			const prepared = await _PrepareConversationGeneratedFileCaptureSqlFixture(_First, firstEngine, _Cipher);
			expect(await _Complete(prepared)).toBe("completed");
			const operation = await _Recovery.conversationGeneratedFile.findFirstOrThrow({ where: { runId: prepared.fixture.runId }, include: { chunks: true } });
			const invocation = await _Recovery.toolInvocation.findFirstOrThrow({ where: { runId: prepared.fixture.runId }, include: { resultDelivery: true } });
			expect(prepared.taskReceipts).toHaveLength(1);
			expect(operation.workflowTaskId).toBe(prepared.taskReceipts[0]!.taskId);
			expect(await _QueueOwner.fetchTaskResult(operation.workflowTaskId)).not.toBeNull();
			expect(operation).toMatchObject({ toolInvocationRowId: invocation.id, rawResultDigest: ___DigestCanonicalJson(prepared.rawResult as unknown as JsonValue), displayName: "county-totals.csv", mediaType: "text/csv;charset=utf-8", chunkCount: 1 });
			expect(operation.chunks).toHaveLength(1);
			expect(await _Recovery.conversationGeneratedFile.count({ where: { runId: prepared.fixture.runId } })).toBe(1);
			expect(await _Recovery.conversationPrivatePayload.count({ where: { conversationId: prepared.fixture.turn.binding.conversationId } })).toBe(1);
			expect(invocation).toMatchObject({ state: "Succeeded", result: { isError: false, content: [{ type: "text", text: "Generated file captured and queued for safety scanning." }], structuredContent: { kind: GeneratedFileResultKinds.Captured, operationId: operation.id, assetId: operation.assetId, artifactId: operation.artifactId, artifactRevisionId: operation.revisionId, rawResultDigest: operation.rawResultDigest, displayName: operation.displayName, mediaType: operation.mediaType, byteLength: Number(operation.byteLength) } } });
			expect(invocation.resultDelivery?.payload).toEqual({ toolInvocationId: invocation.toolInvocationId, outcome: "succeeded", result: invocation.result });

			const replayReceipts: typeof prepared.taskReceipts extends readonly (infer Receipt)[] ? Receipt[] : never = [];
			const replayWorkflows = { spawn: async function _Spawn<Input>(transaction: Parameters<typeof recoveryEngine.spawn<Input>>[0], task: Parameters<typeof recoveryEngine.spawn<Input>>[1])
			{
				const receipt = await recoveryEngine.spawn(transaction, task);
				replayReceipts.push(receipt);
				return receipt;
			} };
			const replayResults = _GeneratedFileInvocationResultsSqlFixture(prepared.fixture, _Cipher, replayWorkflows);
			const replayRuntime = _ToolHandoffSqlRuntime(_Recovery, prepared.fixture, 300_000, replayResults);
			expect(await replayRuntime.authority.completeCompanion(prepared.registered.identity, {
				executionReference: prepared.registered.executionReference,
				podUid: prepared.registered.identity.podUid,
				executionId: prepared.command.executionId,
				claimFence: prepared.command.claimFence,
				completion: { kind: McpCompanionCommandKinds.Invocation, result: prepared.rawResult },
			})).toBe("idempotent");
			expect(replayReceipts).toEqual([]);
			expect(await _Recovery.conversationGeneratedFile.count({ where: { runId: prepared.fixture.runId } })).toBe(1);
			expect(await _Recovery.toolResultDelivery.count({ where: { toolInvocationId: invocation.id } })).toBe(1);
		}
		finally
		{
			await firstEngine.close();
			await recoveryEngine.close();
		}
	});

	it("rolls back encrypted custody, product rows and the real task when IAM terminalization does not follow capture", async function _CaptureRollback()
	{
		const engine = _Engine();
		try
		{
			const prepared = await _PrepareConversationGeneratedFileCaptureSqlFixture(_First, engine, _Cipher, { afterCapture: async function _FailAfterCapture()
			{
				throw new Error("injected failure after generated-file capture");
			} });
			await expect(_Complete(prepared)).rejects.toThrow("injected failure after generated-file capture");
			expect(prepared.taskReceipts).toHaveLength(1);
			expect(await _QueueOwner.fetchTaskResult(prepared.taskReceipts[0]!.taskId)).toBeNull();
			await _ExpectNoCapture(prepared);
			const invocation = await _Recovery.toolInvocation.findFirstOrThrow({ where: { runId: prepared.fixture.runId } });
			expect(invocation).toMatchObject({ state: "Claimed", result: null });
			expect(await _Recovery.toolResultDelivery.count({ where: { toolInvocationId: invocation.id } })).toBe(0);
		}
		finally { await engine.close(); }
	});

	it.each(["claim fence", "expired lease"] as const)("refuses a stale %s before capture", async function _RejectsStaleAuthority(stale)
	{
		const engine = _Engine();
		try
		{
			const prepared = await _PrepareConversationGeneratedFileCaptureSqlFixture(_First, engine, _Cipher, { companionLeaseMs: 1_000, runLifetimeMs: 4_000 });
			if (stale === "expired lease")
				await _WaitPastSqlDeadline(_Recovery, Date.parse(prepared.command.expiresAt));
			const fence = stale === "claim fence" ? randomUUID() : prepared.command.claimFence;
			expect(await _Complete(prepared, fence)).toBe("conflict");
			expect(prepared.taskReceipts).toEqual([]);
			await _ExpectNoCapture(prepared);
			const invocation = await _Recovery.toolInvocation.findFirstOrThrow({ where: { runId: prepared.fixture.runId } });
			expect(invocation).toMatchObject({ state: "Claimed", result: null });
		}
		finally { await engine.close(); }
	}, 15_000);
});
