/** Immutable participant conversation entry schema shared by KurrentDB history responses. */
const _ConversationEntrySchema = { type: "object", additionalProperties: true, required: ["schemaVersion", "id", "conversationId", "position", "kind", "author", "provenance", "visibility", "runId", "causationId", "correlationId", "idempotencyKey", "occurredAt", "attestation"], properties: { schemaVersion: { type: "integer", enum: [1] }, id: { type: "string", format: "uuid" }, conversationId: { type: "string" }, position: { type: "string", pattern: "^(0|[1-9][0-9]*)$" }, kind: { type: "string", enum: ["message", "log", "a2ui"] }, author: { type: "object" }, provenance: { type: "string", enum: ["human-authored", "agent-authored", "service-attested"] }, visibility: { type: "object" }, runId: { type: ["string", "null"] }, causationId: { type: "string" }, correlationId: { type: "string" }, idempotencyKey: { type: "string" }, occurredAt: { type: "string", format: "date-time" }, attestation: { type: ["object", "null"] } } } as const;
/** Projection summary schema that contains opaque membership references but no transcript. */
const _SummarySchema = { type: "object", additionalProperties: false, required: ["id", "mode", "lifecycle", "agentServiceId", "participantRefs", "archivedAt", "readThroughPosition", "updatedAt"], properties: { id: { type: "string" }, mode: { type: "string", enum: ["agent_session", "direct", "group"] }, lifecycle: { type: "string", enum: ["open", "closed"] }, agentServiceId: { type: ["string", "null"] }, participantRefs: { type: "array", items: { type: "string" } }, archivedAt: { type: ["string", "null"], format: "date-time" }, readThroughPosition: { type: "string" }, updatedAt: { type: "string", format: "date-time" } } } as const;
/** Projection detail adds participant bounds but deliberately has no relational messages field. */
const _DetailSchema = { ..._SummarySchema, required: [..._SummarySchema.required, "visibleFromPosition", "accessEndedPosition"], properties: { ..._SummarySchema.properties, visibleFromPosition: { type: "string" }, accessEndedPosition: { type: ["string", "null"] } } } as const;
/** Exact projection detail envelope shared by lifecycle operations. */
const _DetailEnvelopeSchema = { type: "object", additionalProperties: false, required: ["conversation"], properties: { conversation: _DetailSchema } } as const;
/** Shared path coordinate for every active-computer review operation. */
const _ReviewConversationParameter = { name: "conversationId", in: "path", required: true, schema: { type: "string" } } as const;
/** Shared relative workspace path used by file and diff review. */
const _ReviewPathParameter = { name: "path", in: "query", required: true, schema: { type: "string", minLength: 1 } } as const;
/** Bounded command response returned by the private computer review surface. */
const _ReviewCommandSchema = { type: "object", additionalProperties: false, required: ["exitCode", "outcome", "output", "truncated"], properties: { exitCode: { type: ["integer", "null"] }, outcome: { type: "string", enum: ["completed", "timed_out", "output_limited"] }, output: { type: "string" }, truncated: { type: "boolean" } } } as const;

/** OpenAPI fragment for participant-authorized KurrentDB conversation history. */
export const _SelfConversationHistoryOpenapiPaths = {
	"/me/conversations/directory": { get: { operationId: "getMyConversationCreationDirectory", responses: { 200: { description: "Projection-only creation directory.", content: { "application/json": { schema: { type: "object", required: ["directory"], properties: { directory: { type: "object", required: ["participants", "personalAgentStatus", "personalAgent"], properties: { participants: { type: "array", items: { type: "object", required: ["participantRef", "isSelf"], properties: { participantRef: { type: "string" }, isSelf: { type: "boolean" } } } }, personalAgentStatus: { type: "string", enum: ["ready", "unavailable", "ambiguous"] }, personalAgent: { type: ["object", "null"] } } } } } } } } } } },
	"/me/conversations": { get: { operationId: "listMyConversations", parameters: [{ name: "includeArchived", in: "query", required: false, schema: { type: "boolean" } }], responses: { 200: { description: "Participant conversation projections.", content: { "application/json": { schema: { type: "object", required: ["conversations"], properties: { conversations: { type: "array", items: _SummarySchema } } } } } } } }, post: { operationId: "createMyConversation", requestBody: { required: true, content: { "application/json": { schema: { oneOf: [{ type: "object", required: ["mode", "personalAgentRef"], properties: { mode: { const: "agent_session" }, personalAgentRef: { type: "string" } } }, { type: "object", required: ["mode", "participantRefs"], properties: { mode: { type: "string", enum: ["direct", "group"] }, participantRefs: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 99 } } }] } } } }, responses: { 201: { description: "Conversation projection created.", content: { "application/json": { schema: _DetailEnvelopeSchema } } }, 404: { description: "Creation target unavailable." } } } },
	"/me/conversations/{conversationId}": { get: { operationId: "openMyConversation", parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }], responses: { 200: { description: "Conversation projection without transcript data.", content: { "application/json": { schema: _DetailEnvelopeSchema } } }, 404: { description: "Conversation unavailable." } } } },
	"/me/conversations/{conversationId}/archive": { patch: { operationId: "archiveMyConversation", parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["archived"], properties: { archived: { type: "boolean" } } } } } }, responses: { 200: { description: "Participant archive projection changed.", content: { "application/json": { schema: _DetailEnvelopeSchema } } }, 404: { description: "Conversation unavailable." } } } },
	"/me/conversations/{conversationId}/close": { post: { operationId: "closeMyConversation", parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }], responses: { 200: { description: "Conversation projection closed.", content: { "application/json": { schema: _DetailEnvelopeSchema } } }, 404: { description: "Conversation unavailable." } } } },
	"/me/conversations/{conversationId}/history": { get: { operationId: "readMyConversationHistory", summary: "Read participant-visible conversation history", description: "Reads immutable KurrentDB entries after an exclusive position cursor, then separately decrypts only private payloads referenced by entries visible to the currently authorized participant.", tags: ["Conversations"], parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }, { name: "afterPosition", in: "query", required: false, schema: { type: "string", pattern: "^(0|[1-9][0-9]*)$" }, description: "Exclusive immutable stream position." }], responses: { 200: { description: "Authorized immutable history and separately decrypted payloads.", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["entries", "payloads", "nextPosition", "computer"], properties: { entries: { type: "array", items: _ConversationEntrySchema }, payloads: { type: "object", additionalProperties: { type: "string" } }, nextPosition: { type: "string", pattern: "^(0|[1-9][0-9]*)$" }, computer: { type: ["object", "null"] } } } } } }, 400: { description: "Malformed position cursor." }, 401: { description: "Authentication required." }, 404: { description: "Conversation is unavailable to the current participant." }, 503: { description: "Conversation history or private payload authority unavailable." } } } },
	"/me/conversations/{conversationId}/messages": { post: { operationId: "postMyConversationMessage", summary: "Post one encrypted participant message", description: "Encrypts plaintext before PostgreSQL persistence and appends only an opaque payload reference and ciphertext digest to KurrentDB.", tags: ["Conversations"], parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["idempotencyKey", "text", "activation"], properties: { idempotencyKey: { type: "string", format: "uuid" }, text: { type: "string", minLength: 1, maxLength: 65536 }, activation: { type: "string", enum: ["none", "start", "interrupt"] } } } } } }, responses: { 202: { description: "A new immutable entry was accepted.", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["outcome", "position"], properties: { outcome: { type: "string", enum: ["accepted"] }, position: { type: "string" } } } } } }, 200: { description: "The exact immutable entry was already accepted.", content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["outcome", "position"], properties: { outcome: { type: "string", enum: ["idempotent"] }, position: { type: "string" } } } } } }, 400: { description: "Malformed message command." }, 401: { description: "Authentication required." }, 404: { description: "Conversation is unavailable to the current participant." }, 409: { description: "Idempotency or activation conflict." }, 503: { description: "Conversation history or private payload authority unavailable." } } } },
	"/me/conversations/{conversationId}/review/files": { get: { operationId: "readMyConversationComputerFile", summary: "Read one computer workspace file", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter, _ReviewPathParameter], responses: { 200: { description: "Bounded file bytes.", content: { "application/octet-stream": { schema: { type: "string", format: "binary" } } } }, 404: { description: "Active computer unavailable." }, 503: { description: "Review surface unavailable." } } } },
	"/me/conversations/{conversationId}/review/diff": { get: { operationId: "readMyConversationComputerDiff", summary: "Read one workspace diff", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter, _ReviewPathParameter], responses: { 200: { description: "Bounded diff command result.", content: { "application/json": { schema: _ReviewCommandSchema } } }, 404: { description: "Active computer unavailable." }, 503: { description: "Review surface unavailable." } } } },
	"/me/conversations/{conversationId}/review/commands": { post: { operationId: "runMyConversationComputerCommand", summary: "Run one allowlisted workspace command", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["argv"], properties: { argv: { type: "array", minItems: 1, items: { type: "string", minLength: 1 } }, cwd: { type: "string" } } } } } }, responses: { 200: { description: "Bounded command result.", content: { "application/json": { schema: _ReviewCommandSchema } } }, 404: { description: "Active computer unavailable." }, 503: { description: "Review surface unavailable." } } } },
	"/me/conversations/{conversationId}/review/browser/version": { get: { operationId: "readMyConversationComputerBrowserVersion", summary: "Read private browser metadata", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter], responses: { 200: { description: "Chromium version metadata.", content: { "application/json": { schema: { type: "object", additionalProperties: true } } } }, 404: { description: "Active computer unavailable." } } } },
	"/me/conversations/{conversationId}/review/browser/targets": { get: { operationId: "listMyConversationComputerBrowserTargets", summary: "List private browser pages", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter], responses: { 200: { description: "Current Chromium targets.", content: { "application/json": { schema: { type: "array", items: { type: "object", additionalProperties: true } } } } }, 404: { description: "Active computer unavailable." } } } },
	"/me/conversations/{conversationId}/review/browser/pages": { post: { operationId: "openMyConversationComputerBrowserPage", summary: "Open an allowlisted localhost page", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["port", "path"], properties: { port: { type: "integer" }, path: { type: "string" } } } } } }, responses: { 201: { description: "Created Chromium target.", content: { "application/json": { schema: { type: "object", additionalProperties: true } } } }, 404: { description: "Active computer unavailable." } } } },
	"/me/conversations/{conversationId}/review/browser/screenshots": { post: { operationId: "captureMyConversationComputerBrowserScreenshot", summary: "Capture an allowlisted localhost page", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["port", "path", "width", "height"], properties: { port: { type: "integer" }, path: { type: "string" }, width: { type: "integer" }, height: { type: "integer" } } } } } }, responses: { 200: { description: "PNG screenshot.", content: { "image/png": { schema: { type: "string", format: "binary" } } } }, 404: { description: "Active computer unavailable." } } } },
	"/me/conversations/{conversationId}/review/previews/{port}/{path}": { get: { operationId: "readMyConversationComputerPreview", summary: "Read an allowlisted localhost preview", tags: ["Conversation computer review"], parameters: [_ReviewConversationParameter, { name: "port", in: "path", required: true, schema: { type: "integer" } }, { name: "path", in: "path", required: true, schema: { type: "string" } }], responses: { 200: { description: "Preview response body.", content: { "text/html": { schema: { type: "string" } }, "text/plain": { schema: { type: "string" } }, "application/json": { schema: {} } } }, 400: { description: "Preview port or path unavailable." }, 404: { description: "Active computer unavailable." } } } },
} as const;
